### ISSUE TITLE
game randomly freezes when in dialogue

### ISSUE THREAD

**Issue by PTH2023** [yaagl/yet-another-anime-game-launcher#110]
**Describe the bug**
maybe it's not so random because the game freezes in specific parts of the in game dialogue and even if you close it and open it again it will freeze at the same time again

**Screenshots**
sorry but i don't have any

 - macOS: [13.3.1 Ventura]
 - Device: [MacbookPro 14 inch 2021]
 - CPU: [Apple M1 pro]
 - RAM: [ 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11581621/neutralinojs.log)

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
[game_1685214440926.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11582846/game_1685214440926.log)
[game_1685214323148.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11582847/game_1685214323148.log)

**Comment by 3Shain** [comment]
The log you uploaded is created on Apr 21st. Please upload the latest one.

**Comment by PTH2023** [comment]
i opened the game again two times and waited for it to freeze. these are the logs
[game_1685214440926.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11582846/game_1685214440926.log)
[game_1685214323148.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11582847/game_1685214323148.log)

**Comment by 3Shain** [comment]
Which wine version did you use

**Comment by PTH2023** [comment]
i use gi-wine-1.2 but i also tried using gi-wine-1.0 an it still has the same problem

**Comment by PEACEBOI712** [comment]
this happen to me as well , while playing the audio plays but the game is stuck

**Comment by PEACEBOI712** [comment]
https://drive.google.com/file/d/1sqthtfXcQEfcMpu8zPmZTwP5gjb95FJ4/view?usp=sharing
 the evidence

**Comment by ymatuhin** [comment]
Same for me

**Comment by PEACEBOI712** [comment]
it happens only during cut. scenes , it happens only in sumeru for me but the best solution I found is to use other devices like iPhone , pc ,android or a play cover emulator to finish the particular cutscene and you resume the game in Mac

**Comment by dancju** [comment]
When freezes occur, the FPS seems often (if not always) to be 30.1. Did you guys also notice the same pattern?

**Comment by NDENiSko** [comment]
Managed to get past these crashes by lowering graphics to minimum.

**Comment by PEACEBOI712** [comment]
ok

**Comment by PEACEBOI712** [comment]
I also had low graphics but issue persists I think

**Comment by mozzzi2222** [comment]
The same problem happens to me.. Please help me

**Comment by Menelkir** [comment]
Do you still have this issue?
