### ISSUE TITLE
Genshin Freezing Seconds Into Sign In

### ISSUE THREAD

**Issue by SpeedyPlanet** [yaagl/yet-another-anime-game-launcher#116]
**Describe the bug**
Whenever I sign in to start playing genshin it goes to the loading screen and then breaks. It freezes and the sound plays for a while before it just fully crashes.
**Screenshots**
Just the opening GI Screen with sky and pillars.

**System Information (please complete the following information):**
 - macOS: 13.2 Ventura
 - Device: MacbookPro 14inch 2023 
 - CPU: Apple M2 Pro
 - RAM: 16G 

**Additional context**
This is my first time using yaagl and I am able to install the game fine I just can't open it to the main menu screen for more than a couple of seconds before crash.

**Comment by Menelkir** [comment]
Still persists?

**Comment by Menelkir** [comment]
No replies, I will close this issue. Feel free to open if this problem persists.
