### ISSUE TITLE
Yaagl can't be opened ( Sonoma )

### ISSUE THREAD

**Issue by AikoMidori** [yaagl/yet-another-anime-game-launcher#117]
**Describe the bug**
Yaagl doesn't open, message: This application "Yaagl OS" can't be opened.

**Screenshots**
<img width="286" alt="Screenshot 2023-06-06 at 11 22 10" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/44128092/b52bc503-e9c2-44d1-b335-0a717b51f0b5">

**System Information (please complete the following information):**
 - macOS: [ 14.0 dev b1 Sonoma ]
 - Device: [ MacbookPro 16inch 2021 ]
 - CPU: [ Apple M1 Pro ]

**Additional context**

**Logs**
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11662692/neutralinojs.log)

**Comment by cyanoide** [comment]
It's because it's still not verified. Disable csrutil and you will be able to play again (worked for me)

Macbook Air M1 14.0 dev b1 sonoma

**Comment by AikoMidori** [comment]
> It's because it's still not verified. Disable csrutil and you will be able to play again (worked for me). However Wine doesn't seem to work so it won't change much the issue
> 
> Macbook Air M1 14.0 dev b1 sonoma

Gotcha, will wait for an update then.

**Comment by Micuks** [comment]
Same problem. Here's the log from when I try to follow the steps given in `Development`. 

<img width="1512" alt="Screenshot 2023-06-20 at 3 29 12 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/43397551/edb97a83-999c-4c80-9f20-96f192f599d2">

```bash
Error: Command return non-zero code
WINEESYNC=1 WINEDEBUG=fixme-all,err-unwind,+timestamp,trace+seh WINEPREFIX=/Users/micuks/local/games/genshin/yet-another-anime-game-launcher/yaaglwd/wineprefix GIWINEPCNAME=DESKTOP-2G8ULLK GIWINECPUNAME=Intel\(R\)\ Core\(TM\)\ i7-8569U\ CPU\ @\ 2.80GHz GIWINECPUFREQ=2800 GIWINECPUVID=GenuineIntel GIWINESYSMANU=OEM GIWINESYSPRODNAME=Generic\ x86-64 GIWINESYSFAML=B350 /Users/micuks/local/games/genshin/yet-another-anime-game-launcher/yaaglwd/wine/bin/wine64 wineboot -u &> /dev/null
StdOut:

StdErr:
```

Error log in terminal:
```bash
INFO 2023-06-20 15:28:53,333 {"architecture":"arm","frequency":0,"logicalThreads":8,"model":"Apple M1 Pro","physicalCores":8,"physicalUnits":1,"vendor":""} api/debug/debug.cpp:17 micuks@unknown-host
INFO 2023-06-20 15:28:53,333 WINEESYNC=1 WINEDEBUG=fixme-all,err-unwind,+timestamp,trace+seh
WINEPREFIX=/Users/micuks/local/games/genshin/yet-another-anime-game-launcher/yaaglwd/wineprefix GIWINEPCNAME=DESKTOP-2G8ULLK GIWINECPUNAME=Intel\(R\)\ Core\(TM\)\ i7-8569U\ CPU\ @\ 2.80GHz GIWINECPUFREQ=2800 GIWINECPUVID=GenuineIntel GIWINESYSMANU=OEM GIWINESYSPRODNAME=Generic\
x86-64 GIWINESYSFAML=B350 /Users/micuks/local/games/genshin/yet-another-anime-game-launcher/yaaglwd/wine/bin/wine64 wineboot -u &> /dev/null api/debug/debug.cpp:17 micuks@unknown-host
INFO 2023-06-20 15:30:24,299 killing process 60102 api/debug/debug.cpp:17 micuks@unknown-hostINFO 2023-06-20 15:30:24,302 kill 60102 api/debug/debug.cpp:17 micuks@unknown-host
neu: WARNING neutralino-mac_arm64 was stopped with error code 255
```

**Comment by 1146839821** [comment]
cd Yaagl/Contents/MacOS
double click parameterized   to run.

**Comment by crustyxoxo** [comment]
> cd Yaagl/Contents/MacOS double click parameterized to run.

Im new to all this so would i paste this in Terminal for my MacPro m1 2023?

**Comment by 1146839821** [comment]
> > cd Yaagl/Contents/MacOS double click parameterized to run.
> 
> Im new to all this so would i paste this in Terminal for my MacPro m1 2023?

If you don't know how to do it, you can try my fixed version without executing any commands.
[https://github.com/1146839821/yet-another-anime-game-launcher/releases](url)

**Comment by fashalul** [comment]
heyyyyy so this is what it tells me when I want to run it how do I fix it?
<img width="271" alt="Screenshot 2023-12-31 at 3 33 32 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/155303601/1f417559-40d5-46f9-a262-91700c8d0373">
