### ISSUE TITLE
Error message (Sonoma) 

### ISSUE THREAD

**Issue by GooseQuackQuack** [yaagl/yet-another-anime-game-launcher#127]
**Describe the bug**
Unable to use the launcher due to an error message 

**Screenshots**
![image](https://github.com/3Shain/yet-another-anime-game-launcher/assets/137754176/de3b95f4-1f78-4a58-ad1b-5f9f51066874)

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [Macbook air M2]
 - CPU: [eApple M2]
 - RAM: [e.g. 8G ]

**Additional context**

**Logs (if any)**

**Comment by fivehanz** [comment]
same issue, sonoma.

**Comment by Menelkir** [comment]
Is this still an issue?

**Comment by Menelkir** [comment]
No replies, I will close this issue for now. Feel free to reopen the issue if the problem persists.
