### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by ajsid09** [yaagl/yet-another-anime-game-launcher#135]
**Describe the bug**

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
 - CPU: [e.g. Apple M1 ]
 - RAM: [e.g. 16G ]

**Additional context**
hey, the anime game When I start to play a quest it runs for a few minutes but after that shows a black screen

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by frowing37** [comment]
I have this bug

macOS : 13.4.1
Device : MacbookAir 13inch 2022
CPU : Apple M2
RAM : 16GB

**Comment by Menelkir** [comment]
Do you still have this issue?

**Comment by Menelkir** [comment]
No replies so I will close this issue for now, feel free to reopen if the problem persists.
