### ISSUE TITLE
Can't login and start game 

### ISSUE THREAD

**Issue by stephaniehuang66** [yaagl/yet-another-anime-game-launcher#136]
After typing in my username and password, a white box pops up. Usually it asks me to drag a puzzle to complete a picture but now it just shows up as blank and I can't move forward with loading the game. 

I was able to play genshin before, but it crashed after doing a spiral abyss. After restarting the game and my computer several times, I can't login anymore because of this isssue. I also trying verifying the game but it still doesn't work. Any help would be greatly appreciated! 
![20230709_115355](https://github.com/3Shain/yet-another-anime-game-launcher/assets/139070540/3e206173-6936-4745-87c4-0d53114ab25e)

**System Information (please complete the following information):**
 - macOS: Macbook Pro 2021
 - Device: [MacbookPro 2021
 - CPU: Intel Iris Plus Graphics 1536 MB
 - RAM: 16 G

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by 3606pizza** [comment]
Hi! Not sure if you have fixed this issue, but I had the same problem and just recently solved it.

If you open YAAGL OS application and go to the settings icon, you will see a quick link titled "Open Game Install Directory" under quick actions. 

Upon clicking it, you will see that the game files. Go to the "Genshinimpact_data" folder and scroll to the bottom. Here you will want to simply delete the "Webcaches" folder. 

Relaunch YAAGL OS and open up Genshin Impact. Sign in again and it should give you the verification puzzle! This is what worked for me.

**Comment by limitedink** [comment]
I deleted Webcaches and it still didn't work :/

**Comment by stephaniehuang66** [comment]
Hey! I fixed the issue. At the game launcher go to settings > game > make sure the "turn off the AC patch" isn't enabled. It worked for me after I unchecked the box!

**Comment by cordovaputra** [comment]
> Hey! I fixed the issue. At the game launcher go to settings > game > make sure the "turn off the AC patch" isn't enabled. It worked for me after I unchecked the box!

Unchecking the Turn off the AC Patch resulting the _The launcher currently doesn't support version 4.0.0 currently, please wait for further updates_ error
