### ISSUE TITLE
Repetitive and never ending file download. The file size at the launcher is always 10 GB in size. Also error: fail to launch aria2

### ISSUE THREAD

**Issue by khraumz** [yaagl/yet-another-anime-game-launcher#137]
**Describe the bug**

**Screenshots**
<img width="1179" alt="image" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/139090549/4896a6e7-c829-4b17-bc91-3602c7c1cb60">
<img width="419" alt="Screenshot 2023-07-10 at 09 27 09" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/139090549/14e1acfc-d93c-4131-ab0f-1ce63d96de75">
<img width="552" alt="image" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/139090549/6e7abd7c-3b9b-4119-a573-7274e9659b27">

**System Information (please complete the following information):**
 - macOS: 13.4.1 Ventura
 - Device: MacbookPro 13inch 2020
 - CPU: Apple M1
 - RAM: 16G

**Additional context**
Whenever I started downloading the file, my empty game installation directory folder suddenly showing up with 10,7 GB of size .

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by JsCoderCole** [comment]
I had the same issue! I noticed that when I disable any **VPNs** I had, it stopped doing that. I don't know why, but it worked for me. I hope this helps

**Comment by JsCoderCole** [comment]
When downloading the game. It will create GenshinImpact_3.8.0.zip.001 six times, each being 10 GB. Meaning that you'll see:

- GenshinImpact_3.8.0.zip.001 (10GB)
- Then another GenshinImpact_3.8.0.zip.002 (10GB)
- Up to GenshinImpact_3.8.0.zip.006 (10GB)

You should restart the downloading process. Disable any VPNs, and maintain a stable internet connection. Finally, do not close the launcher while it's downloading.

**Comment by valeriorussotto** [comment]
so, should i download 6 times the 10GB file and then the game will work?

**Comment by Menelkir** [comment]
This is covered on the FAQ now.
https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#1-the-game-is-downloading-so-many-zip-pieces-how-many-does-it-need-to-download
