### ISSUE TITLE
anime games spot running after 2 to 3 minutes

### ISSUE THREAD

**Issue by ajsid09** [yaagl/yet-another-anime-game-launcher#139]
**Describe the bug**
black screen with background sound still running 

**Screenshots**
[Screenshot 2023-07-09 at 3 35 28 PM](https://github.com/3Shain/yet-another-anime-game-launcher/assets/138990727/335f8ab8-a020-4c38-ac69-b67c21809324)

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 13 ]
 - CPU: [e.g. Apple M1 ]
 - RAM: [e.g. 16G ]

**Additional context**
anime game GI stops after playing for 2 minutes and shows a completely black screen but the background sound is still running. I reinstall the launcher and check integrity.

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
Do you still have this issue?

**Comment by Menelkir** [comment]
No replies so I will close this issue for now, feel free to reopen if the problem persists.
