### ISSUE TITLE
Crash game when downloading all voice-over

### ISSUE THREAD

**Issue by Trung113395** [yaagl/yet-another-anime-game-launcher#144]
**Describe the bug**
When I am downloading Japanese voice, they have checked file integrity done then downloading. But... downloaded 24MB GI crash
Update: I have tried to download Chinese and Korean, it's crash too

**System Information (please complete the following information):**
 - macOS: 13.4.1(c) Ventura
 - Device: Macbook Air 2022
 - CPU: Apple M2
 - Dedicated GPU: Apple M2 GPU
 - RAM: 8GB

**Comment by fivehanz** [comment]
I have the same issue, but crashes even before it gets a chance to download.

macOS: Sonoma 14.0
Device: Mac mini m1
CPU: Apple M1
Dedicated GPU: Apple M1 
RAM: 8GB

I tried to download mandarin voice

**Comment by veeberry** [comment]
I had the same issue but I found a way to work around it. 

What I did was change my region and language to Japan/Japanese and re-downloaded the launcher/game. 

Even though the intro scene still played in English, when I went to the settings, the Japanese voices pack was pre-downloaded onto the game and I could change it without having to download it after booting up the game for the first time. :)

Hope this helps!

**Comment by Trung113395** [comment]
Well, I downloaded Japanese voiceover on Parallel and it done too. If your Mac has enough language, you can try this way

**Comment by hueclouds** [comment]
How do I change my region? I want to get the Korean Voiceover 😭😭

**Comment by Menelkir** [comment]
> How do I change my region? I want to get the Korean Voiceover 😭😭

Inside the game settings.
