### ISSUE TITLE
Game will not launch (Sonoma)

### ISSUE THREAD

**Issue by fizzywizzywoozy** [yaagl/yet-another-anime-game-launcher#145]
**Describe the bug**
I downloaded the launcher today, and downloaded the game. When I tried to launch it it only gave me this error every time. I'm not too great at this stuff, but I was hoping someone could help me out here. I'm using the beta 14.0 sonoma.. I also did open the launcher through 'paramaterized' since it did previously give me the error that tha launcher could not be opened.

![Screenshot 2023-07-18 at 6 18 28 PM](https://github.com/3Shain/yet-another-anime-game-launcher/assets/139929286/3e6357e3-9584-46fc-976a-8b2bb6c8c7ac)

 - macOS: Sonoma 14.0
 - Device: Mac Mini m1 late 2020
 - CPU: M1
 - RAM: 8gb

I'm also pretty new to github so im sorry if im doing anything wrong..

**Comment by 1146839821** [comment]
I didn't repeat this issue.
according to the error message of your screenshot, it should be dxgli.dll is missing.
[https://github.com/3Shain/winecx/releases/tag/gi-wine-1.0](url) download and copy  then retry

**Comment by MKSlegal** [comment]
hey did you get it working? Im having the same issue

**Comment by Menelkir** [comment]
I will close this for now. Please reopen if you still have this issue.
