### ISSUE TITLE
The launcher fires an error when trying to open it

### ISSUE THREAD

**Issue by Sh1buraji** [yaagl/yet-another-anime-game-launcher#147]
The launcher fires a fatal error when trying to open it.

<img width="465" alt="SCR-20230721-qbbr" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/140177673/3710b524-a61c-49e2-92cc-2b71aae1650b">

System Information:-
 - macOS: 13.4.1(c) Ventura
 - Device: MacbookAir 13inch 2020 
 - CPU: Apple M1
 - RAM: 8G

**Comment by Menelkir** [comment]
Do you still have this issue?
