### ISSUE TITLE
What should I do?

### ISSUE THREAD

**Issue by Caaasterrr** [yaagl/yet-another-anime-game-launcher#151]
I wanted to reinstall the launcher, so I deleted the entire Yaagl os folder. After that, I re-installed it and then this error when starting the game
<img width="1440" alt="Снимок экрана 2023-07-28 в 01 38 47" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/119026772/7b4e7622-cb6b-485e-92f2-4e0c9b111e47">

 - macOS: macOS Monterey
 - Device: MacBook Pro (13-inch, M1, 2020)
 - CPU: M1
 - RAM: 8gb

**Comment by MKSlegal** [comment]
hii im having the same issue? Did you manage to get through?

**Comment by Menelkir** [comment]
Do you still have this issue?
