### ISSUE TITLE
Very Huge Logs Files (100GB) 

### ISSUE THREAD

**Issue by sasunnhkd** [yaagl/yet-another-anime-game-launcher#152]
**Describe the bug**
My Mac mini suddenly out of storage, I checked and found that this anime game launcher application folder was about 100GB. Then I found the logs folder under Yaagl OS/logs is full of game_[date].log files. Some files were more than 50GB. Why the logs were so huge? Any logrotation mechanism to purge the log automatically? 

**Screenshots**
<img width="723" alt="Screenshot 2023-07-29 at 01 59 09" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/38094148/eb05ff60-1ff0-4bb0-b252-12c97473c50a">

<img width="1113" alt="Screenshot 2023-07-29 at 01 59 43" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/38094148/e8167c30-277e-45c7-95c7-49678f652ad1">

**System Information (please complete the following information):**
 - macOS: 13.5 Ventura
 - Device: Mini M2 8GB/256GB
 - CPU: M2
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: 8GB

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by caozhaoqi** [comment]
me too

**Comment by sarahwest** [comment]
Can you tell me the path of the folder?

**Comment by Trung113395** [comment]
I used CleanMyMac X to solve this problem, and I don't know how to stop these logs created. Moreover, GI 4.0 maybe up to 58GB (idk it's fake new or real...)

**Comment by iambitkov** [comment]
<img width="377" alt="Screenshot 2023-09-12 at 10 18 32" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/121220757/0a1074b5-cb40-4ede-bc79-03c8e8785177">
Today I also encountered this problem, only I ended up with 360 GB of logs... This is terrible, it needs to be fixed...

**Comment by Menelkir** [comment]
You can safely delete those logs.
