### ISSUE TITLE
Non-Functional Vertical Mouse Control in the Game ;(

### ISSUE THREAD

**Issue by MarynaPetrova** [yaagl/yet-another-anime-game-launcher#153]
Description:
I encountered a bug with mouse control while playing the game. During the initial launch, the mouse control functioned correctly. However, in subsequent game sessions, I noticed that the mouse's ability to control the camera vertically has ceased to work. The horizontal movement of the mouse remains functional, but there is no response when attempting to move the camera up or down. It's important to note that the mouse behaves as expected within the game's menu, suggesting that the issue is isolated to gameplay.

System Information:

macOS: [Mac OS sonoma beta 4]
Device: [MacbookPro 14inch 2021]
CPU: [Apple M1 pro]
RAM: [16G]

**Comment by Menelkir** [comment]
Do you still have this issue?
