### ISSUE TITLE
Update support for HSR and HI3

### ISSUE THREAD

**Issue by Boomspring** [yaagl/yet-another-anime-game-launcher#155]
**Is your feature request related to a problem? Please describe.**
Having troubles getting the games working using CX or Wine on MacOS (current patches), so... it would be nice is support was added back again here.

**Describe the solution you'd like**
Any chance that you / people have been able to get them working? Mainly errors re. Qt5WebProcess or a page fault immediately upon launching the game via default launcher.

**Describe alternatives you've considered**
Parallels works mostly, but the framerate loss is noticeable. PlayCover is a suitable compromise.

**Comment by PEACEBOI712** [comment]
is  it HSR available for m1 Mac book air

**Comment by Menelkir** [comment]
Can we have a proper update for HSR and HI3 as well? It seems the banwave is gone, the warning flag was even removed from "jade".

**Comment by Menelkir** [comment]
It's getting updated accordingly (as long you can build yourself), the launcher isn't available just yet because is quite of unstable.
