### ISSUE TITLE
how to fullscreen (not windowed borderless

### ISSUE THREAD

**Issue by Cyclohexia** [yaagl/yet-another-anime-game-launcher#156]
is there a config option for launching genshin on fullscreen and not windowed borderless? it behaves really weirdly in w.borderless
Thanks!

**Comment by RishitM** [comment]
u actually cant
u can do one thing: go to settings in genshin and in video do the resolution to fulscreen
thats the max possible

**Comment by MrPieGaming** [comment]
I usually press "CMD + return" to make the app go into fullscreen (or at least take up the entire screen)

**Comment by Menelkir** [comment]
Is this solved?

**Comment by baseplate-admin** [comment]
> Is this solved?

I dont think so

**Comment by Menelkir** [comment]
Then what is missing? If it's a limitation of the game itself, there's nothing that can be done.

**Comment by baseplate-admin** [comment]
> Then what is missing? If it's a limitation of the game itself, there's nothing that can be done.

I think this is a limitation of unity and wine at this point. Theres a lot of open [troubleshooting information](https://github.com/an-anime-team/an-anime-game-launcher/wiki/Troubleshoot-Game) of `an-anime-game-launcher`

**Comment by Menelkir** [comment]
> > Then what is missing? If it's a limitation of the game itself, there's nothing that can be done.
> 
> I think this is a limitation of unity and wine at this point. Theres a lot of open [troubleshooting information](https://github.com/an-anime-team/an-anime-game-launcher/wiki/Troubleshoot-Game) of `an-anime-game-launcher`

I do use aagl as well and I'm aware but wine for macOS is a totally different animal. Most of fixes there will not work for us.

**Comment by Sipperz** [comment]
CLosing issue because no further response was given on the issue, feel free to re-open the issue if needed.
