### ISSUE TITLE
Nothing appears on the captcha screen

### ISSUE THREAD

**Issue by NOOBNUBY** [yaagl/yet-another-anime-game-launcher#161]
<img width="359" alt="image" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/93894025/dc1f4683-9aff-4e82-8568-f5849a78f914">
 
how to fix this?

**Comment by Menelkir** [comment]
Do you still have this issue?
Disable AC and enable it back, usually fixes.
Reopen if you still have this issue.
