### ISSUE TITLE
Stuck on white screen

### ISSUE THREAD

**Issue by manymaxxx** [yaagl/yet-another-anime-game-launcher#162]
After i click "start game" on launcher, i always have same issues. This white screen.
<img width="2560" alt="Знімок екрана 2023-08-16 о 14 33 44" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142410905/37831708-6eec-4152-92c2-4abb826d878b">

**Comment by umtalj0ta** [comment]
Same issue here

**Comment by Menelkir** [comment]
Do you still have this issue?

**Comment by umtalj0ta** [comment]
Solved for me. Thanks :)
