### ISSUE TITLE
Captcha Box

### ISSUE THREAD

**Issue by Blazee00** [yaagl/yet-another-anime-game-launcher#163]
I am having a problem where there is a white box what I think is supposed to be a Captcha Box. There is nothing there.

**Comment by JsCoderCole** [comment]
The solutions I use when I am unable to disable AC Patch:

1. Change DNS to google's (8.8.8.8 / 8.8.4.4)
2. Enable a VPN
3. Restart device and try again

If I'm really desperate:

I'd re-download the game before I enable my VPN to try again.

**Comment by yikl1004** [comment]
I am experiencing the same symptoms.
No matter how long I wait, the captcha never comes.

**Comment by yikl1004** [comment]
> I am experiencing the same symptoms.
> No matter how long I wait, the captcha never comes.

<img width="1097" alt="스크린샷 2023-08-24 19 25 59" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/7499652/9587f1e1-a6be-433a-bc5b-3fcab89ea1bd">
<img width="1097" alt="스크린샷 2023-08-24 19 26 11" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/7499652/4464ea38-6b75-46f2-b2dd-38f45b676d5c">
<img width="1097" alt="스크린샷 2023-08-24 19 26 22" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/7499652/5810cebe-6945-4dde-bb64-4933632cb2b9">

I'm still not getting captcha.

**Comment by randomarchuser** [comment]
What worked for me was to change the wine option to "gptk". Apparently this wine version is designed for apple computers which might explain why it worked better.

**Comment by eliu9395** [comment]
@randomarchuser How do you use gptk? I installed it but it doesn't show up.

**Comment by DonCruze** [comment]
> What worked for me was to change the wine option to "gptk". Apparently this wine version is designed for apple computers which might explain why it worked better.

thank you really work

**Comment by Daho0980** [comment]
> What worked for me was to change the wine option to "gptk". Apparently this wine version is designed for apple computers which might explain why it worked better.

omg it really works

thank you so much :)
