### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by frowing37** [yaagl/yet-another-anime-game-launcher#165]
When I start to play a quest it runs for a few minutes but after that shows a black screen. How can I fix that ?

macOS : 13.4.1
Device : MacbookAir 13inch 2022
CPU : Apple M2
RAM : 16GB

**Comment by frowing37** [comment]
After I get bug, I close game and re-open but game is keep going on  last quest. So I can't play

**Comment by Menelkir** [comment]
The game now needs Sonoma 14.4 or newer. I know this issue is old, but it's just FYI.
If this issue persists, feel free to reopen this issue.
