### ISSUE TITLE
Yaagl OS quit unexpectedly 

### ISSUE THREAD

**Issue by Kamitsuuu** [yaagl/yet-another-anime-game-launcher#166]
when I try to open Yaagl OS on mac in says “Yaagl OS quit unexpectedly” i tried to restart my mac and reinstall the application but nothing worked

![image](https://github.com/3Shain/yet-another-anime-game-launcher/assets/142459023/fa91b6f9-7c61-4adc-9f94-e58a2eb37c15)

**System Information (please complete the following information):**
 - macOS: [High Sierra Version 10.13.6]
 - Device: [Macbook Air 13 inch,2017]

please i hope you can help me fix this i really want to use this application to play genshin i would love y’all please!! 🙏🙏

**Comment by Kamitsuuu** [comment]
hi

**Comment by h12345624** [comment]
Having the same problem
<img width="503" alt="Screen Shot 2023-10-25 at 10 50 07 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/149033231/22590a7e-e315-4881-b817-63c714020926">

**Comment by Menelkir** [comment]
I'm not really sure if it's possible to run genshin on this machine. Probably too weak.
