### ISSUE TITLE
Failed to download resources or network error. Code:-9006

### ISSUE THREAD

**Issue by itsmesamaviles** [yaagl/yet-another-anime-game-launcher#169]
Anybody getting this error after updating to the latest build? This never happened before 4.0.

**Comment by JsCoderCole** [comment]
1. Disable any VPNs while downloading
2. Make sure you're connected to a stable internet

If you're super desperate: 
1. Delete YAAGL and the resource files: /Users/username/Library/Application Support/Yaagl OS
2. re-download the latest [release](https://github.com/3Shain/yet-another-anime-game-launcher/releases/tag/0.1.2) 

If nothing else works: 
Watch some anime and wait for other responses

**Comment by Q3B4** [comment]
Same problem here, cannot download content after logging in. I tried turning on and off VPN and made sure internet was stable, but the problem still existed.

<img width="208" alt="Screenshot 2023-08-21 at 08 33 14" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142759551/0242bb93-14c3-47d7-bd26-f7a2553c572a">

**Comment by SpookyChocolate** [comment]
same problem

**Comment by JunxiBao** [comment]
我的进度条一直在滚动,但是没有任何进展

**Comment by Menelkir** [comment]
Do you still have this issue?
