### ISSUE TITLE
Failed to initialize player

### ISSUE THREAD

**Issue by Speedster0** [yaagl/yet-another-anime-game-launcher#173]
I have tried multiple times following youtube guides, however I still end up with the same error. I even tried multiple combinations of the settings, toggling them on and off.
![Screen Shot 2023-08-23 at 17 23 08](https://github.com/3Shain/yet-another-anime-game-launcher/assets/142982832/ea67aee2-a6cc-4ab8-a47a-71ae11754733)

**Comment by Menelkir** [comment]
You don't have to follow a youtube guide.
What is your machine?

**Comment by Menelkir** [comment]
No replies so I will close this issue for now, feel free to reopen if the problem persists.
