### ISSUE TITLE
what to do now ?

### ISSUE THREAD

**Issue by akitort** [yaagl/yet-another-anime-game-launcher#174]
<img width="1440" alt="Screenshot 2023-08-23 at 3 02 21 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142984210/f5ef1e0e-0b67-4d6e-b1d6-189a5032dc00">
**Describe the bug**

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
 - CPU: [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
<img width="1440" alt="Screenshot 2023-08-23 at 3 02 21 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142984210/3e5da21e-b0b5-4414-bd96-297daee45eaf">

**Comment by JsCoderCole** [comment]
Open the launcher settings and opt to turn off "AC Patch" 
<img width="1057" alt="image" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142519673/1094370a-3620-4b2a-a99a-ee0eff137634">

**Comment by akitort** [comment]
ThanX Bro

**Comment by Garima1000** [comment]
> Open the launcher settings and opt to turn off "AC Patch"
> <img alt="image" width="1057" src="https://user-images.githubusercontent.com/142519673/262676468-1094370a-3620-4b2a-a99a-ee0eff137634.png">

but while verification it shows a white box

**Comment by JsCoderCole** [comment]
You should only select "Turn off AC patch" if you're already logged into Genshin Impact via the launcher. You'll have to wait for a new launcher update if you're not. In @akitort's case, he was already logged in so he doesn't have to worry about a white captcha box after selecting it.
