### ISSUE TITLE
The launcher currently doesn't support version 4.0.1 currently, please wait for further updates

### ISSUE THREAD

**Issue by Garima1000** [yaagl/yet-another-anime-game-launcher#175]
is it gonna update or do I need to download the whole launcher again?

**Comment by Crd5** [comment]
I think we should wait for new yaagl release

**Comment by Garima1000** [comment]
> I think we should wait for new yaagl release

do you have any idea till when will it come out?

**Comment by Jojokana** [comment]
i try bu that i cant log on

**Comment by buingocbao** [comment]
The Release 0.1.3 is out to fix that

> > I think we should wait for new yaagl release
> 
> do you have any idea till when will it come out?
