### ISSUE TITLE
I can't download the latest version

### ISSUE THREAD

**Issue by goesbyeu** [yaagl/yet-another-anime-game-launcher#178]
{"code":"NE_FS_FILRDER","message":"Unable to open file

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
<img width="1440" alt="Screenshot 2023-08-26 at 14 52 29" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142577939/ed2df5e1-7246-4f22-aa46-5526fcb8f5f0">

 - CPU: [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
Do you still have this issue?
