### ISSUE TITLE
Game is not launching/opening

### ISSUE THREAD

**Issue by Sunny1312** [yaagl/yet-another-anime-game-launcher#183]
**Describe the bug**
**stuck on reverting patches and after that it comes back to the launch page it is never loading the game?? please help**

**Screenshots**

<img width="1162" alt="yaagi1" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/91509890/88065e7b-2a7d-4798-ac6d-f71ee09426a1">
<img width="1162" alt="yaagi2" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/91509890/e722c8cf-6c7a-4b8b-b47c-bb61ef3d9ac3">
<img width="1160" alt="yaagi3" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/91509890/b5119f2b-2d6f-439c-89b1-3d175a00626b">
<img width="1159" alt="Untitled 4" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/91509890/61114888-8910-4d9c-a1f6-6f14261dde86">
<img width="1178" alt="asasasa" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/91509890/cf16e33a-e7d9-4525-a404-b6f15d533dbd">

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: [e.g. MacbookPro 16inch 2019 ]
 - CPU: [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
Do you still have this issue?
