### ISSUE TITLE
The launcher says that i need 146GB of free space to download the game even if I have almost 200GB free on my disk

### ISSUE THREAD

**Issue by MKSlegal** [yaagl/yet-another-anime-game-launcher#185]
I downloaded the launcher and it went ok, then when im trying to download the game it says that to do that i need 146gb of free space on my disk, I had like 150gb of free space, then I cleared some things up and I got 200gb of free space, but it continued to tell me that i need 146gb free on my disk, i tried everything that i knew that I could do, redownload the launcher, to turn off the mac ecc. Is this a bug?
<img width="1290" alt="Screenshot 2023-09-10 alle 13 37 40" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/144597714/2227cc9f-57ce-4b92-9529-5ad698a23742">
<img width="534" alt="Screenshot 2023-09-10 alle 13 38 13" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/144597714/8bf768dc-841f-46b0-9e62-b6c9c5f60492">

**Comment by cxwx** [comment]
知道文件下载在哪里吗？我没找到

**Comment by ihavelotsofissues** [comment]
same

**Comment by Menelkir** [comment]
Do you still have this issue?
