### ISSUE TITLE
Failed to initalize player error

### ISSUE THREAD

**Issue by shucheng215** [yaagl/yet-another-anime-game-launcher#186]
**Describe the bug**
Error message appears upon launch
**Screenshots**
![Screenshot 2023-09-09 at 6 57 17 PM](https://github.com/3Shain/yet-another-anime-game-launcher/assets/59895939/bac22e3d-5bf0-49c4-933e-b6c1bac033d4)

**System Information (please complete the following information):**
 - macOS: 13.6 [e.g. 13.1 Ventura]
 - Device:  Mid 2011 iMac 21.5 inch [e.g. MacbookPro 16inch 2019 ]
 - CPU: 2.5 GHz Quad-Core Intel Core i5 [e.g. Apple M1, Intel i7 9750H ]
 - Dedicated GPU (if any): AMD Radeon HD 6750M 512 MB [e.g.  AMD Radeon Pro 5300M ]
 - RAM: 16 GB [e.g. 16G ]

**Additional context**
Reinstalling the entire launcher was attempted, but doesn't work
**Logs (if any)**
> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
[neutralinojs copy.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/12570157/neutralinojs.copy.log)

**Comment by Menelkir** [comment]
You need Metal to run the game.
