### ISSUE TITLE
数据异常，请重新登录

### ISSUE THREAD

**Issue by jxy599** [yaagl/yet-another-anime-game-launcher#188]
**Describe the bug**
提示“数据异常，请重新登录”

**Screenshots**
<img width="1728" alt="截屏2023-09-20 00 33 23" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/49704953/385d2e31-d939-4c32-b013-dfcf896a7693">**System Information (please complete the following information):**
 - macOS: [macOS14 Sonoma]
 - Device: [ MacbookPro 16inch 2023 ]
 - CPU: [Apple M2 MAX]
 - Dedicated GPU (if any): []
 - RAM: [64G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by ruxtain** [comment]
I ran into the same problem. 
<img width="241" alt="image" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/7043478/8c268579-4773-4074-b14f-9f5085be9510">

**Comment by Stapxs** [comment]
#3

**Comment by Menelkir** [comment]
Do you still have this issue?
