### ISSUE TITLE
allocating files

### ISSUE THREAD

**Issue by BentoMic** [yaagl/yet-another-anime-game-launcher#196]
even if i have enough space, even if i reset my mac and deleted and downloaded the latest version for yaagl os, i keep getting stuck on "allocating files" when i try to update 4.1

 - macOS: [12.5 Montery]
 - Device: [e.g. MacbookAir 13inch 20120ro 5300M ]
 - RAM: [8 G]

**Comment by Alxnzzz** [comment]
I have the same problem as well. Did you manage to get it to work?

**Comment by BentoMic** [comment]
nope. i swear i've had this issue in the past but i somehow got it to work again, until the next update came round. have you seen closed issues with the same problem?

**Comment by Alxnzzz** [comment]
No, I looked through the closed issues but could not find one that had the same problem as this one.

**Comment by Menelkir** [comment]
Do you still have this issue?
