### ISSUE TITLE
Hi is there any fix for this its asking for too much storage version 0.1.5

### ISSUE THREAD

**Issue by sosring** [yaagl/yet-another-anime-game-launcher#211]
<img width="538" alt="Screenshot 2023-11-19 at 5 42 43 AM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/108966935/3285762f-201f-4384-a684-dbc081593c0a">

**Comment by Menelkir** [comment]
Isn't asking for "too much storage". The game is almost 90G (and it's keep growing), it needs the space to download the zips of the entire game and then more space to unzip the downloaded one. It will eventually delete the zips after installed, but there's nothing that can be done, the game is huge.

**Comment by xenturix** [comment]
> Isn't asking for "too much storage". The game is almost 90G (and it's keep growing), it needs the space to download the zips of the entire game and then more space to unzip the downloaded one. It will eventually delete the zips after installed, but there's nothing that can be done, the game is huge.

on windows it only asks for about 170gb for installation unzipping 
![Screenshot from 2024-03-26 17-23-43](https://github.com/yaagl/yet-another-anime-game-launcher/assets/165029330/3d560ea1-69ec-4a1b-a530-be5ed87394e6)

and it does not end here i already have about 10gb more space than it needs yet it says that im short on space 
![Screenshot from 2024-03-26 17-23-53](https://github.com/yaagl/yet-another-anime-game-launcher/assets/165029330/aab733d4-52c0-410d-bad1-2c7ed8bc3a58)

**Comment by Menelkir** [comment]
> > Isn't asking for "too much storage". The game is almost 90G (and it's keep growing), it needs the space to download the zips of the entire game and then more space to unzip the downloaded one. It will eventually delete the zips after installed, but there's nothing that can be done, the game is huge.
> 
> on windows it only asks for about 170gb for installation unzipping ![Screenshot from 2024-03-26 17-23-43](https://private-user-images.githubusercontent.com/165029330/316859788-3d560ea1-69ec-4a1b-a530-be5ed87394e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjUyMzIsIm5iZiI6MTcxMTQ2NDkzMiwicGF0aCI6Ii8xNjUwMjkzMzAvMzE2ODU5Nzg4LTNkNTYwZWExLTY5ZWMtNGExYi1hNTMwLWJlNWVkODczOTRlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzUxNjIxM2NlZjE2ZTRjYTViMjc1MDU2ZmM3NGQ4Y2M1ZDE3OGIxZTFjZDAwYjlkNGRmY2NkNTU5ZDExMzU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UURSvU6fT2pFscXKM3lSnbRAZR0QBD_u3Oo6daMmv_Q)
> 
> and it does not end here i already have about 10gb more space than it needs yet it says that im short on space ![Screenshot from 2024-03-26 17-23-53](https://private-user-images.githubusercontent.com/165029330/316860195-aab733d4-52c0-410d-bad1-2c7ed8bc3a58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjUyMzIsIm5iZiI6MTcxMTQ2NDkzMiwicGF0aCI6Ii8xNjUwMjkzMzAvMzE2ODYwMTk1LWFhYjczM2Q0LTUyYzAtNDEwZC1iYWQxLTJjN2VkOGJjM2E1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxNDU1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjUzNGNiNjNkZTgzMGE3YWJmY2U3MWI5MmQ2YzczZjFlY2U0OGZiYWJlYTEyN2E3YjhmYjhiMjZjZDFhZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pAvekJZOLchZVFjLTd_1fpDOdnbUN6CQZ2MWPWtnUcU)

Different filesystem, different OS, probably even a different method. I never checked how windows does but isn't comparable in any way. 
Also, check if you have time machine copies, they don't show towards the free space.
