### ISSUE TITLE
storage

### ISSUE THREAD

**Issue by ihavelotsofissues** [yaagl/yet-another-anime-game-launcher#212]
**Describe the bug**
It says that I don't have enough free space on my disk but I have enough free space.

<img width="1278" alt="Screen Shot 2023-11-19 at 2 29 15 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/151419264/c0b7bf7d-ec54-4f09-8958-dd10a4063151">

**System Information (please complete the following information):**
 - macOS: monterey
 - Device: MacBook Air 13.3inch
 - CPU: apple M1
 - Dedicated GPU (if any): I don't know
 - RAM: I don't know

**Additional context**
does anyone know how to fix this problem?

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by s4nflower** [comment]
you need like 2x storage than what the game says it needs

**Comment by reaji** [comment]
Do you have TimeMachine? I had the same issue but turned out it's my TimeMachine issue.

**Comment by Menelkir** [comment]
Since the author didn't responded, I believe this can be assumed as solved.
