### ISSUE TITLE
Can't type my password in

### ISSUE THREAD

**Issue by yahayaha72** [yaagl/yet-another-anime-game-launcher#215]
can't seem to type anything in the password section when trying to log in to my hyv account, help!

**Comment by VensyMeow** [comment]
I have the same issue! Bump!

**Comment by JsCoderCole** [comment]
Actually... I've had the same thing too! I found out that I can type my password, but it won't display in the box. So **try typing in your password even if the letters don't show!**

**Comment by davecarrijo** [comment]
You can just click on it and write you password, it's  glitch, it just don't show, but it's there. 
If you need really to look at it, open notepad write it copy it and past it on the launcher.
