### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by UnknownPug** [yaagl/yet-another-anime-game-launcher#219]
Hello!

I am trying to download the game via [Yaagl.OS.app.tar.gz version 0.1.5](https://github.com/3Shain/yet-another-anime-game-launcher/releases/tag/0.1.5) and after unzipping a file it's asking for 10GB of space. After downloading the 10GB it is starting again as a loop. I would like to ask if there is any solution to this bug? Thank you in advance.

macOS: Sonoma
Device: MacBook Pro 13 inch 2020
CPU: Apple M1 Chip

**Comment by Sillygoat36** [comment]
it does that 7 times, then one of 4.5 Gb and then it decompresses files, it does the full 74.5 gigs just in blocks

**Comment by UnknownPug** [comment]
> it does that 7 times, then one of 4.5 Gb and then it decompresses files, it does the full 74.5 gigs just in blocks

I see now. I will try that, thanks! 😃
