### ISSUE TITLE
 stuck on "configuring environment"

### ISSUE THREAD

**Issue by chenpinetree** [yaagl/yet-another-anime-game-launcher#22]
macos ventura 13.2.1  M1
32 GB memory, 32 GPU, 10 CPU
Yaagl 0.0.34
After opening the app and downloading the configuration file, it has been stuck on "configuring environment".
<img width="1316" alt="iShot_2023-03-30_22 53 21" src="https://user-images.githubusercontent.com/43738241/228876893-ec6a4f76-039c-484b-9884-e7c7c4f26cff.png">

**Comment by 3Shain** [comment]
See if restarting launcher can help. Also provide me the contents in `~/Library/Application Support/Yaagl/neutralinojs.log` (or `Yaagl OS`)

**Comment by chenpinetree** [comment]
I have tried restarting the app.


`INFO 2023-03-30 21:02:37,634 Checking github endpoints api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:02:38,813 echo $PPID api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:02:38,895 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/chen/Library/Application\ Support/Yaagl/aria2.session --save-session /Users/chen/Library/Application\ Support/Yaagl/aria2.session --pause true --stop-with-process 49380 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:02:38,909 49406 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:02:38,909 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/chen/Library/Application\ Support/Yaagl/aria2.session --save-session /Users/chen/Library/Application\ Support/Yaagl/aria2.session --pause true --stop-with-process 49380 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:02:39,416 Launched aria2 version 1.35.0 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:02:39,773 cat /Applications/CrossOver.app/Contents/Info.plist | grep -A1 CFBundleVersion | grep string | sed s/\<\[^\>\]\*\>//g api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:02:39,907 rm -rf /Users/chen/Library/Application\ Support/Yaagl/wineprefix api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:04:10,937 rm -rf /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:04:11,064 mkdir -p /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:04:11,134 tar -zxvf /Users/chen/Library/Application\ Support/Yaagl/wine.tar.gz -C /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:04:12,540 osascript -e do\ shell\ script\ \"xattr\ -r\ -d\ com.apple.quarantine\ /Users/chen/Library/Application\\\\\ Support/Yaagl/wine\"\ with\ administrator\ privileges api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:04:15,073 WINEPREFIX=/Users/chen/Library/Application\ Support/Yaagl/wineprefix /Users/chen/Library/Application\ Support/Yaagl/wine/bin/wine64 wineboot -u api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:48,949 Checking github endpoints api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:50,206 echo $PPID api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:50,280 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/chen/Library/Application\ Support/Yaagl/aria2.session --save-session /Users/chen/Library/Application\ Support/Yaagl/aria2.session --pause true --stop-with-process 50012 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:50,298 50025 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:50,299 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/chen/Library/Application\ Support/Yaagl/aria2.session --save-session /Users/chen/Library/Application\ Support/Yaagl/aria2.session --pause true --stop-with-process 50012 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:50,806 Launched aria2 version 1.35.0 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:51,154 cat /Applications/CrossOver.app/Contents/Info.plist | grep -A1 CFBundleVersion | grep string | sed s/\<\[^\>\]\*\>//g api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:34:51,278 rm -rf /Users/chen/Library/Application\ Support/Yaagl/wineprefix api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:35:08,541 rm -rf /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:35:08,700 mkdir -p /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:35:08,778 tar -zxvf /Users/chen/Library/Application\ Support/Yaagl/wine.tar.gz -C /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:35:10,227 osascript -e do\ shell\ script\ \"xattr\ -r\ -d\ com.apple.quarantine\ /Users/chen/Library/Application\\\\\ Support/Yaagl/wine\"\ with\ administrator\ privileges api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 21:35:12,910 WINEPREFIX=/Users/chen/Library/Application\ Support/Yaagl/wineprefix /Users/chen/Library/Application\ Support/Yaagl/wine/bin/wine64 wineboot -u api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:54,174 Checking github endpoints api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:55,393 echo $PPID api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:55,470 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/chen/Library/Application\ Support/Yaagl/aria2.session --save-session /Users/chen/Library/Application\ Support/Yaagl/aria2.session --pause true --stop-with-process 50903 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:55,485 50922 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:55,486 ./sidecar/aria2/aria2c -d / --no-conf --enable-rpc --rpc-listen-port=6868 --rpc-listen-all=true --rpc-allow-origin-all --input-file /Users/chen/Library/Application\ Support/Yaagl/aria2.session --save-session /Users/chen/Library/Application\ Support/Yaagl/aria2.session --pause true --stop-with-process 50903 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:55,992 Launched aria2 version 1.35.0 api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:56,363 cat /Applications/CrossOver.app/Contents/Info.plist | grep -A1 CFBundleVersion | grep string | sed s/\<\[^\>\]\*\>//g api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:33:56,487 rm -rf /Users/chen/Library/Application\ Support/Yaagl/wineprefix api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:34:15,528 rm -rf /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:34:15,702 mkdir -p /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:34:15,793 tar -zxvf /Users/chen/Library/Application\ Support/Yaagl/wine.tar.gz -C /Users/chen/Library/Application\ Support/Yaagl/wine api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:34:17,423 osascript -e do\ shell\ script\ \"xattr\ -r\ -d\ com.apple.quarantine\ /Users/chen/Library/Application\\\\\ Support/Yaagl/wine\"\ with\ administrator\ privileges api/debug/debug.cpp:17 chen@unknown-host
INFO 2023-03-30 22:34:19,955 WINEPREFIX=/Users/chen/Library/Application\ Support/Yaagl/wineprefix /Users/chen/Library/Application\ Support/Yaagl/wine/bin/wine64 wineboot -u api/debug/debug.cpp:17 chen@unknown-host
`

**Comment by chenpinetree** [comment]
> See if restarting launcher can help. Also provide me the contents in `~/Library/Application Support/Yaagl/neutralinojs.log` (or `Yaagl OS`)

I have tried restarting the app.
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11117096/neutralinojs.log)

**Comment by chenpinetree** [comment]
> See if restarting launcher can help. Also provide me the contents in `~/Library/Application Support/Yaagl/neutralinojs.log` (or `Yaagl OS`)

i have uploaded neutralinojs.log above

**Comment by 3Shain** [comment]
Seems wine failed to create prefix and to be honest I can't solve it on my side.

`WINEPREFIX=/Users/chen/Library/Application\ Support/Yaagl/wineprefix /Users/chen/Library/Application\ Support/Yaagl/wine/bin/wine64 wineboot -u` input these in terminal and let me know what it outputs.

**Comment by AdityaPande128** [comment]
> Seems wine failed to create prefix and to be honest I can't solve it on my side.
> 
> `WINEPREFIX=/Users/chen/Library/Application\ Support/Yaagl/wineprefix /Users/chen/Library/Application\ Support/Yaagl/wine/bin/wine64 wineboot -u` input these in terminal and let me know what it outputs.

I'm facing this issue too. It happened when I tried to change the wine version from gi-wine-1.2 to gi-wine-1.0
It downloaded the packages but its been stuck at the same screen for an hour now
Whenever I restart, it defaults to restarting again and trying to download it again
Is there a way that I can change the wine version back through the config file?

**Comment by zeshu9** [comment]
@AdityaPande128 

Try going to `~/Library/Application Support/Yaagl OS`. Delete everything in there and launch the game again.

**Comment by SamerEladad** [comment]
I'm facing the same issue, this only happened after I tried to change the wine version from gi-wine-1.2 to gi-wine-1.0 because the game froze occasionally. is there a way to change the wine version without starting the app?

**Comment by SamerEladad** [comment]
update: I switched off my wifi while the launcher was stuck on "configuring environment". these seemed to launch the app and I was able to switch the wine version back to gi-wine-1.2

**Comment by Menelkir** [comment]
I suppose this is fixed? I will close for now.
