### ISSUE TITLE
Wont let me open

### ISSUE THREAD

**Issue by CycloneDraco** [yaagl/yet-another-anime-game-launcher#220]
**Describe the bug**
Gives an error whenever i open game

Error: Command return non-zero code
WINEESYNC=1 WINEDEBUG=fixme-all,err-unwind,+timestamp WINEPREFIX=/Users/james/Library/Application\ Support/Yaagl\ OS/wineprefix GIWINEPCNAME=DESKTOP-EC5OEYY GIWINECPUNAME=Intel\(R\)\ Core\(TM\)\ i7-8569U\ CPU\ @\ 2.80GHz GIWINECPUFREQ=2800 GIWINECPUVID=GenuineIntel GIWINESYSMANU=OEM GIWINESYSPRODNAME=Generic\ x86-64 GIWINESYSFAML=B350 /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/CrossOver-Hosted\ Application/wineloader64 wineboot -u &> /dev/null
StdOut:

StdErr:

I have tried opening the YAAGL chinese version and that works. 

**System Information (please complete the following information):**
 - macOS: [14.2 Sonoma]
 - Device: [Macbook Air M2]
 - CPU: [Apple M2 ]

 - RAM: [16gb ]

\

**Comment by Zqanx** [comment]
Do you still have this issue?
