### ISSUE TITLE
can not reinstall the launcher

### ISSUE THREAD

**Issue by dsihdekuhfhfgf** [yaagl/yet-another-anime-game-launcher#231]
I had problems w opening the launcher and wanted to reinstalll it. I deleted all the files and it still shows like I do have them and that is why I can not reinstall the game. how can I get rid of this issue n download genshin again?

**Comment by eager20** [comment]
genshin 4.3 opened at 2023.12.20 .
yaagle 0.1.5 version support in genshin  4.2.

I am also waiting for yaagle to run version 3.4. ㅠ_ㅠ
