### ISSUE TITLE
Failed to initialize player

### ISSUE THREAD

**Issue by CytrusCitrus** [yaagl/yet-another-anime-game-launcher#235]
**Describe the bug**
When I run the game an error comes up telling me that it has "Failed to initialize graphics"

**Screenshots**
<img width="208" alt="Screen Shot 2023-12-23 at 4 59 38 PM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/154711550/c552f456-c95a-4a15-a27c-b83ffca54ead">

**System Information (please complete the following information):**
 - macOS: 11.7.3 BigSur
 - Device: MacBook Pro (Retina, 15-inch, Mid 2014)
 - CPU: 2.8 GHz Quad-Core Intel Core i7
 - Dedicated GPU (if any): N/A
 - RAM: 16G

**Additional context**
After I close the error window the launcher stops loading. 

**Logs (if any)**
N/A

**Comment by NiMeItachi** [comment]
When is update for amd chip?

**Comment by Menelkir** [comment]
> **Describe the bug** When I run the game an error comes up telling me that it has "Failed to initialize graphics"
> 
> **Screenshots** <img alt="Screen Shot 2023-12-23 at 4 59 38 PM" width="208" src="https://private-user-images.githubusercontent.com/154711550/292649266-c552f456-c95a-4a15-a27c-b83ffca54ead.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjU0NjUsIm5iZiI6MTcxODkyNTE2NSwicGF0aCI6Ii8xNTQ3MTE1NTAvMjkyNjQ5MjY2LWM1NTJmNDU2LWM5NWEtNGExNS1hMjdjLWI4M2ZmY2E1NGVhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQyMzEyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjAzNDdjYmZjZjRmY2E3NmU4OGQ1MTVjMjQ2M2RkMDA0OWQ3ODA4YzZjZmI5OWM0NjhmN2Y5ZDM3YzhkN2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XQaPbldw3W92uTTKwJFJw06ANBWWfLnkzSc9piiWOF8">
> 
> **System Information (please complete the following information):**
> 
>     * macOS: 11.7.3 BigSur
> 
>     * Device: MacBook Pro (Retina, 15-inch, Mid 2014)
> 
>     * CPU: 2.8 GHz Quad-Core Intel Core i7
> 
>     * Dedicated GPU (if any): N/A
> 
>     * RAM: 16G
> 
> 
> **Additional context** After I close the error window the launcher stops loading.
> 
> **Logs (if any)** N/A

Probably not enough VRAM (afaik those GPUs uses 1.5G of shared ram as VRAM).


> When is update for amd chip?

What?
