### ISSUE TITLE
reverting patch issue

### ISSUE THREAD

**Issue by akitort** [yaagl/yet-another-anime-game-launcher#241]
when i open game it reverts patches and doesnt open
i have a mac air m1 
macos sonoma 14.1.2

**Comment by eager20** [comment]
Don't Work for ARM CPU. ㅠ_ㅠ
( Your mac use ARM CPU )

I am waiting for patch to ARM Support.....

**Comment by akitort** [comment]
is it available now arm support?

**Comment by Ravenaige** [comment]
yes, I download that release but same issue

doesnt working :/

**Comment by ahmadInternaldo** [comment]
> when i open game it reverts patches and doesnt open i have a mac air m1 macos sonoma 14.1.2

i get the same error before,
but after update to sonoma 14.4 (beta version), it can be launch the game
hope will help you

**Comment by Menelkir** [comment]
It works now on 14.4.
