### ISSUE TITLE
Game is not launching for Macbook pro M1 pro

### ISSUE THREAD

**Issue by priyatham19** [yaagl/yet-another-anime-game-launcher#243]
**Describe the bug**
After starting the launcher the game is not getting loaded. It is stuck on the launcher screen and not moving forward. I saw the other comments that the latest version is deployed for only Intel macs but not for Apple silicon. Is anyone working on this to fix it for M1 macs?

**System Information (please complete the following information):**
 - macOS: Sonoma 14.2.1
 - Device: Macbook Pro 14 inch 2021
 - CPU: M1 Pro
 - Dedicated GPU (if any): Apple GPU
 - RAM: 16GB

**Comment by Menelkir** [comment]
It doesn't work on arm yet, it's written on the release page.
