### ISSUE TITLE
The app says I don't have enough space on my disk but I do

### ISSUE THREAD

**Issue by gretaimpact** [yaagl/yet-another-anime-game-launcher#248]
- macOS: 14.2.1 (23C71)
 - Device: MacBook Pro 13-inch, M1, 2020
 - CPU: Apple M1
 - Dedicated GPU (if any): Don't know
 - RAM: 8GB
![Screenshot 2024-01-17 at 01 51 06](https://github.com/3Shain/yet-another-anime-game-launcher/assets/156885835/aaedc670-3380-4bb0-9c82-e493546f45f2)

**Comment by witheredlilies** [comment]
I think it could be its not available on Sonoma 14.2.1 yet

**Comment by Menelkir** [comment]
Worth noting the game will not run even if you manage to install, since there's an issue on arm (it's written on release page).
