### ISSUE TITLE
Game often crashes on dialogues or when using bursts

### ISSUE THREAD

**Issue by N1klot** [yaagl/yet-another-anime-game-launcher#253]
When you enter the dialogue, it can crash at any point during it. It is often on the exact same part. Also when using bursts, sometimes it works normally.

 - macOS Sonoma 14.4
 - Device: MacBook Pro 14" M2 Pro
 - CPU: Apple M2 Pro
 - RAM: 16GB

[game_1706832602301.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/14132461/game_1706832602301.log)

**Comment by xingruic** [comment]
i'm having the same issue on the same mac model. some bursts work fine and others crash mid-animation. all the ones that have crashed are 5 star bursts tho, 4 star bursts works fine. also it crashed during one of the lantern rite quest dialogues.

**Comment by N1klot** [comment]
Yes, exactly. I meant 5 star animated bursts. Tried lowering graphics to a minimum possible, did not help.

**Comment by Somwow** [comment]
This also happens to a lot. Especially when I am in the middle of dialogues! 
I am running on a M1 macbook pro 13 inch.

**Comment by Evangelicabyss** [comment]
This is a problem I've been having again recently. More specifically, crashing during dialogue. Running an M2 Macbook Pro 14-inch.

**Comment by Menelkir** [comment]
It's a known issue some systems crashes on animations and cinematics. For people with 16Gb of ram and more, I would suggest trying crossover.

**Comment by Menelkir** [comment]
Do you still have this issue?

**Comment by N1klot** [comment]
No, ever since crossover 24 and changing wine 1.2 to crossover in Yaagl launcher it runs perfect.
