### ISSUE TITLE
[feat request] Let network connection of the Launcher go through system proxy

### ISSUE THREAD

**Issue by zhusun890** [yaagl/yet-another-anime-game-launcher#256]
**Is your feature request related to a problem? Please describe.**
When the launcher downloads necessary configuration files, it seems to be downloading from abroad CDN servers, and the network speed rate was slow (in Jinan, Shandong, China, it's likely 3.5KB/s~30KB/S)

**Describe the solution you'd like**
Let network connection of the Launcher go through system proxy

**Describe alternatives you've considered**
Add a new CDN node that's nearer to China Mainland, and switch to the nearest CDN node automatically when the launcher is going to download some configurations.

**Additional context**
-

**Comment by 3Shain** [comment]
> Add a new CDN node that's nearer to China Mainland, and switch to the nearest CDN node automatically when the launcher is going to download some configurations.

哥们没有银子这是主要问题
