### ISSUE TITLE
Custom environment variable support

### ISSUE THREAD

**Issue by k-kozika** [yaagl/yet-another-anime-game-launcher#268]
I want to play the game in a language that is not used by the OS. I know that I can change a language for wine using the LANG environment variable. So by adding custom environment variable settings we'll be able to play the game in other languages

**Is your feature request related to a problem? Please describe.**
It's not related to the problem

**Describe the solution you'd like**
Add environment variables received from the user [here](https://github.com/3Shain/yet-another-anime-game-launcher/blob/624fa5908488fb166f90fb09220877e632011501/src/wine/wine.ts#L79)

**Describe alternatives you've considered**
Use "Launcher Language" as the game language or add a "Game Language" setting to automatically set the environment variable
But I didn't want to do so because the customization offered to users was low.

**Comment by Menelkir** [comment]
You don't have to change the environment language, you can change the language in-game using the settings. For example, I use english for text and japanese for audio.

**Comment by k-kozika** [comment]
> You don't have to change the environment language, you can change the language in-game using the settings. For example, I use english for text and japanese for audio.

Thank you! I didn't know that.
