### ISSUE TITLE
The game won't launch after I log in

### ISSUE THREAD

**Issue by Harbibus** [yaagl/yet-another-anime-game-launcher#269]
I am using the latest release as of writing this (0.1.8) and this issue has always occurred in the previous release as well (0.1.7)
I have tried closing and opening yaagl, verifying the file integrity, uninstalling the game files and launcher and re installing the latest release again off GitHub, but nothing seems to work and I have always had this problem from the start.
"Data error, please fully uninstall the game and download the latest game files from the official website again"

![Image 24-02-2024 at 1 47 PM](https://github.com/3Shain/yet-another-anime-game-launcher/assets/117966477/27460f7b-057e-4d79-8322-c98a9698dcf4)

   macOS Sonoma Beta 14.4
   Device:  iMac 24-inch 2020
   Chip: Apple M1
   Memory: 8 GB

[game_1708737830153.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/14391276/game_1708737830153.log)

**Comment by k-kozika** [comment]
I solved this problem by switching the patch applied from the game section in the launcher settings. Please try adjusting it properly.

**Comment by greatoe** [comment]
> I solved this problem by switching the patch applied from the game section in the launcher settings. Please try adjusting it properly.

Would you please describe more detailed?  I tried every option combination in the Game section in the launcher Settings but the issue remains.

macOS Sonama Beta 14.4
MacBook Pro 16" 2021
Apple M1 Max
Memory: 64Gb

**Comment by k-kozika** [comment]
Hmm, I had the same problem...
1. First, I turned on `Workaround #3`
  but the problem remains
2. Next, turn on `Turn off the AC patch`
  I was able to start it.

But if you've tried every option, your problem may be different from this one. The problem varies depending on the environment, so I don't know of any better solution.

**Comment by Harbibus** [comment]
> I solved this problem by switching the patch applied from the game section in the launcher settings. Please try adjusting it properly.

This worked for me thank you

**Comment by greatoe** [comment]
> Hmm, I had the same problem...
> 
> 1. First, I turned on `Workaround #3`
>    but the problem remains
> 2. Next, turn on `Turn off the AC patch`
>    I was able to start it.
> 
> But if you've tried every option, your problem may be different from this one. The problem varies depending on the environment, so I don't know of any better solution.

Thank you.  I tried again, still no luck.

**Comment by relrelway** [comment]
> Hmm, I had the same problem...
> 
> 1. First, I turned on `Workaround #3`
>    but the problem remains
> 2. Next, turn on `Turn off the AC patch`
>    I was able to start it.
> 
> But if you've tried every option, your problem may be different from this one. The problem varies depending on the environment, so I don't know of any better solution.

Tried turning on both options and worked flawlessly
