### ISSUE TITLE
i can't open yaagl 0.1.8 even though i have updated sonoma 14.4 beta

### ISSUE THREAD

**Issue by thanhtum274** [yaagl/yet-another-anime-game-launcher#271]
**Describe the bug**
I open yaagl 1.0.8 launcher and nothing appears 

**Screenshots**
<img width="315" alt="Ảnh màn hình 2024-02-25 lúc 16 51 55" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/161203708/03a3f526-64b9-44c7-a98f-2d616d5a19ec">

**System Information (please complete the following information):
 - macOS: [14.4 SONOMA]
 - Device: [MacbookAir 2020 ]
 - CPU: [Apple M1 ]

**Comment by Menelkir** [comment]
Needs more information, the screenshot doesn't help at all.
