### ISSUE TITLE
At least 171.6GiB (184.3GB) of free space is required on your disk. Error.

### ISSUE THREAD

**Issue by FireNuke** [yaagl/yet-another-anime-game-launcher#272]
**Describe the bug**
It keeps saying the same thing over and over that I don't have space. Even tho I do and I don't have any Time Machine backups. Also Genshin isn't 184gb wth it's max 60gb on windows no more.

**Screenshots**

![Screenshot 2024-02-25 at 16 43 00](https://github.com/3Shain/yet-another-anime-game-launcher/assets/56696555/c8844a2f-29f9-4633-8e1f-6eb8ca566d4f)

**System Information (please complete the following information):**
 - macOS: [Latest Sonoma 14.3.1]
 - Device: [Mac mini m1 2020]
 - CPU: [Apple M1]
 - Dedicated GPU (Integrated M1]
 - RAM: [8GB ]

**Additional context**
Don't know why it don't work tbh. 

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
It's 85gb total atm, and you need twice the space because it needs do download the zip files and then unzip it. The zips are deleted after that.

**Comment by Bakhangtaku0** [comment]
Same situation, any solution?

**Comment by Menelkir** [comment]
> Same situation, any solution?

It was answered, unless you have a different situation.
