### ISSUE TITLE
I CANT COOP MODE

### ISSUE THREAD

**Issue by bikinmalu** [yaagl/yet-another-anime-game-launcher#273]
**Describe the bug**
I GOT STUCK WHEN I TRY TO COOP WITH SOME OTHER PLAYER

**Screenshots**

**System Information (please complete the following information):**
 - macOS: 14.3.1 SONOMA
 - Device: iMAC 2019 
 - CPU: Intel i7
 - Dedicated GPU (if any): AMD RADEON PRO R560x 4GB
 - RAM: 16GB

**Comment by Menelkir** [comment]
Needs Sonoma 14.4.
