### ISSUE TITLE
the game keeps crashing while playing .

### ISSUE THREAD

**Issue by PEACEBOI712** [yaagl/yet-another-anime-game-launcher#276]
the game keeps crashing within a few minutes of playing . I copied down the error report and created a txt file . its in the link pasted below 

https://drive.google.com/file/d/1w_gt86rosOGfkL7sOi6jD5KGOs7i0zUq/view?usp=sharing

**Comment by akshad-m** [comment]
same

**Comment by akshad-m** [comment]
same it also happens with me

**Comment by RMSwitchUS** [comment]
it also happens with me
![Uploading Screenshot 2024-03-08 at 18.22.36.png…]()

**Comment by Somwow** [comment]
This also happens to me, could someone kindly help us pls:)
<img width="759" alt="Screenshot 2024-03-08 at 17 25 09" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/159336913/e678a6a7-3126-4173-95a4-29e6bfd206b8">
<img width="854" alt="Screenshot 2024-03-08 at 17 25 23" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/159336913/425d5ddf-9165-4595-a258-410427b15119">

**Comment by reaji** [comment]
+1 
It happens after Mac OS 17.4 beta 4 and now with the Mac OS 17.4 official release.

**Comment by wildsol** [comment]
+1
Crushes while playing
macOS Sonoma 14.4
Apple M3 Pro

**Comment by Kevin-Haus24** [comment]
<img width="1188" alt="Снимок экрана 2024-03-10 в 11 34 17" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/126864281/79e1e09e-2ad0-46be-a3e2-0c68cc7994ec">

macOS Sonoma 14.4
MacBook Air 2021 m1 
Запускается игра только с патчем, играется 2 минуты и вылетает. Изменение версии Wine ничего не меняет. :(

**Comment by bikinmalu** [comment]
resolve anyone?

**Comment by Somwow** [comment]
Is there a way to fix this issue or do we have to wait for a new update?

**Comment by Menelkir** [comment]
Try `unstable-bh-wine-1.1`.

**Comment by bikinmalu** [comment]
> Try `unstable-bh-wine-1.1`.

stuck on loading when i try this

**Comment by wildsol** [comment]
> Try `unstable-bh-wine-1.1`.

Thank you! Works excellent - no crashes after one hour of playing 👍

**Comment by bikinmalu** [comment]
> > Try `unstable-bh-wine-1.1`.
> 
> Thank you! Works excellent - no crashes after one hour of playing 👍

but why in my case, it doesnt work, plz help me

**Comment by wildsol** [comment]
> but why in my case, it doesnt work, plz help me

What I did:
1. Update Launcher to latest v1.9
2. In Launcher settings select **Game** -> unstable-bh-wine-1.1
3. Launcher starts installing new **wine**. 
4. Appears window **Wine Mono Installer**, click **Install**
<img width="460" alt="Screenshot 2024-03-13 at 21 19 16" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/13206000/584a48b7-1a8e-4917-a5f1-718196d29a47">
5. Run the game

MacBook Pro
**OS**: Sonoma 14.4
**Chip**: Apple M3 Pro

**Comment by bikinmalu** [comment]
> > but why in my case, it doesnt work, plz help me
> 
> What I did:
> 
> 1. Update Launcher to latest v1.9
> 2. In Launcher settings select **Game** -> unstable-bh-wine-1.1
> 3. Launcher starts installing new **wine**.
> 4. Appears window **Wine Mono Installer**, click **Install**
> 
> <img alt="Screenshot 2024-03-13 at 21 19 16" width="460" src="https://private-user-images.githubusercontent.com/13206000/312688704-584a48b7-1a8e-4917-a5f1-718196d29a47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTkxMDMsIm5iZiI6MTcxMDM5ODgwMywicGF0aCI6Ii8xMzIwNjAwMC8zMTI2ODg3MDQtNTg0YTQ4YjctMWE4ZS00OTE3LWE1ZjEtNzE4MTk2ZDI5YTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA2NDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMmNkNzQwMDQ1YzcyOTcxNGYxN2YxZGM2YzFkNzRiNzUxOTgyNTA5ZjFmNDU3MWRiNzRkYzQyYzJkZTE2ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nPNqYFNthfWR8BF8PtniXJ_D8nbYDdEDs96TwzFKp_o"> 5. Run the game
> MacBook Pro **OS**: Sonoma 14.4 **Chip**: Apple M3 Pro

i already do, but it doesnt work for me, game is running but, stuck in loading game

**Comment by bikinmalu** [comment]
i use GI-Wine 1.2, every minute is crash, and forced close or stuck, when i try to launch game and back to the game, always reconnecting the server
<img width="2048" alt="Screenshot 2024-03-16 at 22 45 06" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/b230876d-475a-40c8-8db5-6c82c041db29">
dat pict when d game was stuck
i cant screenshot when reconnecting, because its so fast

**Comment by Zqanx** [comment]
16gb or more of ram: crossover wine 
Less than that: unstable-bh-wine-1.1 or gptk wine

**Comment by bikinmalu** [comment]
> 16gb or more of ram: crossover wine Less than that: unstable-bh-wine-1.1 or gptk wine

i already use crossover wine, the result is verification never show up, uncheck AC patch is done
<img width="2048" alt="Screenshot 2024-03-19 at 03 29 33" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/87b7bcd3-c4ff-4b90-a5df-385496aee8c4">

**Comment by Uraboros08** [comment]
> > Попробуй `нестабильное-bh-вино-1.1`.
> 
> Спасибо! Работает отлично - без сбоев после одного часа игры 👍

My textures are all distorted, there are no doors, chests or characters, only faces

**Comment by Menelkir** [comment]
> > > Попробуй `нестабильное-bh-вино-1.1`.
> > 
> > 
> > Спасибо! Работает отлично - без сбоев после одного часа игры 👍
> 
> My textures are all distorted, there are no doors, chests or characters, only faces

Disable _Dynamic Character Resolution_.

**Comment by Sipperz** [comment]
Closing issue because no Further response, Feel free to re-open the issue if required.
