### ISSUE TITLE
The game just doesn’t start

### ISSUE THREAD

**Issue by erysmvn** [yaagl/yet-another-anime-game-launcher#277]
**System Information (please complete the following information):**
 - macOS: [Version 14.1.1 Sonoma]
 - Device: [MacbookPro 13inch 2022 ]
 - CPU: [ Apple M2 ]
 - Dedicated GPU 
 - RAM: [ 8G ]

The game just doesn’t start guys, may it be cause i downloaded it on an external drive?

https://github.com/3Shain/yet-another-anime-game-launcher/assets/124170570/47c7a489-b271-4905-8d28-196e6a236d2e

**Comment by Menelkir** [comment]
Only works with macos 14.4 and up.
