### ISSUE TITLE
so wht to do anyone help??

### ISSUE THREAD

**Issue by akitort** [yaagl/yet-another-anime-game-launcher#278]
![Uploading Screenshot 2024-03-10 at 11.59.29 AM.png…]()

**Comment by akitort** [comment]
the verfication thingy aint showing

**Comment by akitort** [comment]
<img width="1440" alt="Screenshot 2024-03-10 at 11 59 29 AM" src="https://github.com/3Shain/yet-another-anime-game-launcher/assets/142984210/4387b55a-7627-44cc-b3f3-533208571f97">

**Comment by Somwow** [comment]
Fist log in with ac patch off: off verify then close application.
then open with ac patch off: on in game setting on launcher and enter the game.

**Comment by Zqanx** [comment]
Still need help?

**Comment by Xkid0525** [comment]
> Still need help?

Yes please, The 2FA verification to send code to the email is still blank even when I put the acc patch off.

**Comment by Zqanx** [comment]
Try spamming enter while captcha box is showing up. Minimizing game/tabbing out of game also worked for some.

**Comment by Xkid0525** [comment]
> Try spamming enter while captcha box is showing up. Minimizing game/tabbing out of game also worked for some.

Doesn't seem to work for mine. Thanks tho.

**Comment by Xkid0525** [comment]
OK To whoever comes here and gets stuck here, There are 2 things you need to make sure you had done. 1. Make sure you are not running the game from "Downloads"2.. You should Extract the application and drag and drop it into "Application". and then make sure the settings in the AC path.
