### ISSUE TITLE
Failed to load il2cpp

### ISSUE THREAD

**Issue by its3ng** [yaagl/yet-another-anime-game-launcher#283]
**Describe the bug**
I just downloaded yaagl 1.9 and when i press launch game is says "Failed to load il2cpp" Help

**Screenshots**

<img width="1051" alt="Screenshot 2024-03-12 at 7 52 08 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163225474/4c92ab7a-6d52-4bfa-9835-e4b03ceae6ce">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.3
 - Device: Macbook Pro 16-inch, 2021
 - CPU: Apple M1 Pro
 - Dedicated GPU (if any): N/A
 - RAM: 16 GB

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Pierreluc15** [comment]
You need to install Sonoma 14.4

**Comment by Menelkir** [comment]
As mentioned, only 14.4 and up.
