### ISSUE TITLE
Error when trying to launch game

### ISSUE THREAD

**Issue by cath-mg** [yaagl/yet-another-anime-game-launcher#284]
**Describe the bug**
Upon clicking 'Launch Game' button, encounters "Failed to load il2cpp" error message (this happens more frequently), or stuck at "Game is running (DO NOT CLOSE THE LAUNCHER)" infinite loading.

**Screenshots**
<img width="1280" alt="Screenshot 2024-03-14 at 8 32 55 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/15902019/a68e92de-3615-4bf6-b891-4bf84c5e36ab">
<img width="1278" alt="Screenshot 2024-03-14 at 8 40 27 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/15902019/dd1a4af5-fb41-4f8b-b877-132a933c17bd">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.4
 - Device: Macbook Pro 14-inch 2023
 - CPU: M3 Pro
 - Dedicated GPU (if any): N/A
 - RAM: 36 GB

**Additional context**
What I've tried:
- Reinstalled launcher using all the listed Wine Distribution available
- Reformatted external hard disk containing the game files into APFS
- Moved YAAGL Launcher under Applications

**Logs (if any)**
neutralinojs.log attached below:
[neutralinojs.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/14602593/neutralinojs.log)

**Comment by Zqanx** [comment]
Have you tried crossover wine? The option appears in yaagl settings once you download crossover.

**Comment by cath-mg** [comment]
@Zqanx Isn't CrossOver a paid software with only 14 days free trial?

**Comment by Menelkir** [comment]
> @Zqanx Isn't CrossOver a paid software with only 14 days free trial?

There's a 15-day trial, and you only need to open crossover once, and the reopen yaagl to the option be available.

**Comment by cath-mg** [comment]
@Menelkir Installed CrossOver, did [this](https://github.com/yaagl/yet-another-anime-game-launcher/wiki/CrossOver:-use-latest-MoltenVK), and retried... Loader said "Game is running (DO NOT CLOSE THE LAUNCHER)" -> "Reverting patch", then nothing happened.

**Comment by Menelkir** [comment]
Try without updating the dylib.

**Comment by floki-kaki** [comment]
> @Menelkir Installed CrossOver, did [this](https://github.com/yaagl/yet-another-anime-game-launcher/wiki/CrossOver:-use-latest-MoltenVK), and retried... Loader said "Game is running (DO NOT CLOSE THE LAUNCHER)" -> "Reverting patch", then nothing happened.

exact same problem here

**Comment by floki-kaki** [comment]
> Try without updating the dylib.

the same thing happens

**Comment by cath-mg** [comment]
> @Menelkir: Try without updating the dylib.
Nope, still not working, unfortunately. It's the same behavior.

**Comment by floki-kaki** [comment]
those who get the same problem running genshin on windows natively say its because of the UserAssembly.dll file (GenshinImpact_Data/Native/UserAssembly.dll)

**Comment by Zqanx** [comment]
Try file integrity check?

**Comment by floki-kaki** [comment]
doesnt return anything, does it just put a log file somewhere or does it show up on the spot?

**Comment by ImZedik** [comment]
Same problem for me too.

**Comment by cath-mg** [comment]
@Zqanx Did the integrity check, clicked "Launch Game" button, and same error ("Failed to load il2cpp"), unfortunately.

**Comment by Zqanx** [comment]
Not sure what is wrong here... you do have Sonoma 14.4. This happened a lot to people who didn't update to 14.4. Worst case scenario reinstall.

**Comment by floki-kaki** [comment]
idk i have 14.3.1 thats prob it

**Comment by floki-kaki** [comment]
yep! the game runs just fine on Sonoma 14.4, thanks @Zqanx

**Comment by cath-mg** [comment]
@Zqanx reinstall the game? Or the macOS itself?

**Comment by bikinmalu** [comment]
> @Zqanx reinstall the game? Or the macOS itself?

i already done dis, re install d game, but nothing happens

**Comment by Zqanx** [comment]
> @Zqanx reinstall the game? Or the macOS itself?

Reinstall the game. 
Make sure it's located somewhere non-accessible to icloud which could potentially corrupt the files. Ideally a new folder directly under your user (if it isn't already the case).

**Comment by soocc** [comment]
Anyone found a fix? I have the same problem too

**Comment by Shhhh72** [comment]
Have you tried using a different wine? I had an issue where it wouldn't start up too and changed the wine from the default one and it worked.

**Comment by Sipperz** [comment]
Closing issue because no response, Feel free to re-open the issue if required.
