### ISSUE TITLE
Always stuck in game and reconnecting the server after that

### ISSUE THREAD

**Issue by bikinmalu** [yaagl/yet-another-anime-game-launcher#286]
i use GI-Wine 1.2, every minute is crash, and forced close or stuck, when i try to launch game and back to the game, always reconnecting the server

<img width="2048" alt="Screenshot 2024-03-16 at 22 45 06" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/89527a9d-9b23-47f4-8165-17027df535db">
<img width="2048" alt="Screenshot 2024-03-16 at 23 15 09" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/8030c85a-5f33-4595-8b0f-5db3c9940523">

dis when game was stuck

<img width="2048" alt="Screenshot 2024-03-16 at 23 15 09" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/8030c85a-5f33-4595-8b0f-5db3c9940523">
and dis after dat

 - macOS: [e.g. 14.4 Sonoma
 - Device: [e.g. Imac 2019 ]
 - CPU: [e.g. Intel i7 ]
 - Dedicated GPU (if any): [e.g.  Radeon Pro 560x 4gb ]
 - RAM: [e.g. 16G ]

**Additional context**

**Comment by Zqanx** [comment]
Try crossover wine. The option will appear in yaagl settings once you download crossover.

**Comment by bikinmalu** [comment]
> Try crossover wine. The option will appear in yaagl settings once you download crossover.

how to try dis?

**Comment by Menelkir** [comment]
https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#18crossover-does-not-show-on-yaagl-settings

**Comment by bikinmalu** [comment]
> https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#18crossover-does-not-show-on-yaagl-settings

i already try this, but verification never show up, uncheck AC patch already but still d same
<img width="2048" alt="Screenshot 2024-03-19 at 03 29 33" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/695d5c20-4a46-4ed6-b64f-90331d183920">

**Comment by Menelkir** [comment]
> > https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#18crossover-does-not-show-on-yaagl-settings
> 
> i think dis software is paid, or not?use free trial?

There's a 15-day trial, and you can just open it once.

**Comment by bikinmalu** [comment]
> > > https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#18crossover-does-not-show-on-yaagl-settings
> > 
> > 
> > i think dis software is paid, or not?use free trial?
> 
> There's a 15-day trial, and you can just open it once.

https://github.com/yaagl/yet-another-anime-game-launcher/issues/286#issuecomment-2004933130

**Comment by bikinmalu** [comment]
> > > https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#18crossover-does-not-show-on-yaagl-settings
> > 
> > 
> > i think dis software is paid, or not?use free trial?
> 
> There's a 15-day trial, and you can just open it once.

verification isnt comin when login

**Comment by Zqanx** [comment]
Try doing the verification blindly

**Comment by bikinmalu** [comment]
> Reference

maybe its possible, but really really hard

**Comment by bikinmalu** [comment]
> i use GI-Wine 1.2, every minute is crash, and forced close or stuck, when i try to launch game and back to the game, always reconnecting the server
> 
> <img alt="Screenshot 2024-03-16 at 22 45 06" width="2000" src="https://private-user-images.githubusercontent.com/161714653/313416854-89527a9d-9b23-47f4-8165-17027df535db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM0MDQsIm5iZiI6MTcxMDg4MzEwNCwicGF0aCI6Ii8xNjE3MTQ2NTMvMzEzNDE2ODU0LTg5NTI3YTlkLTliMjMtNDdmNC04MTY1LTE3MDI3ZGY1MzVkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDQ2NDZkODFjZWZhMDQ3YTdjMDUyNmNlNmJiNGUxYWM5OTE3NTU4NTUyYTNhNWFmMTk1NWMwZDU0MTY0NWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oo1HMq0CWbO-w1UxXaVHiAUfCLXiKsNUT1W_o1Uc2vQ"> <img alt="Screenshot 2024-03-16 at 23 15 09" width="2000" src="https://private-user-images.githubusercontent.com/161714653/313416871-8030c85a-5f33-4595-8b0f-5db3c9940523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM0MDQsIm5iZiI6MTcxMDg4MzEwNCwicGF0aCI6Ii8xNjE3MTQ2NTMvMzEzNDE2ODcxLTgwMzBjODVhLTVmMzMtNDU5NS04YjBmLTVkYjNjOTk0MDUyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTA3ZTk5MWUxYTM4ZWEwMjFhNDZjMzRkNDA5ZjYwMDQ2ODk0MjkxNjZhN2U2YjEzNmZkMTcyMGQwODFmYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yc1gEl3gWyJnu_hVq0c6vp7Cg95Z3sZI2XqYIjOs1eE">
> dis when game was stuck
> 
> <img alt="Screenshot 2024-03-16 at 23 15 09" width="2000" src="https://private-user-images.githubusercontent.com/161714653/313416871-8030c85a-5f33-4595-8b0f-5db3c9940523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM0MDQsIm5iZiI6MTcxMDg4MzEwNCwicGF0aCI6Ii8xNjE3MTQ2NTMvMzEzNDE2ODcxLTgwMzBjODVhLTVmMzMtNDU5NS04YjBmLTVkYjNjOTk0MDUyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTA3ZTk5MWUxYTM4ZWEwMjFhNDZjMzRkNDA5ZjYwMDQ2ODk0MjkxNjZhN2U2YjEzNmZkMTcyMGQwODFmYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yc1gEl3gWyJnu_hVq0c6vp7Cg95Z3sZI2XqYIjOs1eE"> and dis after dat
> * macOS: [e.g. 14.4 Sonoma
> * Device: [e.g. Imac 2019 ]
> * CPU: [e.g. Intel i7 ]
> * Dedicated GPU (if any): [e.g.  Radeon Pro 560x 4gb ]
> * RAM: [e.g. 16G ]
> 
> **Additional context** Add any other context about the problem here.

i try use another server, i use europe server, its works, but my game profile at beginning again

**Comment by Menelkir** [comment]
> > i use GI-Wine 1.2, every minute is crash, and forced close or stuck, when i try to launch game and back to the game, always reconnecting the server
> > <img alt="Screenshot 2024-03-16 at 22 45 06" width="2000" src="https://private-user-images.githubusercontent.com/161714653/313416854-89527a9d-9b23-47f4-8165-17027df535db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM0MDQsIm5iZiI6MTcxMDg4MzEwNCwicGF0aCI6Ii8xNjE3MTQ2NTMvMzEzNDE2ODU0LTg5NTI3YTlkLTliMjMtNDdmNC04MTY1LTE3MDI3ZGY1MzVkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDQ2NDZkODFjZWZhMDQ3YTdjMDUyNmNlNmJiNGUxYWM5OTE3NTU4NTUyYTNhNWFmMTk1NWMwZDU0MTY0NWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Oo1HMq0CWbO-w1UxXaVHiAUfCLXiKsNUT1W_o1Uc2vQ"> <img alt="Screenshot 2024-03-16 at 23 15 09" width="2000" src="https://private-user-images.githubusercontent.com/161714653/313416871-8030c85a-5f33-4595-8b0f-5db3c9940523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM0MDQsIm5iZiI6MTcxMDg4MzEwNCwicGF0aCI6Ii8xNjE3MTQ2NTMvMzEzNDE2ODcxLTgwMzBjODVhLTVmMzMtNDU5NS04YjBmLTVkYjNjOTk0MDUyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTA3ZTk5MWUxYTM4ZWEwMjFhNDZjMzRkNDA5ZjYwMDQ2ODk0MjkxNjZhN2U2YjEzNmZkMTcyMGQwODFmYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yc1gEl3gWyJnu_hVq0c6vp7Cg95Z3sZI2XqYIjOs1eE">
> > dis when game was stuck
> > <img alt="Screenshot 2024-03-16 at 23 15 09" width="2000" src="https://private-user-images.githubusercontent.com/161714653/313416871-8030c85a-5f33-4595-8b0f-5db3c9940523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4ODM0MDQsIm5iZiI6MTcxMDg4MzEwNCwicGF0aCI6Ii8xNjE3MTQ2NTMvMzEzNDE2ODcxLTgwMzBjODVhLTVmMzMtNDU5NS04YjBmLTVkYjNjOTk0MDUyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQyMTE4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTA3ZTk5MWUxYTM4ZWEwMjFhNDZjMzRkNDA5ZjYwMDQ2ODk0MjkxNjZhN2U2YjEzNmZkMTcyMGQwODFmYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yc1gEl3gWyJnu_hVq0c6vp7Cg95Z3sZI2XqYIjOs1eE"> and dis after dat
> > 
> > * macOS: [e.g. 14.4 Sonoma
> > * Device: [e.g. Imac 2019 ]
> > * CPU: [e.g. Intel i7 ]
> > * Dedicated GPU (if any): [e.g.  Radeon Pro 560x 4gb ]
> > * RAM: [e.g. 16G ]
> > 
> > **Additional context** Add any other context about the problem here.
> 
> i try use another server, i use europe server, its works, but my game profile at beginning again

The profiles are not shared between servers unfortunately. But it's strange having issues between servers since the game is already loaded.

**Comment by Menelkir** [comment]
Do you still have this issue?
