### ISSUE TITLE
I CANT IN GAME STUCK ON LOADING

### ISSUE THREAD

**Issue by bikinmalu** [yaagl/yet-another-anime-game-launcher#287]
I TRY RO CHANGE GI WINE TO 1.0 , 1.2 BUT STILL SAME

<img width="2048" alt="Screenshot 2024-03-18 at 01 16 58" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/34fa2f44-ad59-44c9-ae84-a82c84f24fea">

 - macOS: [e.g. 14.4 SONOMA]
 - Device: [e.g. IMAC INTEL 2019]
 - CPU: [e.g. INTEL I7 ]
 - Dedicated GPU (if any): [e.g.  RADEON PRO 560X 4GB ]
 - RAM: [e.g. 16G ]

**Comment by Zqanx** [comment]
Try crossover wine. Look in the faq more info.

**Comment by bikinmalu** [comment]
> Try crossover wine. Look in the faq more info.

i was, but verification isnt coming up

**Comment by Menelkir** [comment]
> > Try crossover wine. Look in the faq more info.
> 
> i was, but verification isnt coming up

Yes but now you don't have to do the verification again I guess?
Just try again with crossover.

**Comment by Sipperz** [comment]
Closing issue because no response, Feel free to re-open the issue if required.
