### ISSUE TITLE
Crashes when doing quests

### ISSUE THREAD

**Issue by Baemigo** [yaagl/yet-another-anime-game-launcher#289]
**Describe the bug**
I started the teapot quest and no matter what I did the first option to select to start the quest would always crash the game. The rest of the game works great just quests seem to freak it out

**Screenshots**
The photo provided is just next to the quest giver Xiaqiao
<img width="1233" alt="Screenshot 2024-03-20 at 7 16 54 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/118240549/dbf72b81-3e2c-4e1f-b209-221411c83647">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.4
 - Device: iMac 2019 Z12V000PEX/A
 - CPU:  Apple M1
 - Dedicated GPU (if any): 8 Core GPU (4 performance 4 efficiency)
 - RAM: 16GB LPDDR4

**Additional context**
I haven't tried other quests yet, I couldn't locate any logs either

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
Disable _Dynamic Character Resolution_ in game settings.
