### ISSUE TITLE
Showing error message, stuck in loading screen

### ISSUE THREAD

**Issue by RMSwitchUS** [yaagl/yet-another-anime-game-launcher#290]
**Describe the bug**
Game stuck in loading screen
I usually use unstable bh wine 1.1 after updating to MacOS Sonoma and it worked just fine
But since yesterday it keeps showing this problem
need help 

**Screenshots**
<img width="1710" alt="Screenshot 2024-03-23 at 15 01 30" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/162700663/0784dc36-c659-4ac3-81bf-497c6aea6572">
<img width="1710" alt="Screenshot 2024-03-23 at 15 01 49" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/162700663/58fe6e0b-b823-4d69-8f55-90f1f52493f8">
<img width="1710" alt="Screenshot 2024-03-23 at 15 04 30" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/162700663/2d45de89-a436-4385-a82d-1b709b0a30d5">

**System Information (please complete the following information):**
 - macOS: 14.4 Sonoma
 - Device: MacBook Air M2
 - CPU: Apple M2
 - Dedicated GPU (if any):
 - RAM: 16GB, SSD 512

**Additional context**
**_the error message_**

Unhandled exception: page fault on read access to 0x63222c223733224a in 64-bit code (0x00000100c9aa1f).
Register dump:
 rip:0000000100c9aa1f rsp:00000000116ae4a0 rbp:0000000100cffa00 eflags:00000246 (   - --  I  Z- -P- )
 rax:63222c223733223a rbx:0000000004feac90 rcx:0000000004feac90 rdx:00000000066a3680
 rsi:0000000000000000 rdi:0000000004feacb0  r8:0000000100d06620  r9:0000000000000000 r10:0000000000000001
 r11:0000000000000016 r12:0000000100d06620 r13:0000000100cffa00 r14:0000000004feacf0 r15:00000000066ed110
Stack dump:
0x000000116ae4a0:  00000000116ae53c 000000000a33cafa
0x000000116ae4b0:  0000000000000030 00000000116ae600
0x000000116ae4c0:  0000000000000001 0000000000000003
0x000000116ae4d0:  0000000000008000 00000000066df370
0x000000116ae4e0:  00000000066df330 0000000004fead10
0x000000116ae4f0:  0000000000000000 0000000100c9a8da
0x000000116ae500:  0000000000000030 0000000000000016
0x000000116ae510:  0000000000008001 0000000006eaecf0
0x000000116ae520:  0000000006eaed20 00000000116ae53c
0x000000116ae530:  0000000000000016 0000001600000016
0x000000116ae540:  0000000004feacf0 0000000000000000
0x000000116ae550:  0000000004fead10 0000000100cffa00
Backtrace:
=>0 0x00000100c9aa1f in crypt32 (+0x1aa1f) (0x00000100cffa00)
  1 0x00000100c9a8da in crypt32 (+0x1a8da) (0000000000000000)
  2 0x00000100c9aa2c in crypt32 (+0x1aa2c) (0x00000100cffa00)
  3 0x00000100c9a8da in crypt32 (+0x1a8da) (0000000000000000)
  4 0x00000100c9aa2c in crypt32 (+0x1aa2c) (0x00000100cffa00)
  5 0x00000100cf456c in crypt32 (+0x7456c) (0000000000000000)
  6 0x00000100c88abb in crypt32 (+0x8abb) (0000000000000000)
  7 0x00000100c927c0 in crypt32 (+0x127c0) (0x0000000671cf90)
  8 0x00000100c92d19 in crypt32 (+0x12d19) (0x0000000671cf90)
  9 0x00000100c960e5 in crypt32 (+0x160e5) (0x000000066df1e0)
  10 0x00000100c98f38 in crypt32 (+0x18f38) (0x00000006722ca8)
  11 0x000001efe05435 in winhttp (+0x5435) (0x00000006722ca8)
  12 0x000001efe15d72 in winhttp (+0x15d72) (0x0000017006ece0)
  13 0x000001efe18013 in winhttp (+0x18013) (0x000000000000c0)
  14 0x000001efe18206 in winhttp (+0x18206) (0x000000000000c0)
  15 0x000001efe18e03 in winhttp (+0x18e03) (0x000001efe261b0)
  16 0x000001efe20b6d in winhttp (+0x20b6d) (0x000001efe261b0)
  17 0x0000010d6c2480 in astrolabe (+0x202480) (0x00191600283a48)
  18 0x0000010d6b8469 in astrolabe (+0x1f8469) (0x000000116af748)
  19 0x0000010d6542d7 in astrolabe (+0x1942d7) (0000000000000000)
  20 0x0000010d7beaf4 in astrolabe (+0x2feaf4) (0000000000000000)
  21 0x0000010d7be7bf in astrolabe (+0x2fe7bf) (0xaaaaaaaaaaaaaaaa)
  22 0x0000010d7cb52a in astrolabe (+0x30b52a) (0xaaaaaaaaaaaaaaaa)
  23 0x0000010d7bf35d in astrolabe (+0x2ff35d) (0x00191600283cc8)
  24 0x0000010d666bc0 in astrolabe (+0x1a6bc0) (0x00000000000001)
  25 0x0000010d5ac784 in astrolabe (+0xec784) (0x00000000000001)
  26 0x0000010d5ac92d in astrolabe (+0xec92d) (0x00000000000001)
  27 0x0000010d5bb082 in astrolabe (+0xfb082) (0x00000000000001)
  28 0x0000017802cc89 in kernel32 (+0x2cc89) (0000000000000000)
  29 0x0000017006fa75 in ntdll (+0x6fa75) (0000000000000000)
0x00000100c9aa1f crypt32+0x1aa1f: mov 0x10(%rax), %rax
Modules:
Module	Address					Debug info	Name (31 modules, 60 for wow64 not listed)
ELF	0000000000000000-000000000000c000	Deferred        <wine-loader>
ELF	0000000004770000-0000000004774000	Deferred        <wine-loader>
ELF	000000000483d000-00000000048f5000	Deferred        ntdll.so
PE	00000000686ca000-00000000686fa000	Deferred        libpng16.16.dylib
ELF	00000000687d8000-00000000687e4000	Deferred        ws2_32.so
ELF	00000000687fa000-00000000689ae000	Deferred        win32u.so
PE	0000000068b94000-0000000068c34000	Deferred        libfreetype.6.dylib
ELF	000000006ad11000-000000006ad1d000	Deferred        dnsapi.so
ELF	000000006ad26000-000000006ad36000	Deferred        bcrypt.so
ELF	000000006ad4a000-000000006ad56000	Deferred        crypt32.so
PE	000000006ad6d000-000000006ad91000	Deferred        libintl.8.dylib
PE	000000006adbd000-000000006add9000	Deferred        libtasn1.6.dylib
ELF	000000006ae0c000-000000006af0c000	Deferred        opengl32.so
PE	000000006b065000-000000006b0a1000	Deferred        libidn2.0.dylib
PE	000000006b104000-000000006b154000	Deferred        libnettle.8.8.dylib
PE	000000006b1a8000-000000006b1f0000	Deferred        libhogweed.6.8.dylib
ELF	000000006b228000-000000006b230000	Deferred        kerberos.so
ELF	000000006b230000-000000006b238000	Deferred        netapi32.so
PE	000000006b23a000-000000006b416000	Deferred        libgnutls.30.dylib
PE	000000006b628000-000000006b76c000	Deferred        libp11-kit.0.dylib
PE	000000006b9af000-000000006ba23000	Deferred        libgmp.10.dylib
PE	000000006baf9000-000000006bcb5000	Deferred        libunistring.5.dylib
ELF	000000006be85000-000000006be95000	Deferred        secur32.so
ELF	000000006bea6000-000000006beb2000	Deferred        msv1_0.so
PE	000000006bebb000-000000006bed0000	Deferred        libobjc-trampolines.dylib
ELF	000000006beda000-000000006bf6a000	Deferred        winemac.so
ELF	000000006e9b8000-000000006ea44000	Deferred        winevulkan.so
PE	000000006f8ba000-000000006fff2000	Deferred        libmoltenvk.dylib
PE	00007ff80a66f000-00007ff80a6aa000	Deferred        libsystem_kernel.dylib
PE	00007ff80a6aa000-00007ff80a6b6000	Deferred        libsystem_pthread.dylib
PE	00007ff80a6db000-00007ff80a6e6000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	00000094    0     wine_rpcrt4_io
	000000b4    0     wine_rpcrt4_io
	000000d0    0     wine_rpcrt4_io
	000000e4    0     
	000000f0    0     wine_rpcrt4_io
	00000194    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000dc    0     
00000068 winedevice.exe
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	0000007c    0     
	00000080    0     
	0000008c    0     
	00000090    0     
	000000a0    0     
	000000a4    0     
00000084 explorer.exe
	00000088    0     
	000000a8    0     
	000000ac    0     wine_rpcrt4_server
00000098 plugplay.exe
	0000009c    0     
	000000bc    0     
	000000c0    0     wine_sechost_service
	000000c4    0     wine_rpcrt4_server
	000002b4    0     wine_rpcrt4_io
	000002b8    0     wine_threadpool_worker
000000c8 svchost.exe
	000000cc    0     
	000000d4    0     
	000000d8    0     wine_sechost_service
000000e8 rpcss.exe
	000000ec    0     
	000000f4    0     
	000000f8    0     wine_sechost_service
	000000fc    0     wine_rpcrt4_server
	00000100    0     wine_rpcrt4_server
	00000104    0     wine_rpcrt4_io
0000010c cmd.exe
	00000110    0     
00000124 (D) Z:\Users\rizkamaulana\Anime Game\GenshinImpact.exe
	00000128    0     
	0000012c    0     
	0000013c    0     
	00000140    0     wine_threadpool_worker
	00000144    0     wine_threadpool_waitqueue
	00000148    0     
	00000188    0     
	0000018c    0     wine_threadpool_worker
	00000190    0     wine_threadpool_worker
	00000198    0     ShaderLoadManagerT
	0000019c    0     
	000001a0    0     
	000001a4    0     wine_threadpool_worker
	000001a8    0     wine_threadpool_worker
	000001ac    0     wine_threadpool_worker
	000001b0    0     wine_threadpool_worker
	000001b4    0     
	000001b8    0     
	000001bc    0     
	000001c0    0     
	000001c4    0     
	000001c8    0     
	000001cc    0     ThreadPoolServiceThread
	000001d0    0     ThreadPoolForegroundWorker
	000001d4   -2     ThreadPoolBackgroundWorker
	000001d8    0     astrolale_main_default
	000001dc    0     astrolale_url_fetcher
	000001e0   -2     ThreadPoolBackgroundWorker
	000001e4    0     astrolale_logback
	000001e8    0     astrolale_network
	000001ec    0     wine_threadpool_timerqueue
	000001f0    0     ThreadPoolForegroundWorker
	000001f4    0     PAC thread #0
	000001f8    0     PAC thread #1
	000001fc    0     GC Marker 0
	00000200    0     GC Marker 1
	00000204    0     GC Marker 2
	00000208    0     GC Marker 3
	0000020c    0     GC Marker 4
	00000210    0     GC Marker 5
	00000214    0     GC Marker 6
	00000218    0     GC Finalizer
	0000021c   -1     BatchDeleteObjects
	00000220    0     AsyncReadManager
	00000224    0     dxvk-pcompiler
	00000228    0     dxvk-pcompiler
	0000022c    0     dxvk-pcompiler
	00000230    0     dxvk-pcompiler
	00000234    0     dxvk-pcompiler
	00000238    0     dxvk-submit
	0000023c    0     dxvk-queue
	00000240    0     dxvk-cs
	00000244    0     UnityGfxDeviceWorker
	00000248    0     Worker Thread
	0000024c    0     Worker Thread
	00000250    0     Worker Thread
	00000254    0     Worker Thread
	00000258    0     Worker Thread
	0000025c    0     Worker Thread
	00000260    0     Worker Thread
	00000264   -2     BackgroundWorker
	00000268   -2     BackgroundWorker
	0000026c   -2     BackgroundWorker
	00000270   -2     BackgroundWorker
	00000274    0     
	00000278    0     
	0000027c    0     
	00000280    0     
	00000284    0     
	00000288    0     
	0000028c    0     
	00000290   -2     UnitySubstanceThread
	00000294   -2     dxvk-shader
	00000298   -2     dxvk-shader
	0000029c   -2     dxvk-shader
	000002a0   -2     dxvk-shader
	000002a4   -2     dxvk-shader
	000002a8    0 <== PAC thread #2
	000002ac    0     wine_xinput_hid_update
	000002b0    0     wine_sechost_device_notify
	000002bc    0     
	000002c0   15     
	000002c4   -1     UnityPreload
	000002d8    0     
	000002e0    0     
000002d0 conhost.exe
	000002d4    0     
System information:
    Wine build: wine-8.16
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Darwin
    Host version: 23.4.0

**Comment by Zqanx** [comment]
Try crossover wine?

**Comment by Sipperz** [comment]
is this issue resolved?
