### ISSUE TITLE
genshin not loading

### ISSUE THREAD

**Issue by clemthelem** [yaagl/yet-another-anime-game-launcher#291]
i have crossover and my mac is on sonoma 14.4.1 using yaagl 0.1.9 
when i launch the game my computer just gets stuck on the hoyoverse screen and i have to force quit it (my mac doesnt say its not responding tho) 
before i got crossover it would get stuck loading on the 7 visions thing and then my mac would crash 
does anyone know how to fix this issue?

**Comment by tenphi** [comment]
I found that using CXPatcher breaks the compatibility. Maybe it's your case as well.
Using wine works fine.

**Comment by Sipperz** [comment]
is this issue resolved? do reply to confirm or tell us more about it.
