### ISSUE TITLE
can't download requested file

### ISSUE THREAD

**Issue by mdalhagg** [yaagl/yet-another-anime-game-launcher#293]
**Describe the bug**
when i open the game and start downloading requested file after complete download it's show me like this ??

what should ii do?

**Screenshots**

<img width="1639" alt="Screenshot 2024-03-29 at 1 52 09 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/59109473/be212521-fd25-4cbc-beea-5120496cf0ac">

**System Information (please complete the following information):**
 - macOS: 14.4 sonoma
 - Device: Macbook Air 16inch 2023 
 - CPU:  Apple M2, silicon 
 - RAM: 8G

**Comment by Zqanx** [comment]
Restart a few times. People also mentionned files being locked in specific cases, as well as using antivirus, dns filters, external drive not being set to apfs, etc. Verify if it is your case. Check this post in our discord server https://discord.com/channels/1085010808678912090/1205012024145354762/1205012024145354762

**Comment by MohammedAlhagg** [comment]
thanks it's solved
