### ISSUE TITLE
I wanna change the icon of the launcher to use the anime game's original icon, how?

### ISSUE THREAD

**Issue by le0-VV** [yaagl/yet-another-anime-game-launcher#295]
There are 2 ways to change a macOS App's icon. You replace the .icns file in the directory, or you use "Get Info" on the app to soft-change the icon. Neither of the 2 methods work when Yaagl is open however, as the icon will change back to the Yaagl icon, which doesn't comply with the [macOS icon guideline outlined since Big Sur](https://developer.apple.com/design/human-interface-guidelines/app-icons).

Is there a way I can change the icon myself? Its kinda big deal for me

**Comment by Menelkir** [comment]
I do use custom icons on many apps and both ways works for me tho.

**Comment by le0-VV** [comment]
does the icon change back to Yaagl stock icon when you open the launcher?

**Comment by le0-VV** [comment]
I've upscaled Yaagl's stock icon and generated an [icns file](https://dropovercl.s3.amazonaws.com/4151dc64-3275-4d64-9e91-870c0e44ce9f/6ba34c1a-8643-4124-840b-8e8660b9c955/a7324e5a-db77-4245-b55d-6768aac12d4b.icns) from it, link valid for 3 months

**Comment by Menelkir** [comment]
Sorry for the late reply, it's giving me access denied.

**Comment by le0-VV** [comment]
Oh crap the link must have expired, lemme re upload real quick

**Comment by le0-VV** [comment]
https://a.dropoverapp.com/cloud/download/fd3c39c8-841c-4f19-8d42-37a5075eda2d/afaaeede-d123-4e5a-8f09-0ca8e0c325f8

Link expires 3 months from now

**Comment by Menelkir** [comment]
I had an odd behavior, but it's more like a macos behavior.
**Test 1:** Copy and pasted the icon using the "Get info".
**Test 2:** Modified the internal icns file on Resource folder.
![Screenshot 2024-04-05 at 18 40 53](https://github.com/yaagl/yet-another-anime-game-launcher/assets/110792903/ef9d6624-3679-4bbb-96e3-bc151b268ee5)
The one modifed persisted even after a reboot, until I "Get info" on it.
![Screenshot 2024-04-05 at 18 41 23](https://github.com/yaagl/yet-another-anime-game-launcher/assets/110792903/89b41722-eda0-48ea-b1e9-597d0d3ada8d)

**Comment by le0-VV** [comment]
They do persist after a reboot, but what bugs me is that when you open the app, it temporarily goes back to stock, then changes back to custom afterwards. And idk if that's a me thing or it's a common issue. I have this happen to a lot of other apps as well, Snap Inc's Lens Studio for example.

Let me show you what I mean: 

https://github.com/yaagl/yet-another-anime-game-launcher/assets/40534994/ba015705-64b6-4134-b1a2-b4d0406166ab

**Comment by le0-VV** [comment]
I cloned the repo and replaced /src/icons/Paimon.cr.png with a png version of the icon I'm using and built my own launcher, the launcher now uses the new icon properly

**Comment by le0-VV** [comment]
Created [pull request](https://github.com/yaagl/yet-another-anime-game-launcher/pull/301) to replace the icon
