### ISSUE TITLE
Can't open the game

### ISSUE THREAD

**Issue by dwtnan** [yaagl/yet-another-anime-game-launcher#297]
https://github.com/yaagl/yet-another-anime-game-launcher/assets/149883685/3274431b-0387-462b-a26f-0951ece8ec6b

MacBook Pro 2022 13inches
macOS 14.4.1 Sonoma 
Apple M2 silicon 
RAM 8GB

**Comment by Zqanx** [comment]
Reinstall launcher and launcher files. Method is on the main page. Game files don't need to be touched.

**Comment by jxy599** [comment]
重新安装了也是同样的问题

**Comment by Zqanx** [comment]
@dwtnan @jxy599 
这边注意系统要更新到 14.4。然后游戏资源最好放在 /user 里面的一个新文件夹，不要放在 /documents 或者桌面上。这些地方会收到 iCloud 的干扰。然后 yaagl 设置里再检测一下资源完整性。

**Comment by Raganhildis** [comment]
都按照你说的做了之后游戏还是打不开呀

**Comment by Zqanx** [comment]
@Raganhildis 
是像上面视频里这种情况吗？这个问题很奇怪，一般不太发生。你先确定一下 Rosetta 2 有没有更新到最新版。到终端里把这个粘贴进去然后按回车键：`softwareupdate --install-rosetta`。然后如果失败了就多试几次。如果终端里说`software update not available`，则把电脑重启一下。

**Comment by Raganhildis** [comment]
> @Raganhildis 是像上面视频里这种情况吗？这个问题很奇怪，一般不太发生。你先确定一下 Rosetta 2 有没有更新到最新版。到终端里把这个粘贴进去然后按回车键：`softwareupdate --install-rosetta`。然后如果失败了就多试几次。如果终端里说`software update not available`，则把电脑重启一下。

好的谢谢 游戏打开了
