### ISSUE TITLE
数据异常，请重新登录游戏

### ISSUE THREAD

**Issue by 3Shain** [yaagl/yet-another-anime-game-launcher#3]
__解决方案：仍在调查中__

目前已知的信息：
在Apple Silicon设备上几乎必定复现。
部分Intel设备也可复现。

重装启动器/游戏均无法解决。

初步结论：触发了服务端发出的设备帐号绑定的风控

如果你也遇到相同的情况，请补充更多的信息，例如
* 你的设备型号（CPU，内存大小，显卡）
* 你的系统版本
* 最近有什么特别的操作
* 使用mac登录的游戏时间

**Comment by Midolii** [comment]
|设备型号|CPU|内存大小|
|:--:|:--:|:--:|
|MacBook Pro2021 16inch|m1pro|16|

|系统版本|
|:--:|
|ventura 13.2.1 (22D68)|

- 最近本子没有进行特别的操作
- 最近使用mac登陆游戏的时间为昨天下午2点

**Comment by NIAOTOU** [comment]
设备型号：MacBook Pro（M1pro、16G内存）
系统版本：13.0 (22A380)
刚刚安装Yaagl 第一次登录就数据异常
从未使用mac登陆过游戏

**Comment by Evanyang0425** [comment]
设备型号：MacBook Pro（M1pro、16G内存）
系统版本：13.3 Beta版(22E5236f)
数据异常

**Comment by caozhaoqi** [comment]
设备型号：Mac mini m2 8+256
系统版本：13.2.1
数据异常 无法登陆

**Comment by 1nno4ent** [comment]
设备型号：Macbook Pro（M1Pro、16G内存）

系统版本：13.2.1 (22D68)

crossover和wine都数据异常

**Comment by Mayne-B** [comment]
Mac Book Pro 14寸 2021年
M1 Pro 16GB
第一次使用Yaagl登陆 数据异常
本人平时在本溪使用ipad登陆原神，在第一次尝试用Yaagl登陆未果后就去了米哈游通行证查询登陆设备情况，用Yaagl登陆原神显示的情况是，window且IP为大连

**Comment by AmethBin** [comment]
设备型号：Macbook Pro 2021, M1 Max 32G
系统版本：13.2.1 (22D68)
可正常登陆游戏的配置：Wine -> gi-wine-1.0,  Workaround -> 打开;
显数据异常的配置：Wine -> gi-wine-1.0,  Workaround -> 关闭;  Wine -> unstable-gi-wine-031201-O3,  Workaround -> 关闭;
游戏无法打开的配置：Wine -> unstable-gi-wine-031201-O3,  Workaround -> 打开;

数据异常与登录IP应当无关，因为新建号也显示数据异常。

**Comment by jerryzhang123456** [comment]
设备型号：iMac 2021, M1 16G
系统版本：13.3 (beta)
最早直接使用start.command登陆
几天前发现数据异常，转而使用yaagl启动器登陆
可正常登陆游戏的配置：Wine -> unstable-gi-wine-031201-O3, Workaround -> 打开;
显数据异常的配置：Wine -> gi-wine-1.0, Workaround -> 关闭; Wine -> unstable-gi-wine-031201-O3, Workaround -> 关闭;
Wine -> unstable-gi-wine-nt-0, Workaround -> 关闭

**Comment by 1nno4ent** [comment]
个人解决方案：先用O3不带workaround进游戏，账号异常属于正常情况，然后退出游戏，打开workaround，再次启动游戏即可进入了，且账号异常被绕过，第一次有可能会崩，再启动一次就好了

**Comment by HowieHye** [comment]
- 设备型号： `MacBook Air 2020, M1 16G`
- 系统版本： `13.2.1`
- Wine 版本: `gi-wine-1.0`
- DXVK Shader 异步编译: `启用`
- Workaround : `启用`

以上配置可正常游戏，不开`Retina模式`能稳定55帧以上，开`Retina模式`会比较卡。

**Comment by cyp0633** [comment]
MacBook Pro 13 2020，i5-1038NG7，16G内存，核显
macOS 13.4
一个月前正常登录，之后未用此Mac登录过；IP段与之前成功登录时不同

**Comment by brainbush** [comment]
MacBook Pro 2021 16 M1 pro 16G
13.4 (22F66)
最近一次尝试发现提示登陆异常后，切换网络能成功登陆，但再次在切换后的网络登陆就一直提示登陆异常
尝试操作：打开/关闭workaround 3   删除application support所有文件并重新输入验证码登陆

**Comment by coocy** [comment]
你的设备型号（CPU，内存大小，显卡）:iMac 2019 40G内存 eGPU 6800XT
你的系统版本: macOS 13.4
最近有什么特别的操作: 无

前几天第一次安装用的CrossOver，接下来的几天都可正常启动并进入，今天发现异常，然后安装Yaagl，进入后依然异常，然后用新注册账号登录，还是异常。尝试同一账号iPhone上可正常进入。

尝试了几个不同的Wine版本（包括unstable-gi-wine-031201-O3）
尝试打开关闭Workaround
尝试切换IP
尝试删除Application Support下的文件
以上方法都不行

没有尝试：重新安装游戏（因为游戏太大了硬盘不足，我也懒得重新下载安装)

**Comment by pplppl888** [comment]
设备型号： Mac Studio M1 Ultra 128GB
系统版本： 13.4.1
Wine 版本: gi-wine-1.2
Workaround : 启用
原神数据异常请重新登录

**Comment by HuserCXname** [comment]
设备型号（CPU，内存大小，显卡）:Intel(R) Celeron(R) N5095A @ 2.00GHz   2.00 GHz
16.0 GB (11.8 GB 可用)
Intel(R) UHD Grahics
系统版本:Windows 10 专业版
最近有什么特别的操作:无

**Comment by Stapxs** [comment]
你的设备型号（CPU，内存大小，显卡）：MacBook Pro 2013，M2、16G
你的系统版本：Sonoma 14 RC
最近有什么特别的操作：最近有异地登陆
使用mac登录的游戏时间：最近两个月内都没有

**Comment by LYX473** [comment]
> 个人解决方案：先用O3不带workaround进游戏，账号异常属于正常情况，然后退出游戏，打开workaround，再次启动游戏即可进入了，且账号异常被绕过，第一次有可能会崩，再启动一次就好了

也不行啊

**Comment by Stapxs** [comment]
> 你的设备型号（CPU，内存大小，显卡）：MacBook Pro 2013 16inch，M2 Pro、16G 你的系统版本：Sonoma 14 RC 最近有什么特别的操作：新设备，最近有异地登陆 使用mac登录的游戏时间：最近两个月内都没有

4.1 新版本已恢复 emmmm

**Comment by onevcat** [comment]
一般来说，每个版本前十天甚至二十天是没问题的。在下半开池开启前，基本会开始进行设备标记，并添加帐号和设备的识别，导致出现这个错误无法登入。

猜测这个识别列表是放在内存里的，版本更新重启服务器时这部分内容丢失，所以每个版本前几天可以正常登入。

4.1 的 release note 里有一条“反作弊系统更新”，不知道是否会影响至今为止的行为模式。可以静待十来天再看。

**Comment by Stapxs** [comment]
> 一般来说，每个版本前十天甚至二十天是没问题的。在下半开池开启前，基本会开始进行设备标记，并添加帐号和设备的识别，导致出现这个错误无法登入。
> 
> 猜测这个识别列表是放在内存里的，版本更新重启服务器时这部分内容丢失，所以每个版本前几天可以正常登入。
> 
> 4.1 的 release note 里有一条“反作弊系统更新”，不知道是否会影响至今为止的行为模式。可以静待十来天再看。

事实证明开池子前还是寄了（恼

**Comment by waterlens** [comment]
设备型号：MacBook Pro M2 Pro 14寸 2023 32+512
系统版本：Sonoma 14.0
最近特别的操作：新本子
Mac 登录的游戏时间：尚无
