### ISSUE TITLE
Game NPC display abnormality

### ISSUE THREAD

**Issue by ChowQio** [yaagl/yet-another-anime-game-launcher#300]
**Describe the bug**
1/Some game NPCs are abnormally displayed and only their faces are displayed when they are close to them, but normal when I are far away.
2/All pages that only open web pages, such as game announcements, failed to open.
**Screenshots**
<img width="1512" alt="截屏2024-04-06 00 01 36" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163286064/06daa652-4a77-479b-ac22-3dd8d0e6fbad">

**System Information (please complete the following information):**
 - macOS: 14.4.1
 - Device: MBP 2021
 - CPU: M1 pro
 - Dedicated GPU (if any): 
 - RAM: [16G ]

**Additional context**

**Logs (if any)**

[game_1712330029076.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/14887628/game_1712330029076.log)
[game_1712210189531.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/14887632/game_1712210189531.log)
[game_1712232246095.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/14887633/game_1712232246095.log)

**Comment by Menelkir** [comment]
Disable _Dynamic Character Resolution_ inside the game settings.
