### ISSUE TITLE
[SOLVED] Fatal Error - "Yaggl OS" cannot be opened because the developer cannot be verifid

### ISSUE THREAD

**Issue by isamon614** [yaagl/yet-another-anime-game-launcher#302]
Cannot launch Yaagl
Was able to use the application easily earlier today as i was on a field trip and decided to play genshin. when i got back to school, i downloaded [CAASPP secure browser](https://ca.portal.cambiumast.com/index.html) in order to take a test i needed to take on the mac. after i finished the test, i played osu. now, i tried opening YAAGL again, and was greeted with this message
<img width="292" alt="Screenshot 2024-04-09 at 4 09 14 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/166566485/2b6bd5ec-2d9d-4ac3-92c7-48a078b0deb5">
actually, i was greeted with an error that just said "Fatal Error" this screenshot was only after i tried deleting and reinstalling YAAGL. 
**System Information (please complete the following information):**
 - macOS: [Sonoma 14.4.1]
 - Device: [MacBook Pro 14-inch, 2021]
 - CPU: [Apple M1 Pro]
 - RAM: [16 GB ]

Im new to using Github and stuff so idrk like the rules and termsand stuff, sorry in advance.

**Comment by isamon614** [comment]
looks like i just missed a step from this[ tutorial video ](https://youtu.be/n5avbxzzTsU?si=MEo9QnEJPBwgbjt_&t=202) all worked fine. but anyone know why it showed the message even after it worked perfectly fine only hours before?

**Comment by Menelkir** [comment]
It's literally written there. 
The app isn't verified because you have to pay apple to sign an app to make it "verified by apple".
