### ISSUE TITLE
error #2cpp in trying to log in

### ISSUE THREAD

**Issue by cyataz** [yaagl/yet-another-anime-game-launcher#304]
i'm met with either a forever loading screen or a 2cpp error in the launch screen

<img width="662" alt="Screenshot 2024-04-14 at 12 32 15 am" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/166929728/4c2b4ca6-4e2d-4a22-b30c-ad542695456c">

i have a M2 ventura 13.2.1 which i should probably update to a 14.4.1, but is there anything in mind that i should do before this? 

Also, what do the different wines do? I have tried out a couple, but the ones i tried didnt work

**Comment by Menelkir** [comment]
It's on FAQ, only work on Sonoma for arm macs.
