### ISSUE TITLE
Error, Load Failed?

### ISSUE THREAD

**Issue by Rallywolf120** [yaagl/yet-another-anime-game-launcher#305]
I went through the steps to install the game. I clicked on "Install Game" and then it kicked me out of the App. Afterward I tried to open it back up and it just presented me with "TypeError: Load failed".

System Information 
<img width="2240" alt="Screenshot 2024-04-16 at 7 00 14 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/167261710/4f8d3078-6900-433b-81dd-03ff2857b8c0">

 - macOS: Sonoma 14.41
 - Device: IMac 24 inch, 2023
 - CPU: Apple M3
 - RAM: 8 GB

**Comment by Zqanx** [comment]
It might be a network issue. Recently someone had a similar issue and changing DNS from 1.1.1.1 to 8.8.8.8 solved it.

**Comment by Rallywolf120** [comment]
Wait I have another question. But thank you on the helpful tip, it did work! Now its doen loading but whenever it finishes to the end of the bar, the progress resets. Just wondering if its suppose to do that? Is it part of the downloading process?

**Comment by Menelkir** [comment]
> Wait I have another question. But thank you on the helpful tip, it did work! Now when it's done loading and it finishes to the end of the bar, the progress resets. Just wondering if its suppose to do that? Is it part of the downloading process?

It doesn't "reset", read the FAQ.

**Comment by Zqanx** [comment]
> Wait I have another question. But thank you on the helpful tip, it did work! Now when it's done loading and it finishes to the end of the bar, the progress resets. Just wondering if its suppose to do that? Is it part of the downloading process?

Yes. It downloads about seven to eight 10g zip files. So it downloads a new zip file after one is done, it doesn't reset. This #1 clause in the faq.
