### ISSUE TITLE
Failed to load il2cpp

### ISSUE THREAD

**Issue by YongUSin** [yaagl/yet-another-anime-game-launcher#306]
**Describe the bug**
It says 'failed to load il2cpp', and doesn't work anymore.

**Screenshots**

**System Information (please complete the following information):**
 - macOS: 14.4.1 Sonoma
 - Device: Macbook Pro 14 M3
 - RAM: 16G

**Additional context**
I read another closed issue #283 , and the solution was to update to 14.4 and up
but my one is already 14.4.1 :(

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Zqanx** [comment]
1. Check file integrity 
2. Redownload launcher (method on main page)

**Comment by Sipperz** [comment]
Commenting to see if the issue was resolved or not, Reopen the issue if more help is wanted.
