### ISSUE TITLE
''The launcher does not currently support version 4.6.0. Please wait for further updates.''

### ISSUE THREAD

**Issue by mon0z** [yaagl/yet-another-anime-game-launcher#308]
So I pre-downloaded version 4.6 on my Mac Pro Sonoma 14.4 and when the update came out it said that the launcher doesn't support the version? I tried turning off AC path but that prevented me from logging in.
<img width="946" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/167961140/451604f3-d40b-4548-a116-c2d4ea8fec8e">

 - macOS: Sonoma 14.4
 - Device: MacBook M1 Pro 14-inch
 - RAM: 16GB

**Comment by mordantes** [comment]
Same issue

**Comment by a-gaitian** [comment]
Works fine for me on same machine

**Comment by yikl1004** [comment]
same issue

**Comment by Menelkir** [comment]
Unbelievable.

**Comment by duckcinema** [comment]
this works for me until i 'click to begin' after log in. it stuck on white screen

**Comment by Menelkir** [comment]
It says to wait for further updates, then wait for further updates.

https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#21hey-version-x-is-already-out--when-will-yaagl-be-updated-for-x-version
