### ISSUE TITLE
Can't launch Yaagl

### ISSUE THREAD

**Issue by 1WASP11** [yaagl/yet-another-anime-game-launcher#312]
**Describe the bug**
Can't launch Yaagl

**Screenshots**
![Знімок екрана 2024-04-25 о 22 29 46](https://github.com/yaagl/yet-another-anime-game-launcher/assets/168131686/42442f49-29e6-4b5b-add9-de5120e889ce)

**System Information (please complete the following information):**
 - macOS: [10.13.6]
 - Device: [iMac 27-inch, Late 2009 ]
 - CPU: [intel i7 2,8 GHz ]
 - Dedicated GPU (if any): [ATI Radeon HD 4850 512MB]
 - RAM: [12G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
You didn't read https://github.com/yaagl/yet-another-anime-game-launcher?tab=readme-ov-file#install
