### ISSUE TITLE
Stuck on "allocating files on disk"

### ISSUE THREAD

**Issue by Soliturd** [yaagl/yet-another-anime-game-launcher#313]
**Describe the bug**
when I go to update the game, it refuses and just stays on the "allocating files on disk" screen. tried everything I could think of, will not work.

**Screenshots**
<img width="1264" alt="Screenshot 2024-04-26 at 3 44 52 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168102066/d532f00d-a318-4bf8-973e-ea7e75a39a52">

**System Information (please complete the following information):**
 - macOS: [Sonoma Version 14.4.1]
 - Device: [MacBook Air 13" 2020]
 - CPU: [Apple M1 (i cant find anymore info on the cpu)]
 - RAM: [8GB]

**Additional context**
Apparently someone else has had this issue before but the info on in makes 0 sense to me.

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
(how do i do this)

**Comment by the-biggest-birfd** [comment]
try installing it overnight and see in the morning if its still allowcating

**Comment by Sipperz** [comment]
Are you using a External Drive?

**Comment by Soliturd** [comment]
@Sipperz what does that mean?

(I’m not very tech savvy I’m so sorry)

**Comment by Sipperz** [comment]
> @Sipperz what does that mean?
> 
> 
> 
> (I’m not very tech savvy I’m so sorry)

No worries, it's like a USB you can attach to your Mac through a cable, to transfer data.

**Comment by Soliturd** [comment]
> > @Sipperz what does that mean?
> > (I’m not very tech savvy I’m so sorry)
> 
> No worries, it's like a USB you can attach to your Mac through a cable, to transfer data.

No, I just have it downloaded to my mac. Though most of my storage goes to YAAGL, not any other games.

**Comment by Sipperz** [comment]
Oh okey, did it eventually work or still stuck?

**Comment by Soliturd** [comment]
> Oh okey, did it eventually work or still stuck?

Im gonna test it out later today, but I haven't had any progress at all

**Comment by Soliturd** [comment]
I think there has been something wrong with my mac. i erased all data and ill update if it works now.

**Comment by Soliturd** [comment]
Something turned out to be wrong with my mac. I cant tell exactly what but for me i was unable to open or interact with files, and no games including YAAGL worked. 

if this is happening to you, i might suggest completely erasing and reseting your mac through settings
