### ISSUE TITLE
cannot open the game

### ISSUE THREAD

**Issue by aiolia1** [yaagl/yet-another-anime-game-launcher#315]
**Describe the bug**
click the button "start game", the game does not open.
![Uploading log.png…]()
the yaagl version is 0.10.

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. 14.5 Ventura]
 - Device: [e.g. MacbookPro 14inch]
 - CPU: [e.g. Apple M1 ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by aiolia1** [comment]
<img width="1222" alt="log" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/144715559/d52e4701-c71a-4aa4-a0ff-5317b28a603e">

**Comment by Menelkir** [comment]
For Arm macs, only Sonoma 14.4 or superior works.
