### ISSUE TITLE
game keeps crashing

### ISSUE THREAD

**Issue by rkxlinx** [yaagl/yet-another-anime-game-launcher#317]
Hey folks! I just downloaded this launcher to play some genshin again and I've been having problems with laggy combat and with the game crashing (It happens every 5-10 minutes or so) and it's annoying me a lot. Any help would be greatly appreciated!

**System Information:**
 - macOS: [13.4.1 Sonoma]
 - Device: [MacbookPro 13inch 2022 ]
 - CPU: [Apple M2]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [8 GB ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Sipperz** [comment]
If you are Using "gi-wine-1.0/1.2" I will recommend switching it to "unstable-bh-gptk-1.0",
Yaagl Launcher > Settings > Wine > "Unstable-bh-gptk1.0".
If the option is not there, Download Game Porting Tool Kit.

**Comment by rkxlinx** [comment]
Thank you so much! The game is working now :))
