### ISSUE TITLE
password no writer

### ISSUE THREAD

**Issue by asakew** [yaagl/yet-another-anime-game-launcher#319]
**Describe the bug**

**Screenshots**
<img width="1440" alt="Снимок экрана 2024-05-01 в 20 48 42" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/46191008/7dab11d6-08fa-45ba-aa88-ba4ae00de8d9">

**System Information (please complete the following information):**
 - macOS: sanoma 14.4.1
 - Device: Macbook 13inch 2019
 - CPU: Apple M1
 - Dedicated GPU: M1
 - RAM: 8GB

**Additional context**
password no witer, not copy, paste text

**Comment by asakew** [comment]
[game_1714559680792.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15176408/game_1714559680792.log)
[game_1714560401334.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15176409/game_1714560401334.log)

**Comment by Sipperz** [comment]
When you type password it is being registered just not showing it on the bar.
Copy paste does not work on some wines, Try Ctrl + V instead of Cmd + V, See if this helps as that is the Command to Copy paste on windows.

**Comment by asakew** [comment]
Thanks you 😍

<img width="1440" alt="Снимок экрана 2024-05-02 в 18 26 14" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/46191008/cd2299de-cdb9-4e1d-ad1d-140576908ef5">

**Comment by asakew** [comment]
Thanks you for help😍

**Comment by Sipperz** [comment]
Glad to Help, Happy Gaming.
