### ISSUE TITLE
Mouse unresponsive issue

### ISSUE THREAD

**Issue by SimplySora** [yaagl/yet-another-anime-game-launcher#32]
**Describe the bug**
No matter the settings I use, the mouse always lags behind my inputs in actual gameplay. Especially noticeable while aiming. This occurs with any mouse I try and it is *only* while playing the anime game. It's about a half second delay, and it only applies to camera movement. When navigating menus the delay is gone. No such delay exists for keyboard inputs. 

**System Information (please complete the following information):**
 - macOS: 13.2 Ventura
 - Device: Mac Studio
 - CPU: Apple M1 Max
 - RAM: 64GB

**Comment by SimplySora** [comment]
It also tends to just freeze up sometimes for about half a second. Makes aiming feel extremely choppy.

**Comment by 3Shain** [comment]
🤔️ I have no idea, seems it's caused by wine. I can solve a problem only if I can reproduce.

**Comment by JZVince** [comment]
Try to lower your mouse polling rate (125 worked fine for me).
