### ISSUE TITLE
Freeze after clicking outside the game

### ISSUE THREAD

**Issue by istucesyt** [yaagl/yet-another-anime-game-launcher#320]
**Describe the bug**
As soon as I click outside the game (external screen) or open _Mission Control_ or another app, the pointer no longer clicks once inside the game.
Thank you in advance for your help.

**Screenshots**
Ø

**System Information (please complete the following information):**
 - macOS: Sonoma 14.5 beta 2
 - Device: MacBook Air 15" 2023
 - CPU: Apple M2
 - Dedicated GPU (if any): (Apple M2)
 - RAM: 8G

**Additional context**
Ø

**Logs (if any)**
Ø

**Comment by istucesyt** [comment]
I don't think so: I was on 14.4 (stable) not long ago and I had the same problem.
Maybe the external screen? It's a Samsung HDMI screen, and I find that it is not well integrated by macOS: the SF symbols are distorted for example...

**Comment by Sipperz** [comment]
Hmm.. let's see
