### ISSUE TITLE
Game graphics shitting itself whenever there’s a vine thingy underwater

### ISSUE THREAD

**Issue by mon0z** [yaagl/yet-another-anime-game-launcher#321]
Basically when I’m in Fontaine, the screen just goes weird whenever I’m in a mile radius of those vine cages, this is really annoying and I don’t know if there’s a solution for this 

![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/167961140/b1fd8d25-0dd5-442a-9a26-cc3a67a37c4d)

my MacBook is a MacBook Pro Sonoma 14.4 14 inch 16GB RAM

**Comment by Zqanx** [comment]
Try disabling subsurface scattering in settings
