### ISSUE TITLE
i can't login (The web doesn't open)

### ISSUE THREAD

**Issue by Heon0719** [yaagl/yet-another-anime-game-launcher#322]
**Describe the bug**
i can't login (The web doesn't open)
After entering the password, I cannot pass the Captcha to register a new device. Even when logging in using Facebook or Twitter, only a blank screen appears, as shown in the screenshot above. I did a lot of searching and tried turning the AC option on and off and deleting the web folder in the game installation folder, but the symptom was not resolved. I played it fine yesterday on another Mac. But it doesn't work on today's new MacBooks.

**Screenshots**
<img width="1728" alt="스크린샷 2024-05-04 오후 10 18 28" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/68222910/95d99fce-f048-433d-822b-c1eafbb5ae93">

**System Information (please complete the following information):**
 - macOS: 14.4.1 sonama
 - Device: MacBookPro 16" M1 Pro
 - CPU: M1 Pro
 - Dedicated GPU (if any): null
 - RAM: 16gb

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Heon0719** [comment]
On the left is the m1 pro 16 inch with the above problem and on the right is the m3 pro 16 inch. It works. Both are the same 14.4.1 Sonoma, same yaagi, same options.
![IMG_1658](https://github.com/yaagl/yet-another-anime-game-launcher/assets/68222910/1f29866f-6bc4-4b6c-9898-cf39cb71e5df)

**Comment by Sipperz** [comment]
The Captcha login issue is also known to happen on windows every now and then, Will recommend trying to use some of these known methods - 

1. do it blind by drag drop the puzzle
2. alt-tab minimise/maximise genshin before login
3. try on-off AC patch for the above
4. Spamming return key

See if any of these solutions help you in getting the captcha.

**Comment by Sipperz** [comment]
Issue was Solved by changing wine version to "unstable-bh-gptk-1.0".
