### ISSUE TITLE
Game crashes while switching between domains, and during fast paced animations. 

### ISSUE THREAD

**Issue by mynameisjoe01928** [yaagl/yet-another-anime-game-launcher#323]
**Describe the bug**
While switching from or to Domains, especially during the new Vibro-Crystal Applications event, the game kills itself after only loading half of the hydro symbol in the load bar. Again, during Character Burst animations or Character Skill animations, the game decides to also kill itself but play the happy music. Game also must be force quit, as normal quitting does not work.

**Screenshots**
<img width="2240" alt="Screenshot 2024-05-05 at 9 14 53 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/965ccf46-e070-49d9-88d8-5c81513c8a13">

**System Information (please complete the following information):**
 - macOS: macOS 14.5 Beta 
 - Device: iMac 24 inch, 2021
 - CPU: Apple M1
 - RAM: 8Gb

**Additional context**
Workaround #3 and "Turn off AC patch" are both turned on to allow for the game to actually load, and most settings are on medium or low because this computer is sad.

**Comment by Sipperz** [comment]
Which wine version are u using?
Try switch it to "unstab;e-bh-gptk-1.0" if its not on it already.

**Comment by Somwow** [comment]
THANK YOU SO MUCH !!!
I also had the same problem, and your solution worked!!!

**Comment by mynameisjoe01928** [comment]
> Which wine version are u using? Try switch it to "unstable-bh-gptk-1.0" if its not on it already.

I've tried using all other wine versions, but I found that only "unstable-gi-wine-1.12" works. "unstable-bh-gptk-1.0" doesn't load any graphics for me.

**Comment by mynameisjoe01928** [comment]
> Which wine version are u using? Try switch it to "unstable-bh-gptk-1.0" if its not on it already.

I've tried using all other wine versions, but I found that only "unstable-gi-wine-1.12" works. "unstable-bh-gptk-1.0" doesn't load any graphics for me.

**Comment by Sipperz** [comment]
> > Which wine version are u using? Try switch it to "unstable-bh-gptk-1.0" if its not on it already.
> 
> 
> 
> I've tried using all other wine versions, but I found that only "unstable-gi-wine-1.12" works. "unstable-bh-gptk-1.0" doesn't load any graphics for me.

Tuna integrity check from launcher settings, untick the "workaround #3" option", see if it changes anything.

**Comment by mynameisjoe01928** [comment]
> > > Which wine version are u using? Try switch it to "unstable-bh-gptk-1.0" if its not on it already.
> > 
> > 
> > I've tried using all other wine versions, but I found that only "unstable-gi-wine-1.12" works. "unstable-bh-gptk-1.0" doesn't load any graphics for me.
> 
> Do a integrity check from launcher settings, untick the "workaround #3" option", see if it changes anything.

If I untick the "workaround #3" option, the game doesn't load even after 10 minutes.

**Comment by Sipperz** [comment]
> > > > Which wine version are u using? Try switch it to "unstable-bh-gptk-1.0" if its not on it already.
> > > 
> > > 
> > > I've tried using all other wine versions, but I found that only "unstable-gi-wine-1.12" works. "unstable-bh-gptk-1.0" doesn't load any graphics for me.
> > 
> > 
> > Do a integrity check from launcher settings, untick the "workaround #3" option", see if it changes anything.
> 
> If I untick the "workaround #3" option, the game doesn't load even after 10 minutes.

weird, will have to look into it, Idk if the Macos beta has something to do with it.

**Comment by mynameisjoe01928** [comment]
> > > > > Which wine version are u using? Try switch it to "unstable-bh-gptk-1.0" if its not on it already.
> > > > 
> > > > 
> > > > I've tried using all other wine versions, but I found that only "unstable-gi-wine-1.12" works. "unstable-bh-gptk-1.0" doesn't load any graphics for me.
> > > 
> > > 
> > > Do a integrity check from launcher settings, untick the "workaround #3" option", see if it changes anything.
> > 
> > 
> > If I untick the "workaround #3" option, the game doesn't load even after 10 minutes.
> 
> weird, will have to look into it, Idk if the Macos beta has something to do with it.

Thanks!
