### ISSUE TITLE
The game crashes when entering the world

### ISSUE THREAD

**Issue by DaniilBurd** [yaagl/yet-another-anime-game-launcher#324]
I log into the game normally. At the moment of authorization and loading, the game does not crash even if it is on it for a long time, but if I load and enter the world, then literally after a couple of minutes the game crashes
**Screenshots**

**System Information (please complete the following information):**
 - macOS: [macOS Sonoma 14.4]
 - Device: [MacbookPro 13inch 2020]
 - CPU: [Apple M1 ]

 - RAM: [8 gb ]

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
[game_1714992556222.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15219833/game_1714992556222.log)

> If it's relate
[crash report .zip](https://github.com/yaagl/yet-another-anime-game-launcher/files/15219843/crash.report.zip)
d to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by minorenji** [comment]
Same issue on Apple M1 Pro, 16GB, Sonoma 14.4.1.

I took a look at my logs myself and as far as I can tell, the first unusual sequence of errors is this which repeats a couple times:

```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 2):
Vertex attribute v3(3) of type uint2 cannot be read using MTLAttributeFormatHalf2.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_1518e3df6bb0d5f47e947e88b8921a10176f36ee
err:     fs  : FS_155fe232c704af5e155c9299fa8bfa1761800a7b
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 1 : location 2, binding 2, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 2 : location 1, binding 1, format VK_FORMAT_R16G16_SFLOAT, offset 4
err:     attr 3 : location 3, binding 1, format VK_FORMAT_R16G16_SFLOAT, offset 8
err:     attr 4 : location 4, binding 1, format VK_FORMAT_R16G16_SFLOAT, offset 8
err:     binding 0 : binding 0, stride 48, rate 0, divisor 0
err:     binding 1 : binding 1, stride 12, rate 0, divisor 0
err:     binding 2 : binding 2, stride 48, rate 0, divisor 0
```
OP's log also contains this error, and it consistently appears in the logs where my game crashed.

Occasionally, this error also happens first:

```
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Shader module does not contain an entry point named 'main0'.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Vertex shader function could not be compiled into pipeline. See previous logged error.
err:   DxvkGraphicsPipeline: Failed to compile pipeline
err:     vs  : VS_a848f5b98baf0e0841e192b19edeccac97b44aa6
err:     fs  : FS_dee044f663dab18f765e5165cbd546aac420fdc6
err:     attr 0 : location 0, binding 0, format VK_FORMAT_R32G32B32_SFLOAT, offset 0
err:     attr 1 : location 2, binding 0, format VK_FORMAT_R32G32B32_SFLOAT, offset 12
err:     attr 2 : location 1, binding 1, format VK_FORMAT_R8G8B8A8_UNORM, offset 0
err:     attr 3 : location 4, binding 1, format VK_FORMAT_R32G32_SFLOAT, offset 4
err:     attr 4 : location 5, binding 1, format VK_FORMAT_R32G32_SFLOAT, offset 4
err:     attr 5 : location 6, binding 1, format VK_FORMAT_R16G16_UINT, offset 12
err:     attr 6 : location 3, binding 0, format VK_FORMAT_R32G32B32A32_SFLOAT, offset 24
err:     binding 0 : binding 0, stride 40, rate 0, divisor 0
err:     binding 1 : binding 1, stride 24, rate 0, divisor 0
```

It's interesting because my game was working fine yesterday, and there's been no update since then. The only thing that has changed is the mid-patch release of a new in game event?

**Comment by Sipperz** [comment]
This seems to very well be a "Gi1.2/1.1 wine issue" atm, for 8 GB Ram Macs will recommend "unstable-bh-gptk-1.0", and for 16 GB and above Crossover wine will be the best option.

For crossover wine visit codeweavers website, if you don't see GPTK option download it from Official Apple site.
