### ISSUE TITLE
Keeps crashing, Big error

### ISSUE THREAD

**Issue by Rallywolf120** [yaagl/yet-another-anime-game-launcher#326]
The System was working fine. Sure it had a few problems but It still worked relatively fine. Now whenever I boot up the game it will just stay on the loading screen and crash or just boot up the game and then 30 seconds later it'll crash again

<img width="2240" alt="Screenshot 2024-05-08 at 5 50 51 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/167261710/af2b1f8a-5528-4ef6-8e5a-8a1090628527">

**System Information (please complete the following information):**
 - macOS: 14.4.1  
 - Device: iMac 24 in 2024
 - RAM: 8GB?

**Comment by H644b** [comment]
Ram is probably the issue.

**Comment by Sipperz** [comment]
its Not a Ram issue, it is a wine issue

switch wine to "unstable-bh-gptk-1.0"

Yaagl Settings > wine > *change wine version"

**Comment by yikl1004** [comment]
switch wine to "unstable-bh-gptk-1.0"
good working!!!

@Rallywolf120 Try it, and close this issue
