### ISSUE TITLE
wine keeps crashing 

### ISSUE THREAD

**Issue by erysmvn** [yaagl/yet-another-anime-game-launcher#327]
wine keeps crashing when i enter the world

<img width="1680" alt="Screenshot 2024-05-12 alle 1 22 40 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/124170570/59176d8e-0c22-4972-86a2-16493656bc19">

**System Information (please complete the following information):**
 - macOS: [14.4.1 Ventura]
 - Device: [MacbookPro 13inch 2022 ]
 - CPU: [ Apple M2 ]
 - RAM: [ 8G ]
 - Wine: [ gl 1.2 (stable) ]

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Sipperz** [comment]
Please change the wine to - "Unstable-bh-gptk-1.0".

It should resolve the issues.

**Comment by Eclopia** [comment]
> Please change the wine to - "Unstable-bh-gptk-1.0".
> 
> It should resolve the issues.

i had the same issue and i switched to that wine version, now the game wont even load

**Comment by Sipperz** [comment]
> > Please change the wine to - "Unstable-bh-gptk-1.0".
> > It should resolve the issues.
> 
> i had the same issue and i switched to that wine version, now the game wont even load

What are Ur Mac specs?

**Comment by Eclopia** [comment]
> > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > It should resolve the issues.
> > 
> > 
> > i had the same issue and i switched to that wine version, now the game wont even load
> 
> What are Ur Mac specs?
Its a little old -
macOS: 12.7.3
device- iMac (retina 5k, 27-inch, late 2015)
processor- 4GHz Quad-Core Intel Core i7
RAM- 32GB

**Comment by Eclopia** [comment]
> > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > It should resolve the issues.
> > 
> > 
> > i had the same issue and i switched to that wine version, now the game wont even load
> 
> What are Ur Mac specs?


Its a little old -
macOS: 12.7.3
device- iMac (retina 5k, 27-inch, late 2015)
processor- 4GHz Quad-Core Intel Core i7
RAM- 32GB

**Comment by Sipperz** [comment]
> > > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > > It should resolve the issues.
> > > 
> > > 
> > > i had the same issue and i switched to that wine version, now the game wont even load
> > 
> > 
> > What are Ur Mac specs?
> 
> Its a little old - macOS: 12.7.3 device- iMac (retina 5k, 27-inch, late 2015) processor- 4GHz Quad-Core Intel Core i7 RAM- 32GB

That will explain why gptk didn't work, Game Porting Tool Kit is make for M series Macs, for ur Ram Config will recommend Crossover.

**Comment by Eclopia** [comment]
> > > > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > > > It should resolve the issues.
> > > > 
> > > > 
> > > > i had the same issue and i switched to that wine version, now the game wont even load
> > > 
> > > 
> > > What are Ur Mac specs?
> > 
> > 
> > Its a little old - macOS: 12.7.3 device- iMac (retina 5k, 27-inch, late 2015) processor- 4GHz Quad-Core Intel Core i7 RAM- 32GB
> 
> That will explain why gptk didn't work, Game Porting Tool Kit is made for M series Macs, for ur Ram Config will recommend Crossover.

sorry I'm not a computer person, could you explain?

**Comment by Sipperz** [comment]
> > > > > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > > > > It should resolve the issues.
> > > > > 
> > > > > 
> > > > > i had the same issue and i switched to that wine version, now the game wont even load
> > > > 
> > > > 
> > > > What are Ur Mac specs?
> > > 
> > > 
> > > Its a little old - macOS: 12.7.3 device- iMac (retina 5k, 27-inch, late 2015) processor- 4GHz Quad-Core Intel Core i7 RAM- 32GB
> > 
> > 
> > That will explain why gptk didn't work, Game Porting Tool Kit is made for M series Macs, for ur Ram Config will recommend Crossover.
> 
> sorry I'm not a computer person, could you explain?

GPTK (Game Porting Tool Kit) is a Apple made version for M series (Arm Macs) the news [M1, M2, M3] chips, You are using a Intel Mac which does Apple do not support for GPTK, For Intel Macs there is a Program Called "Crossover", Search "Crossover for mac" on google it should lead u to "Codeweavers" website, on their website you can download FREE Crossover Trial.

Steps to Use Crossover on Yaagl-
1. Make sure to put Crossover in /Applications.
2. Open crossover once to let it finish its install.
3. Open Yaagl
4. Go to Yaagl Launcher settings > Wine > "should see Crossover as an option" > Switch to it.
5. Launch the game.

**Comment by Eclopia** [comment]
> > > > > > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > > > > > It should resolve the issues.
> > > > > > 
> > > > > > 
> > > > > > i had the same issue and i switched to that wine version, now the game wont even load
> > > > > 
> > > > > 
> > > > > What are Ur Mac specs?
> > > > 
> > > > 
> > > > Its a little old - macOS: 12.7.3 device- iMac (retina 5k, 27-inch, late 2015) processor- 4GHz Quad-Core Intel Core i7 RAM- 32GB
> > > 
> > > 
> > > That will explain why gptk didn't work, Game Porting Tool Kit is made for M series Macs, for ur Ram Config will recommend Crossover.
> > 
> > 
> > sorry I'm not a computer person, could you explain?
> 
> GPTK (Game Porting Tool Kit) is a Apple made version for M series (Arm Macs) the news [M1, M2, M3] chips, You are using a Intel Mac which does Apple do not support for GPTK, For Intel Macs there is a Program Called "Crossover", Search "Crossover for mac" on google it should lead u to "Codeweavers" website, on their website you can download FREE Crossover Trial.
> 
> Steps to Use Crossover on Yaagl-
> 
> 1. Make sure to put Crossover in /Applications.
> 2. Open crossover once to let it finish its install.
> 3. Open Yaagl
> 4. Go to Yaagl Launcher settings > Wine > "should see Crossover as an option" > Switch to it.
> 5. Launch the game.

thank you!

**Comment by akitort** [comment]
> Please change the wine to - "Unstable-bh-gptk-1.0".
> 
> It should resolve the issues.

whats the best setting for m1 mac 8 gb ram sonoma 14.4.1

**Comment by Eclopia** [comment]
> > > > > > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > > > > > It should resolve the issues.
> > > > > > 
> > > > > > 
> > > > > > i had the same issue and i switched to that wine version, now the game wont even load
> > > > > 
> > > > > 
> > > > > What are Ur Mac specs?
> > > > 
> > > > 
> > > > Its a little old - macOS: 12.7.3 device- iMac (retina 5k, 27-inch, late 2015) processor- 4GHz Quad-Core Intel Core i7 RAM- 32GB
> > > 
> > > 
> > > That will explain why gptk didn't work, Game Porting Tool Kit is made for M series Macs, for ur Ram Config will recommend Crossover.
> > 
> > 
> > sorry I'm not a computer person, could you explain?
> 
> GPTK (Game Porting Tool Kit) is a Apple made version for M series (Arm Macs) the new [M1, M2, M3] chips, You are using a Intel Mac which Apple do not support for GPTK, For Intel Macs there is a Program Called "Crossover", Search "Crossover for mac" on google it should lead u to "Codeweavers" website, on their website you can download FREE Crossover Trial.
> 
> Steps to Use Crossover on Yaagl-
> 
> 1. Make sure to put Crossover in /Applications.
> 2. Open crossover once to let it finish its install.
> 3. Open Yaagl
> 4. Go to Yaagl Launcher settings > Wine > "should see Crossover as an option" > Switch to it.
> 5. Launch the game.
> 
> ~ feel free to ask more info if needed.

It still wont work, just blacks out 
At this point i might just switch to ipad and delete some stuff to free up storage there

**Comment by Sipperz** [comment]
Might be related to Molten vk, might have to try and change it to 1.2.6 version, or lower.

**Comment by Sipperz** [comment]
> > Please change the wine to - "Unstable-bh-gptk-1.0".
> 
> > 
> 
> > It should resolve the issues.
> 
> 
> 
> whats the best setting for m1 mac 8 gb ram sonoma 14.4.1

There is no "best settings"

Subsurface scattering and Dynamic character resolution, These two should be off for everyone.

Rest try changing settings mic then up -

Low to Medium,

**Comment by akitort** [comment]
> [<img alt="@akitort" width="40" height="40" src="https://avatars.githubusercontent.com/u/142984210?s=80&amp;v=4">](/akitort)
> 
> 
> #### Add a comment

wheres the dynamic character res ?

**Comment by Eclopia** [comment]
> > > > > > > > Please change the wine to - "Unstable-bh-gptk-1.0".
> > > > > > > > It should resolve the issues.
> > > > > > > 
> > > > > > > 
> > > > > > > i had the same issue and i switched to that wine version, now the game wont even load
> > > > > > 
> > > > > > 
> > > > > > What are Ur Mac specs?
> > > > > 
> > > > > 
> > > > > Its a little old - macOS: 12.7.3 device- iMac (retina 5k, 27-inch, late 2015) processor- 4GHz Quad-Core Intel Core i7 RAM- 32GB
> > > > 
> > > > 
> > > > That will explain why gptk didn't work, Game Porting Tool Kit is made for M series Macs, for ur Ram Config will recommend Crossover.
> > > 
> > > 
> > > sorry I'm not a computer person, could you explain?
> > 
> > 
> > GPTK (Game Porting Tool Kit) is a Apple made version for M series (Arm Macs) the news [M1, M2, M3] chips, You are using a Intel Mac which does Apple do not support for GPTK, For Intel Macs there is a Program Called "Crossover", Search "Crossover for mac" on google it should lead u to "Codeweavers" website, on their website you can download FREE Crossover Trial.
> > Steps to Use Crossover on Yaagl-
> > 
> > 1. Make sure to put Crossover in /Applications.
> > 2. Open crossover once to let it finish its install.
> > 3. Open Yaagl
> > 4. Go to Yaagl Launcher settings > Wine > "should see Crossover as an option" > Switch to it.
> > 5. Launch the game.
> 
> thank you!



> Might be related to Molten vk, might have to try and change it to 1.2.6 version, or lower.

ok will try

**Comment by Sipperz** [comment]
> > [<img alt="@akitort" width="40" height="40" src="https://avatars.githubusercontent.com/u/142984210?s=80&amp;v=4">](/akitort)
> > #### Add a comment
> 
> wheres the dynamic character res ?

In game settings

should be at the bottom or "unstable-bh-gptk-1.0" might not have that option for some reason.

**Comment by Eclopia** [comment]
> Might be related to Molten vk, might have to try and change it to 1.2.6 version, or lower.
apologies to keep this going so long, what exactly do i need to do? 
if this doesnt work ill just switch apps around on my other devices

**Comment by ScathachSkadi** [comment]
> > Might be related to Molten vk, might have to try and change it to 1.2.6 version, or lower.
> 
> apologies to keep this going so long, what exactly do i need to do? if this doesnt work ill just switch apps around on my other devices

Check your crossover version. Did you try opening the game multiple times? Are you sure your wine version is set to "crossover"? It should work right out of the box if you have installed the latest crossover provided on the site and have opened crossover at least once. 

Do consider choosing another platform since Fontaine and recent areas are quite glitchy in terms of graphics. Keep that in mind. GI will work amazing on your device if you bootcamp to Windows, however.

**Comment by Eclopia** [comment]
> > > Might be related to Molten vk, might have to try and change it to 1.2.6 version, or lower.
> > 
> > 
> > apologies to keep this going so long, what exactly do i need to do? if this doesnt work ill just switch apps around on my other devices
> 
> Check your crossover version. Did you try opening the game multiple times? Are you sure your wine version is set to "crossover"? It should work right out of the box if you have installed the latest crossover provided on the site and have opened crossover at least once.
> 
> Do consider choosing another platform since Fontaine and recent areas are quite glitchy in terms of graphics. Keep that in mind. GI will work amazing on your device if you bootcamp to Windows, however.

I'm trying to avoid bootcamp simply due to storage and I don't want it to run too slowly - I use my mac for editing. But i'll try running crossover again and see what happens, if not is there any other good ways to run the game or should I just use a different device?

**Comment by Sipperz** [comment]
If Crossover cannot assist, might have to use different device, or Use Bluestacks and emulate mobile version.

**Comment by Sipperz** [comment]
The Molten VK method I mentioned before is a very slim chance of Intel, as it can get unresponsive to load the game in certain regions, and then we cannot assist much other then using a different device to teleport to a less demanding area and re log in.

**Comment by ScathachSkadi** [comment]
> > > > Might be related to Molten vk, might have to try and change it to 1.2.6 version, or lower.
> > > 
> > > 
> > > apologies to keep this going so long, what exactly do i need to do? if this doesnt work ill just switch apps around on my other devices
> > 
> > 
> > Check your crossover version. Did you try opening the game multiple times? Are you sure your wine version is set to "crossover"? It should work right out of the box if you have installed the latest crossover provided on the site and have opened crossover at least once.
> > Do consider choosing another platform since Fontaine and recent areas are quite glitchy in terms of graphics. Keep that in mind. GI will work amazing on your device if you bootcamp to Windows, however.
> 
> I'm trying to avoid bootcamp simply due to storage and I don't want it to run too slowly - I use my mac for editing. But i'll try running crossover again and see what happens, if not is there any other good ways to run the game or should I just use a different device?

You see, it's not very ideal to run GI on mac in the first place. Since you would normally not edit while GI is open, why not install bootcamp and play there(it will work very very well) and boot back to MacOS after you are done?

**Comment by Eclopia** [comment]
> If Crossover cannot assist, might have to use different device, or Use Bluestacks and emulate mobile version.

Gi doesn't work on bluestacks but other games I play do so ill move some over and use a dif device, thank you everyone for trying to help though! <3

**Comment by Sipperz** [comment]
That is for the better, thank you for giving it a fair shot with trouble shooting, Happy gaming.
