### ISSUE TITLE
can anyone tell the best settings for Mac m1 (Mac OS sonoma)

### ISSUE THREAD

**Issue by PEACEBOI712** [yaagl/yet-another-anime-game-launcher#328]
can anyone tell the best settings for Mac OS Sonoma (M1 chip) and also tell which wine version to use for stability because I couldn't figure which setting to use have the game somewhat playable

**Comment by Sipperz** [comment]
> can anyone tell the best settings for Mac OS Sonoma (M1 chip) and also tell which wine version to use for stability because I couldn't figure which setting to use have the game somewhat playable

What are Ur Mac's Specs?

**Comment by PEACEBOI712** [comment]
Mac m1 
8gb ram 
os:sanoma 14.5

**Comment by PEACEBOI712** [comment]
storage 500gb

**Comment by PEACEBOI712** [comment]
anymore specs

**Comment by Sipperz** [comment]
"Unstable-bh-gptk-1.0" will be preferred wine.

Subsurface scattering, Dynamic character resolution, Turned off.

Rest medium to low for graphics.

**Comment by PEACEBOI712** [comment]
ok

**Comment by PEACEBOI712** [comment]
low or lowest??

**Comment by Sipperz** [comment]
> low or lowest??
> 
> 

Low to medium, select and run around see what combination u like.

**Comment by PEACEBOI712** [comment]
ok
