### ISSUE TITLE
不断报错

### ISSUE THREAD

**Issue by doudouyun87** [yaagl/yet-another-anime-game-launcher#330]
Couldn't get first exception for process 0118 Z:\Volumes\SamsungT5\yuanshenyaagl\YuanShen.exe.
No backtrace available
Modules:
Module	Address					Debug info	Name (32 modules, 54 for wow64 not listed)
ELF	0000000000000000-000000000000b000	Deferred        <wine-loader>
ELF	0000000002e11000-0000000002e15000	Deferred        <wine-loader>
ELF	0000000002eea000-0000000002fa2000	Deferred        ntdll.so
PE	00000000685ca000-00000000685fa000	Deferred        libpng16.16.dylib
ELF	00000000686e0000-00000000686ec000	Deferred        ws2_32.so
ELF	00000000686fa000-00000000688ae000	Deferred        win32u.so
PE	0000000068a94000-0000000068b34000	Deferred        libfreetype.6.dylib
ELF	000000006ab89000-000000006ab95000	Deferred        dnsapi.so
ELF	000000006ab9e000-000000006abae000	Deferred        bcrypt.so
ELF	000000006abc2000-000000006abce000	Deferred        crypt32.so
PE	000000006abe5000-000000006ac09000	Deferred        libintl.8.dylib
PE	000000006ac35000-000000006ac51000	Deferred        libtasn1.6.dylib
ELF	000000006ac84000-000000006ad84000	Deferred        opengl32.so
PE	000000006aedd000-000000006af19000	Deferred        libidn2.0.dylib
PE	000000006af7c000-000000006afcc000	Deferred        libnettle.8.8.dylib
PE	000000006b020000-000000006b068000	Deferred        libhogweed.6.8.dylib
PE	000000006b0b2000-000000006b28e000	Deferred        libgnutls.30.dylib
PE	000000006b4a0000-000000006b5e4000	Deferred        libp11-kit.0.dylib
PE	000000006b827000-000000006b89b000	Deferred        libgmp.10.dylib
PE	000000006b971000-000000006bb2d000	Deferred        libunistring.5.dylib
PE	000000006be1f000-000000006be33000	Deferred        com.apple.appkit
ELF	000000006be4e000-000000006beda000	Deferred        winemac.so
ELF	000000006d9e0000-000000006d9f0000	Deferred        secur32.so
PE	000000006e153000-000000006e168000	Deferred        libobjc-trampolines.dylib
PE	000000006eaed000-000000006eb09000	Deferred        libd3dshared.dylib
PE	000000006eb48000-000000006eb7c000	Deferred        libdxccontainer.dylib
ELF	000000006ed11000-000000006ed1d000	Deferred        winspool.so
PE	0000000073970000-0000000073d8c000	Deferred        d3dmetal
PE	000000007fff0000-00000000827e8000	Deferred        libmetalirconverter.dylib
PE	00007ff8090eb000-00007ff809126000	Deferred        libsystem_kernel.dylib
PE	00007ff809126000-00007ff809132000	Deferred        libsystem_pthread.dylib
PE	00007ff809157000-00007ff809162000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	0000009c    0     wine_rpcrt4_io
	000000b4    0     wine_rpcrt4_io
	000000c8    0     
	000000e0    0     wine_rpcrt4_io
	00000258    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000c0    0     
00000068 winedevice.exe
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	0000007c    0     
	00000080    0     
	00000094    0     
	00000098    0     
00000084 explorer.exe
	00000088    0     
	000000cc    0     
	000000d0    0     wine_rpcrt4_server
0000008c plugplay.exe
	00000090    0     
	000000a0    0     
	000000a4    0     wine_sechost_service
	000000a8    0     wine_rpcrt4_server
	000001fc    0     wine_rpcrt4_io
	00000200    0     wine_threadpool_worker
000000ac svchost.exe
	000000b0    0     
	000000b8    0     
	000000bc    0     wine_sechost_service
000000d8 rpcss.exe
	000000dc    0     
	000000e8    0     
	000000ec    0     wine_sechost_service
	000000f0    0     wine_rpcrt4_server
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_io
00000100 cmd.exe
	00000104    0     
00000118 (D) Z:\Volumes\SamsungT5\yuanshenyaagl\YuanShen.exe
	000002b0    0     
000002a8 conhost.exe
	000002ac    0     
System information:
    Wine build: wine-8.17
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Darwin
    Host version: 23.5.0
[backtrace.txt](https://github.com/yaagl/yet-another-anime-game-launcher/files/15297117/backtrace.txt)

**Comment by Zqanx** [comment]
外置硬盘需要格式化为 APFS。

**Comment by Sipperz** [comment]
Closing issue because no response, Feel free to re-open the issue if required.
