### ISSUE TITLE
Minimises itself when tabbing out to another tab.

### ISSUE THREAD

**Issue by srkzx0** [yaagl/yet-another-anime-game-launcher#332]
**Describe the bug**
When I alt + tab (command +tab) in this case or any method to switch to another tab, the application minimises itself. It is extremely annoying especially for multitasking or gaming in general. 

**Screenshots**
N/A

**System Information (please complete the following information):**
 - macOS: [14.4.1 Sonama]
 - Device: [e.g. MacbookAir 13.3inch 2020]
 - CPU: [Apple M1]
 - Dedicated GPU (if any): [N/A]
 - RAM: [8G]

**Additional context**
It minimises the application to the dock, and you have to manually click it before its pops back up into your window.

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Sipperz** [comment]
That is the default behavior not an issue.

**Comment by srkzx0** [comment]
is there a way to prevent this from happening though? Thanks

**Comment by Sipperz** [comment]
No, as it is the Default behaviour, Maybe in the future, but no promises.

**Comment by srkzx0** [comment]
Ahh alright, thanks again!
