### ISSUE TITLE
报错 无法启动

### ISSUE THREAD

**Issue by gaohecheng1** [yaagl/yet-another-anime-game-launcher#333]
报错，无法启动

<img width="1920" alt="截屏2024-05-15 21 06 22" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/134496553/e4aecd44-0eaa-4bc7-a08d-d00d9d2d1138">

**System Information (please complete the following information):**
 - macOS: [ 14.1.1 Sonoma]
 - Device: [ MacbookPro 16inch M3Max ]
 - CPU: [M3Max ]

 - RAM: [e.g. 36G ]

**Logs (if any)**

Couldn't get first exception for process 0118 Z:\Users\gaoheyuan\genshin\YuanShen.exe.
No backtrace available
Modules:
Module	Address					Debug info	Name (24 modules, 47 for wow64 not listed)
ELF	0000000000000000-0000000000010000	Deferred        <wine-loader>
ELF	0000000002b6d000-0000000002b71000	Deferred        <wine-loader>
ELF	0000000002c46000-0000000002cfe000	Deferred        ntdll.so
PE	00000000685ca000-00000000685fa000	Deferred        libpng16.16.dylib
ELF	00000000686d8000-00000000686e4000	Deferred        ws2_32.so
ELF	00000000686fa000-00000000688ae000	Deferred        win32u.so
PE	0000000068a94000-0000000068b34000	Deferred        libfreetype.6.dylib
ELF	000000006ac11000-000000006ac1d000	Deferred        dnsapi.so
ELF	000000006ac26000-000000006ac36000	Deferred        bcrypt.so
ELF	000000006ac4a000-000000006ac56000	Deferred        crypt32.so
PE	000000006ac6d000-000000006ac91000	Deferred        libintl.8.dylib
PE	000000006acbd000-000000006acd9000	Deferred        libtasn1.6.dylib
ELF	000000006ad0c000-000000006ae0c000	Deferred        opengl32.so
PE	000000006af65000-000000006afa1000	Deferred        libidn2.0.dylib
PE	000000006b004000-000000006b054000	Deferred        libnettle.8.8.dylib
PE	000000006b0a8000-000000006b0f0000	Deferred        libhogweed.6.8.dylib
PE	000000006b13a000-000000006b316000	Deferred        libgnutls.30.dylib
PE	000000006b528000-000000006b66c000	Deferred        libp11-kit.0.dylib
PE	000000006b8af000-000000006b923000	Deferred        libgmp.10.dylib
PE	000000006b9f9000-000000006bbb5000	Deferred        libunistring.5.dylib
ELF	000000006bed6000-000000006bf62000	Deferred        winemac.so
PE	00007ff813bbb000-00007ff813bf6000	Deferred        libsystem_kernel.dylib
PE	00007ff813bf6000-00007ff813c02000	Deferred        libsystem_pthread.dylib
PE	00007ff813c27000-00007ff813c32000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	000000a8    0     wine_rpcrt4_io
	000000c4    0     wine_rpcrt4_io
	000000d8    0     
	000000e4    0     wine_rpcrt4_io
	00000188    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000d0    0     
00000068 winedevice.exe
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	0000007c    0     
	00000080    0     
	00000094    0     
	00000098    0     
00000084 explorer.exe
	00000088    0     
	0000009c    0     
	000000a0    0     wine_rpcrt4_server
0000008c plugplay.exe
	00000090    0     
	000000b0    0     
	000000b4    0     wine_sechost_service
	000000b8    0     wine_rpcrt4_server
000000bc svchost.exe
	000000c0    0     
	000000c8    0     
	000000cc    0     wine_sechost_service
000000dc rpcss.exe
	000000e0    0     
	000000e8    0     
	000000ec    0     wine_sechost_service
	000000f0    0     wine_rpcrt4_server
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_io
00000100 cmd.exe
	00000104    0     
00000118 (D) Z:\Users\gaoheyuan\genshin\YuanShen.exe
	0000020c    0     
000001cc conhost.exe
	000001d0    0     
System information:
    Wine build: wine-8.17
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Darwin
    Host version: 23.4.0

**Comment by gaohecheng1** [comment]
用的GPTK

**Comment by ScathachSkadi** [comment]
Update to 14.4 or up
