### ISSUE TITLE
game crashed 打不开，报错

### ISSUE THREAD

**Issue by gaohecheng1** [yaagl/yet-another-anime-game-launcher#334]
when I start the game ，the game crash

<img width="1920" alt="截屏2024-05-15 23 10 22" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/134496553/abbe8aee-db58-4859-878b-0ac6cb053b0d">

**System Information (please complete the following information):**
 - macOS: [ 14.5 Sonoma （14.4.1也不好使）]
 - Device: [m3Max MBP 16寸 ]
 - CPU: [M3Max ]
 - RAM: [36G  ]
 - Useing GPTK

Couldn't get first exception for process 0118 Z:\Users\gaoheyuan\genshin\YuanShen.exe.
No backtrace available
Modules:
Module	Address					Debug info	Name (24 modules, 47 for wow64 not listed)
ELF	0000000000000000-0000000000010000	Deferred        <wine-loader>
ELF	000000000082d000-0000000000831000	Deferred        <wine-loader>
ELF	0000000000906000-00000000009be000	Deferred        ntdll.so
PE	00000000685ca000-00000000685fa000	Deferred        libpng16.16.dylib
ELF	00000000686d8000-00000000686e4000	Deferred        ws2_32.so
ELF	00000000686fa000-00000000688ae000	Deferred        win32u.so
PE	0000000068a94000-0000000068b34000	Deferred        libfreetype.6.dylib
ELF	000000006ac11000-000000006ac1d000	Deferred        dnsapi.so
ELF	000000006ac26000-000000006ac36000	Deferred        bcrypt.so
ELF	000000006ac4a000-000000006ac56000	Deferred        crypt32.so
PE	000000006ac6d000-000000006ac91000	Deferred        libintl.8.dylib
PE	000000006acbd000-000000006acd9000	Deferred        libtasn1.6.dylib
ELF	000000006ad0c000-000000006ae0c000	Deferred        opengl32.so
PE	000000006af65000-000000006afa1000	Deferred        libidn2.0.dylib
PE	000000006b004000-000000006b054000	Deferred        libnettle.8.8.dylib
PE	000000006b0a8000-000000006b0f0000	Deferred        libhogweed.6.8.dylib
PE	000000006b13a000-000000006b316000	Deferred        libgnutls.30.dylib
PE	000000006b528000-000000006b66c000	Deferred        libp11-kit.0.dylib
PE	000000006b8af000-000000006b923000	Deferred        libgmp.10.dylib
PE	000000006b9f9000-000000006bbb5000	Deferred        libunistring.5.dylib
ELF	000000006bfd6000-000000006c062000	Deferred        winemac.so
PE	00007ff80981b000-00007ff809856000	Deferred        libsystem_kernel.dylib
PE	00007ff809856000-00007ff809862000	Deferred        libsystem_pthread.dylib
PE	00007ff809887000-00007ff809892000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	000000a8    0     wine_rpcrt4_io
	000000c4    0     wine_rpcrt4_io
	000000d8    0     
	000000e4    0     wine_rpcrt4_io
	00000188    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000d0    0     
00000068 winedevice.exe
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	0000007c    0     
	00000080    0     
	0000008c    0     
	00000090    0     
00000084 explorer.exe
	00000088    0     
	0000009c    0     
	000000a0    0     wine_rpcrt4_server
00000094 plugplay.exe
	00000098    0     
	000000b0    0     
	000000b4    0     wine_sechost_service
	000000b8    0     wine_rpcrt4_server
000000bc svchost.exe
	000000c0    0     
	000000c8    0     
	000000cc    0     wine_sechost_service
000000dc rpcss.exe
	000000e0    0     
	000000e8    0     
	000000ec    0     wine_sechost_service
	000000f0    0     wine_rpcrt4_server
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_io
00000100 cmd.exe
	00000104    0     
00000118 (D) Z:\Users\gaoheyuan\genshin\YuanShen.exe
	0000020c    0 <== 
000001c4 conhost.exe
	000001c8    0     
System information:
    Wine build: wine-8.17
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Darwin
    Host version: 23.5.0

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
[game_1715769397577.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15323570/game_1715769397577.log)

**Comment by Sipperz** [comment]
Do u have Rosetta 2 installed?

Type "softwareupdate --install-rosetta"

In Terminal.

**Comment by gaohecheng1** [comment]
> Do u have Rosetta 2 installed?
> 
> Type "softwareupdate --install-rosetta"
> 
> In Terminal.

of course i installed ，the game just suddenly cant run，有一天玩游戏的时候突然提示系统环境异常，请重启机器，然后就打不开了，报错，当时系统版本是14.4.1 随后我更新了14.5，还是一样打不开

**Comment by Zqanx** [comment]
这个问题可能 workaround 3 能解决（yaagl 设置里）。然后试试用 crossover 的 wine。具体方法在 wiki 里的常见问题解答里有。

**Comment by gaohecheng1** [comment]
> 这个问题可能 workaround 3 能解决（yaagl 设置里）。然后试试用 crossover 的 wine。具体方法在 wiki 里的常见问题解答里有。

试过了，不太行，包括重装ys和yaagl，删掉application support

**Comment by Zqanx** [comment]
你的 crossover 是什么版本？然后还可以试试其他 wine，包括 gptk。可以通过 whisky 安装。

**Comment by Sipperz** [comment]
Closing issue because no response, feel free to re-open the issue if needed.
