### ISSUE TITLE
cant launch game

### ISSUE THREAD

**Issue by CarlosWan** [yaagl/yet-another-anime-game-launcher#335]
**Describe the bug**

**System Information (please complete the following information):**
 - macOS: 14.5 
 - Device: MacbookPro 16inch
 - CPU: M3 Pro
 - RAM: 36G

**Logs (if any)**
166889.893:00e4:err:service:validate_context_handle Access denied - handle created with access 34, needed 10000
166890.194:0144:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\\windows\\system32\\HoYoKProtect.sys") not found
166890.194:0144:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\HoYoProtect": c0000142
010c: thread_get_state failed on Apple Silicon - faking zero debug registers
0110: thread_get_state failed on Apple Silicon - faking zero debug registers
011c: thread_get_state failed on Apple Silicon - faking zero debug registers
0120: thread_get_state failed on Apple Silicon - faking zero debug registers
0128: thread_get_state failed on Apple Silicon - faking zero debug registers
012c: thread_get_state failed on Apple Silicon - faking zero debug registers
0160: thread_get_state failed on Apple Silicon - faking zero debug registers
0164: thread_get_state failed on Apple Silicon - faking zero debug registers
0168: thread_get_state failed on Apple Silicon - faking zero debug registers
016c: thread_get_state failed on Apple Silicon - faking zero debug registers
0170: thread_get_state failed on Apple Silicon - faking zero debug registers

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
[game_1715825914869.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15328963/game_1715825914869.log)

**Comment by gaohecheng1** [comment]
14.1.1前天晚上突然就不好使了，更新14.5好不好使

**Comment by gaohecheng1** [comment]
用GPTK试试，能不能进去
use GPTK wine doesn't work on my computer too

**Comment by Sipperz** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **System Information (please complete the following information):**
> 
> * macOS: 14.5
> * Device: MacbookPro 16inch
> * CPU: M3 Pro
> * RAM: 36G
> 
> **Logs (if any)** 166889.893:00e4:err:service:validate_context_handle Access denied - handle created with access 34, needed 10000 166890.194:0144:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\windows\system32\HoYoKProtect.sys") not found 166890.194:0144:err:ntoskrnl:ZwLoadDriver failed to create driver L"\Registry\Machine\System\CurrentControlSet\Services\HoYoProtect": c0000142 010c: thread_get_state failed on Apple Silicon - faking zero debug registers 0110: thread_get_state failed on Apple Silicon - faking zero debug registers 011c: thread_get_state failed on Apple Silicon - faking zero debug registers 0120: thread_get_state failed on Apple Silicon - faking zero debug registers 0128: thread_get_state failed on Apple Silicon - faking zero debug registers 012c: thread_get_state failed on Apple Silicon - faking zero debug registers 0160: thread_get_state failed on Apple Silicon - faking zero debug registers 0164: thread_get_state failed on Apple Silicon - faking zero debug registers 0168: thread_get_state failed on Apple Silicon - faking zero debug registers 016c: thread_get_state failed on Apple Silicon - faking zero debug registers 0170: thread_get_state failed on Apple Silicon - faking zero debug registers
> 
> > If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
> > [game_1715825914869.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15328963/game_1715825914869.log)

is the game instantly disappearing when you Launch it?

**Comment by CarlosWan** [comment]
> I am going to assume don't have Rosetta 2 installed here as well
> 
> softwareupdate --install-rosetta
> 
> ^ Type this in Terminal.

rosetta 2 had been installed before, it could be something else.

**Comment by CarlosWan** [comment]
> > **Describe the bug** A clear and concise description of what the bug is.
> > **System Information (please complete the following information):**
> > 
> > * macOS: 14.5
> > * Device: MacbookPro 16inch
> > * CPU: M3 Pro
> > * RAM: 36G
> > 
> > **Logs (if any)** 166889.893:00e4:err:service:validate_context_handle Access denied - handle created with access 34, needed 10000 166890.194:0144:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\windows\system32\HoYoKProtect.sys") not found 166890.194:0144:err:ntoskrnl:ZwLoadDriver failed to create driver L"\Registry\Machine\System\CurrentControlSet\Services\HoYoProtect": c0000142 010c: thread_get_state failed on Apple Silicon - faking zero debug registers 0110: thread_get_state failed on Apple Silicon - faking zero debug registers 011c: thread_get_state failed on Apple Silicon - faking zero debug registers 0120: thread_get_state failed on Apple Silicon - faking zero debug registers 0128: thread_get_state failed on Apple Silicon - faking zero debug registers 012c: thread_get_state failed on Apple Silicon - faking zero debug registers 0160: thread_get_state failed on Apple Silicon - faking zero debug registers 0164: thread_get_state failed on Apple Silicon - faking zero debug registers 0168: thread_get_state failed on Apple Silicon - faking zero debug registers 016c: thread_get_state failed on Apple Silicon - faking zero debug registers 0170: thread_get_state failed on Apple Silicon - faking zero debug registers
> > > If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
> > > [game_1715825914869.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15328963/game_1715825914869.log)
> 
> is the game instantly disappearing when you Launch it?

No, Not even entering the game, just loading
<img width="1688" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/42070581/2c9ee152-b7e9-401d-aa70-9384029848bd">

**Comment by gaohecheng1** [comment]
> > > **Describe the bug** A clear and concise description of what the bug is.
> > > **System Information (please complete the following information):**
> > > 
> > > * macOS: 14.5
> > > * Device: MacbookPro 16inch
> > > * CPU: M3 Pro
> > > * RAM: 36G
> > > 
> > > **Logs (if any)** 166889.893:00e4:err:service:validate_context_handle Access denied - handle created with access 34, needed 10000 166890.194:0144:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\windows\system32\HoYoKProtect.sys") not found 166890.194:0144:err:ntoskrnl:ZwLoadDriver failed to create driver L"\Registry\Machine\System\CurrentControlSet\Services\HoYoProtect": c0000142 010c: thread_get_state failed on Apple Silicon - faking zero debug registers 0110: thread_get_state failed on Apple Silicon - faking zero debug registers 011c: thread_get_state failed on Apple Silicon - faking zero debug registers 0120: thread_get_state failed on Apple Silicon - faking zero debug registers 0128: thread_get_state failed on Apple Silicon - faking zero debug registers 012c: thread_get_state failed on Apple Silicon - faking zero debug registers 0160: thread_get_state failed on Apple Silicon - faking zero debug registers 0164: thread_get_state failed on Apple Silicon - faking zero debug registers 0168: thread_get_state failed on Apple Silicon - faking zero debug registers 016c: thread_get_state failed on Apple Silicon - faking zero debug registers 0170: thread_get_state failed on Apple Silicon - faking zero debug registers
> > > > If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
> > > > [game_1715825914869.log](https://github.com/yaagl/yet-another-anime-game-launcher/files/15328963/game_1715825914869.log)
> > 
> > 
> > is the game instantly disappearing when you Launch it?
> 
> No, Not even entering the game, just loading <img alt="image" width="1688" src="https://private-user-images.githubusercontent.com/42070581/331433411-2c9ee152-b7e9-401d-aa70-9384029848bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjU1ODIsIm5iZiI6MTcxNTkyNTI4MiwicGF0aCI6Ii80MjA3MDU4MS8zMzE0MzM0MTEtMmM5ZWUxNTItYjdlOS00MDFkLWFhNzAtOTM4NDAyOTg0OGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDA1NTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YzFlYzJlNjRkNjFkZDYxYjhmZjY2OWVjZGRhODI5YmFlMzY4Y2Q4MDA5YjJiYmRhZGE5Y2ZhN2I1M2VmYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.miTa8YudDQZo8Hy5tZt0xrCOJneY4kf1C9rMFGYn-SQ">

try to use unstable GPTK

**Comment by Sipperz** [comment]
For anything above 16 gb RAM

We recommend crossover wine.

**Comment by Ryno666** [comment]
My 14.5 Sonoma also have the same problem. I cant enter the game just after appearring the infomation you have shown

**Comment by Sipperz** [comment]
@CarlosWan Sorry for late reply, Carlos Your error seems to be missing game files, which should get resolved, with the new version. If you didn't try already do give it a try.

**Comment by Ryno666** [comment]
谢谢，您的邮件我已收到！

**Comment by Ryno666** [comment]
Sorry I didn’t get what do you mean exactly. The new version means the Yaagl or the new version of  Genshin. I tried both but it does not work at all. So Im still bothering.

**Comment by Sipperz** [comment]
@Ryno666 do u have discord? so we can help u on the spot, for some reason Github is not sending me alerts when someone is replying.

**Comment by Sipperz** [comment]
Closing issue because no response was given, feel free to re-open if required.

**Comment by Ryno666** [comment]
谢谢，您的邮件我已收到！
