### ISSUE TITLE
Keyboard and mouse is not working 

### ISSUE THREAD

**Issue by MisterPur** [yaagl/yet-another-anime-game-launcher#336]
The keyboard is complete unresponsive. On the mouse only works the left and right Botton. I also can't alt+tab. the only way is to get of the game is to us press cmd multiple times. this started happen after I plug a keyboard , mouse and a monitor. and now not even the Mac keyboard is not responding

**System Information:**
 - macOS: 14.4.1
 - Device: MacBook Air 2020 
 - CPU: Apple M1
 - RAM: 8

**Comment by MisterPur** [comment]
ok it work now. but idk why.

**Comment by MisterPur** [comment]
it happening again

**Comment by ScathachSkadi** [comment]
Keyboard language?

**Comment by Sipperz** [comment]
Closing issue because no response was given to provide more info on the issue, feel free to re-open if required.
