### ISSUE TITLE
weird glitch with the NPCs

### ISSUE THREAD

**Issue by Soliturd** [yaagl/yet-another-anime-game-launcher#337]
Describe the bug
if i walk close to some specific npcs, they do this. i cant tell if this is YAAGL or genshin but man is it weird. i cannot interact with characters when this occurs

**Screenshots**
<img width="1440" alt="Screenshot 2024-05-18 at 4 37 09 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168102066/d556e830-c48c-4486-b13d-ff3ef88ed332">
<img width="167" alt="Screenshot 2024-05-18 at 4 37 13 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168102066/1902292e-8854-43f9-81d2-5a2237d4de02">
<img width="453" alt="Screenshot 2024-05-18 at 5 10 23 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168102066/59f751f2-534b-4038-8f4a-f69fe5589a8c">

**System Information**

macOS: [Sonoma Version 14.4.1]
Device: [MacBook Air 13" 2020]
CPU: [Apple M1 (i cant find anymore info on the cpu)]
RAM: [8GB]

**Additional context**
cant find anything on this

**Logs (if any)**

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory (Idk how to do this)

**Comment by Zqanx** [comment]
Turn off dynamic character resolution (in-game settings)

**Comment by Soliturd** [comment]
> Turn off dynamic character resolution (in-game settings)

worked! thanks!
