### ISSUE TITLE
"ReferenceError: Can't find variable: BigInt"

### ISSUE THREAD

**Issue by AlolaCaden** [yaagl/yet-another-anime-game-launcher#338]
i try and open yaagl for the first time, only to see this pop up.

![Screen Shot 2024-05-20 at 3 31 39 pm](https://github.com/yaagl/yet-another-anime-game-launcher/assets/116863090/eaddc5f3-c39e-408a-b3fb-5be3f22cf622)

Info:
 - macOS: 10.15.7, MacOs Catalina
 - Device: 21.5 inch, 2013 Late iMac
 - CPU: 2.9 GHz Quad-Core Intel Core i5
 - Dedicated GPU: NVIDIA GeForce GT 750M 1 GB
 - RAM: 16 GB 1600 MHz DDR3

**Comment by 3Shain** [comment]
> macOS: 10.15.7

No for intel mac this is too old.
