### ISSUE TITLE
Characters and other graphics don't load/.

### ISSUE THREAD

**Issue by soulaphic** [yaagl/yet-another-anime-game-launcher#340]
During cutscenes, characters don't load properly. Additionally, chests aren't visible in the world and can only be identified if they are locked inside of a red ring.
<img width="741" alt="Screenshot 2024-05-24 at 11 34 53 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/170783379/41666a1d-2901-477b-ba32-38693fed1509">
<img width="722" alt="Screenshot 2024-05-24 at 11 35 41 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/170783379/c13bbca5-4ee8-46d4-bacc-e630eae3d5f3">
<img width="764" alt="Screenshot 2024-05-24 at 11 36 30 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/170783379/d193a6a8-5691-49ad-9cfa-95f29ff98c4d">

**Comment by mynameisjoe01928** [comment]
i have the same problem

Tested everysingle available wine version and the whisky wine, none of them work even with character resolution turned off

**Comment by Menelkir** [comment]
Disable Dynamic Character Resolution.
