### ISSUE TITLE
HSR Performance Issues

### ISSUE THREAD

**Issue by 1146839821** [yaagl/yet-another-anime-game-launcher#341]
Hi~
Recently, I used a method to make HSR run well on Apple Silicon Mac.
The general idea is to use 3Shain's unstable bh wine-1.2 and run hsr using jadeite first
then,Toggle D3DMetal in CrossOver and relaunch the game again using command.
[https://codeberg.org/mkrsym1/jadeite/issues/39](url)

Perhaps you can refer to the above methods for optimization.
Thanks.

**Comment by ATuStory** [comment]
![Uploading Ảnh màn hình 2024-06-22 lúc 11.49.45.png…]
how to fix graphic, please. thanks very much

**Comment by ATuStory** [comment]
![Ảnh màn hình 2024-06-22 lúc 11 49 45](https://github.com/yaagl/yet-another-anime-game-launcher/assets/173487964/3b6f07ec-a935-4e68-8d92-e49447f74a40)
how to fix graphic, please. thanks very much

**Comment by Sipperz** [comment]
> ![Ảnh màn hình 2024-06-22 lúc 11 49 45](https://github.com/yaagl/yet-another-anime-game-launcher/assets/173487964/3b6f07ec-a935-4e68-8d92-e49447f74a40)
> 
> how to fix graphic, please. thanks very much

Which part of graphics needs fixing? Describe it a bit more.

**Comment by ATuStory** [comment]
How to delete lines behind characters in the background

**Comment by ATuStory** [comment]
> > ![Ảnh màn hình 2024-06-22 lúc 11 49 45](https://private-user-images.githubusercontent.com/173487964/341934553-3b6f07ec-a935-4e68-8d92-e49447f74a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDM5ODMsIm5iZiI6MTcxOTA0MzY4MywicGF0aCI6Ii8xNzM0ODc5NjQvMzQxOTM0NTUzLTNiNmYwN2VjLWE5MzUtNGU2OC04ZDkyLWU0OTQ0N2Y3NGE0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQwODA4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDlhODM1YjQwZmVmMWRlM2M1ODA4MjU1MTdiMjEzZjIzYTQyZjkxYTQ0NjJiNDVlYTcyZGJkZTA0Y2U0MmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jKSLeWO-GhnD1mRIffTu_HjC1-yru8fpK8q87ayE16M)
> > how to fix graphic, please. thanks very much
> 
> Which part of graphics needs fixing? Describe it a bit more.
How to delete lines behind characters in the background

**Comment by ATuStory** [comment]
> Hi~ Recently, I used a method to make HSR run well on Apple Silicon Mac. The general idea is to use 3Shain's unstable bh wine-1.2 and run hsr using jadeite first then,Toggle D3DMetal in CrossOver and relaunch the game again using command. [https://codeberg.org/mkrsym1/jadeite/issues/39](url)
> 
> Perhaps you can refer to the above methods for optimization. Thanks.

can you share tips video?

**Comment by 1146839821** [comment]
> > Hi~ Recently, I used a method to make HSR run well on Apple Silicon Mac. The general idea is to use 3Shain's unstable bh wine-1.2 and run hsr using jadeite first then,Toggle D3DMetal in CrossOver and relaunch the game again using command. [https://codeberg.org/mkrsym1/jadeite/issues/39](url)
> > Perhaps you can refer to the above methods for optimization. Thanks.
> 
> can you share tips video?

This is not a one-size-fits-all solution. I made some modifications for yaagl. You can download my release version if you want to test it.
[https://github.com/1146839821/yet-another-anime-game-launcher/releases](url)

1. The default wine will be replaced with  **wine7.7-gptk**  
2. Please delete yaagl data completely before use(/Users/your name/Library/Application Support/Yaagl HSR)
[https://drive.google.com/file/d/11xq3lIGEPoAVeyHQgV8rJIfBXYHisKZY/view?usp=drive_link](url)
