### ISSUE TITLE
Characters do not load even when Dynamic Character Resolution is turned off

### ISSUE THREAD

**Issue by mynameisjoe01928** [yaagl/yet-another-anime-game-launcher#342]
**Describe the bug**
I've known about the Dynamic Character bug, but this is my first time encountering it. Ever since I've switched to the New Yaagl, and the new wine. I've tried every other wine prefix and whisky.

**Screenshots**
<img width="2240" alt="Screenshot 2024-05-25 at 8 45 54 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/21438c21-ad95-4cbd-8316-dc54ccb9dee5">
<img width="2240" alt="Screenshot 2024-05-25 at 8 45 58 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/b2c63ddc-c4d0-4d3b-bf60-fa032253e463">
<img width="2240" alt="Screenshot 2024-05-25 at 8 54 05 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/8d380f86-786f-4f06-87b8-ad78a5af0307">
<img width="2240" alt="Screenshot 2024-05-25 at 8 54 07 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/65806f0e-68a2-4d8f-a2c3-73548a35373f">
<img width="2240" alt="Screenshot 2024-05-25 at 8 56 31 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/f3f9eb2e-582b-4ecd-a48b-89456dcddb76">
<img width="2240" alt="Screenshot 2024-05-25 at 8 56 33 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/39995c3c-6bb7-4851-a33d-c3b6be77c6f2">
<img width="2240" alt="Screenshot 2024-05-25 at 8 56 35 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/7f8c3358-502b-48fc-9a9c-e3d28d4203e5">
<img width="2240" alt="Screenshot 2024-05-25 at 8 56 38 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/f15b4463-55b3-420f-b4b8-24cf24f4507f">
<img width="2240" alt="Screenshot 2024-05-25 at 8 56 39 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/e1b22a31-d1c3-4980-90bc-bfab7ea7f902">
<img width="2240" alt="Screenshot 2024-05-25 at 8 59 10 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/ca53cec0-7c0f-480f-addc-46cab74f5876">
<img width="2240" alt="Screenshot 2024-05-25 at 8 59 15 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/c5f54652-4535-4f34-ba1a-1a8ba6518376">
<img width="2240" alt="Screenshot 2024-05-25 at 9 00 23 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/f52e71dc-c880-4bb8-bd18-55e3cd2f5ca6">
<img width="2240" alt="Screenshot 2024-05-25 at 9 00 30 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/e09c195d-2926-4622-87a5-83e1bc09b4ec">
<img width="2240" alt="Screenshot 2024-05-25 at 8 45 21 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/163480596/5b171b8b-8bc9-48f9-bcd0-1d979a6470e1">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.5
 - Device: 2021 M1 24-inch iMac
 - CPU: M1 
 - Dedicated GPU (if any): N/A
 - RAM: 8GB

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Zqanx** [comment]
Switch back to older yaagl if non of the new wines work for you.

**Comment by mynameisjoe01928** [comment]
Thanks!
