### ISSUE TITLE
hsr使用crossover打开时 无法进入

### ISSUE THREAD

**Issue by martin-han** [yaagl/yet-another-anime-game-launcher#343]
**Describe the bug**
hsr使用crossover启动时  刚刚显示“__ __(没看清)补丁” 就回到开始游戏页面 即未能打开游戏  确保已经完成了提示的最新版MoltenVK
 在gl完全没有显示crossover选项 并已确保非中文版crossover

**System Information (please complete the following information):**
 - macOS: [e.g. 14.4]
 - Device: [e.g. MacbookPro 14inch 2021 ]
 - CPU: [e.g. Apple M1pro ]
 - RAM: [e.g. 16G ]
crossover版本是24.0.3

**Comment by 3Shain** [comment]
crossover is not supported for HSR yet (workaround exists but not implemented atm). Please use `v9.2-mingw`.
