### ISSUE TITLE
Error when trying to launch HSR OS

### ISSUE THREAD

**Issue by soulaphic** [yaagl/yet-another-anime-game-launcher#344]
This error occurs when I click "launch game" after downloading all of the game files.
<img width="586" alt="Screenshot 2024-05-25 at 12 15 32 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/170783379/1b64b3e3-f2e8-4057-80f9-528dbf349e7d">

**Comment by 3Shain** [comment]
Please show me a screenshot of your game directory.

**Comment by Sipperz** [comment]
Closing issue because of no response, feel free to re-open if required.
