### ISSUE TITLE
Chests not showing

### ISSUE THREAD

**Issue by soulaphic** [yaagl/yet-another-anime-game-launcher#345]
Chests do not show up. I've attached my graphics settings as well.
<img width="515" alt="Screenshot 2024-05-25 at 8 03 35 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/170783379/3507e67e-b168-4a6b-8c39-38d346082436">
<img width="964" alt="Screenshot 2024-05-25 at 8 04 48 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/170783379/dfdb9034-7c4d-4e2c-a794-0c1fed84cec4">
<img width="955" alt="Screenshot 2024-05-25 at 8 04 55 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/170783379/285d1bd3-79cc-4fa0-bec8-2d62244473bf">

**Comment by 3Shain** [comment]
.... list specs and versions!

**Comment by Sipperz** [comment]
Closing because no further response, feel free to re-open if further assistance is required.
