### ISSUE TITLE
Is it possible to roll back?

### ISSUE THREAD

**Issue by Kevin-Haus24** [yaagl/yet-another-anime-game-launcher#346]
I played until the release of 1.11 perfectly on m1 without departures and problems (even the fps was stable). I tested different versions of wine and found wine unstable v1.0. Only everything worked well on her. And now she's gone. I tested all 3 new wine distributions and not all textures everywhere (half of the NPS heads fly, some weapons are not loaded, and benet is a joke at all, all his textures have moved out and he looks like a monster from horrors).

It's all about the fact that now only rolling back to 1.10 or returning wine unstable v1.0 will help me. :(

Maybe I'm not the only one who has faced the same problem.

**Comment by 3Shain** [comment]
Will add some of old wine distribution back later. To rollback you can uninstall yaagl and download 0.1.10 manually to replace the current one, then ignore the update notification.

**Comment by hwang1607** [comment]
v9.2-mingw is extremely glitchy, the unstable version is laggy for me. only version that worked smoothly was the previous wine version that 1.11 removed.

**Comment by Kevin-Haus24** [comment]
> v9.2-mingw is extremely glitchy, the unstable version is laggy for me. only version that worked smoothly was the previous wine version that 1.11 removed. edit: the shain version works well on the latest version

Will it be necessary to reinstall the game again?

**Comment by Kevin-Haus24** [comment]
> Will add some of old wine distribution back later. To rollback you can uninstall yaagl and download 0.1.10 manually to replace the current one, then ignore the update notification.

Will it be necessary to reinstall the game again?

**Comment by 3Shain** [comment]
> > Will add some of old wine distribution back later. To rollback you can uninstall yaagl and download 0.1.10 manually to replace the current one, then ignore the update notification.
> 
> Will it be necessary to reinstall the game again?

no as you choose exactly the same game installation directory

**Comment by Kevin-Haus24** [comment]
Thank you for returning unstable-bh-gptk-1.0 so soon. Now everything works stably as before.
