### ISSUE TITLE
会一直卡在“正在下载配置环境所需文件”

### ISSUE THREAD

**Issue by ShawnDiego** [yaagl/yet-another-anime-game-launcher#353]
会一直卡在“正在下载配置环境所需文件”，while 網速没有任何变化，但一直在显示这个。并且以这种方式在类似于局域网流量的速度。！[上传截屏2024-06-01 09.55.13.png...]()

**Comment by Zqanx** [comment]
1. 把 yaagl 移到废纸篓
2. 到 ~/Library/Application Support/Yaagl 或 ~/Library/Application Support/Yaagl OS 然后把整个 Yaagl （或 Yaagl OS）文件夹移到废纸篓。
3. 重新下载 yaagl

**Comment by Sipperz** [comment]
Closing issue because no further response was given, feel free to re-open the issue if need further help.

**Comment by ShawnDiego** [comment]
作者说把所有.app文件都删掉然后重新下载再试一次发自我的 iPhone在 2024年9月11日，17:56，Mcxiang94 ***@***.***> 写道：﻿
我也遇到了 你解决了么

**Comment by Tjmxxo** [comment]
同样，三个启动器都卡在这个界面，也是局域网在和aria2互传，几乎没有互联网访问
