### ISSUE TITLE
Wine doesn't work

### ISSUE THREAD

**Issue by mon0z** [yaagl/yet-another-anime-game-launcher#354]
So I have a MacBook M1 16gb RAM and enough space for genshin, but now that the older wines have dropped I cant play on the new ones no matter which wine I switch to. I tried using whisky but it's very confusing to me and doesn't work either. 
My playstation is slowly frying itself so I cant play on there so this MacBook is my only source of playing this game. 
I also used crossover before but now it doesn't work? 
<img width="1278" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/167961140/3cff6567-6da3-42d1-877d-983ab41e7c23">
it also said this 
<img width="402" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/167961140/df20d368-4f69-4530-aed9-af66019fc2db">
translation = the program genshinimpact.exe met a serious problem and had to shut down immediately, apologies 
can anybody please help? I don't want to lose my genshin over this... this is saddening me a lot
no matter what wine I use it doesn't work :(

**Comment by PEACEBOI712** [comment]
same goes for honkai star rail on Mac m1

**Comment by mon0z** [comment]
> same goes for honkai star rail on Mac m1

hi did u solve it or is it still stuck on the screen? if yes how did u solve it ?

**Comment by Menelkir** [comment]
> is anyone here to help??? I've commented almost a day ago and it still does the same thing ???????????

Because people do this using their free time, remember, we aren't hoyo and you're using a free service maintained by volunteers. If you're in a hurry, use a supported platform.

**Comment by Zqanx** [comment]
@mon0z 
Since you have 16gb of ram, you will want to use crossover wine (option appears in yaagl settings). 

@PEACEBOI712 
Hsr is currently in a bizarre situation; performance is very inconsistent. We will unfortunately not provide support for that.

**Comment by mon0z** [comment]
> @mon0z Since you have 16gb of ram, you will want to use crossover wine (option appears in yaagl settings).
> 
> @PEACEBOI712 Hsr is currently in a bizarre situation; performance is very inconsistent. We will unfortunately not provide support for that.

hij I use crossover but it said to check the compatibility thing in crossover and gave me yet again the same error message

**Comment by Zqanx** [comment]
@mon0z 
Not sure what you're talking about... can you provide a picture of "check compatibility"? Also make sure you're using latest version of crossover.

**Comment by mon0z** [comment]
> 



> @mon0z Not sure what you're talking about... can you provide a picture of "check compatibility"? Also make sure you're using latest version of crossover.

<img width="402" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/167961140/b0ad9c09-fa2e-427a-aa48-24d16387997b">
how can I see what version of crossover I'm using?

**Comment by Zqanx** [comment]
Right click crossover app, then cmd + i to see info. Also, is your macos version sonoma 14.4 or later?

**Comment by mon0z** [comment]
> Right click crossover app, then cmd + i to see info. Also, is your macos version sonoma 14.4 or later?

yes my Mac is 14.5 and my crossover is version 24.0.3

**Comment by Zqanx** [comment]
This might be a rosetta issue since you said none of the wines work for you... paste `softwareupdate --install-rosetta` in terminal.

**Comment by mon0z** [comment]
> This might be a rosetta issue since you said none of the wines work for you... paste `softwareupdate --install-rosetta` in terminal.

this might sound dumb (I'm no good in computer stuff), but how do I open this terminal?

**Comment by Zqanx** [comment]
You can access it through applications in finder, or hit cmd + space then type terminal.

**Comment by Zqanx** [comment]
That's weird. Restart your computer and try again?

**Comment by mon0z** [comment]
> That's weird. Restart your computer and try again?

ok will try

**Comment by mon0z** [comment]
I tried and it gave me the same message

**Comment by Zqanx** [comment]
Somethings seems to be unusual with your mac configuration... I'm afraid you will have to reset your mac (you can google how to do that). However make sure to back up important files before that.

**Comment by mon0z** [comment]
> Something seems to be unusual with your mac configuration... I'm afraid you will have to reset your mac (you can google how to do that). However make sure to back up important files before that.

If I reset does my account disappear? Because I looked up how but it only have me factory reset

**Comment by mon0z** [comment]
> > Something seems to be unusual with your mac configuration... I'm afraid you will have to reset your mac (you can google how to do that). However make sure to back up important files before that.
> 
> If I reset does my account disappear? Because I looked up how but it only have me factory reset

can we maybe continue this in discord I feel like thats easier

**Comment by Sipperz** [comment]
> same goes for honkai star rail on Mac m1

Honkai does NOT work with crossover as of now. 

Instead use -9.2V Mingw/ 8.16-3shain/ Whisky.

**Comment by Sipperz** [comment]
This Issue was solved in discord today, after just updating to the newer Yaagl version.
