### ISSUE TITLE
Add a way to run the "full" game through YAAGL

### ISSUE THREAD

**Issue by OttersMeep** [yaagl/yet-another-anime-game-launcher#355]
**Is your feature request related to a problem? Please describe.**
There are some things I don't quite like about running Genshin through YAAGL, namely that it doesn't install the full game so you have to wait for an update on each version.

**Describe the solution you'd like**
Add an option to install the full game into a wine bottle, like Whisky does.

**Describe alternatives you've considered**
Using whisky, but the YAAGL specific tweaks are better.

**Comment by Menelkir** [comment]
Not sure if I understand what you mean. 
Yaagl does install the full game, and since we aren't hoyo, you have to wait for an update from hoyo to eventually update each version?

**Comment by Zqanx** [comment]
You can predownload and play with ac patch disabled even if newest yaagl update is not available yet.
