### ISSUE TITLE
Failed to run yaagl when switched to whisky-dxvk wine

### ISSUE THREAD

**Issue by Micuks** [yaagl/yet-another-anime-game-launcher#357]
**Describe the bug**
I cannot enter yaagl after switched to whisky-dxvk wine. There is a failed to modify /etc/hosts error when I open yaagl and enter password for the `osascript` event. This osascript cannot be executed in terminal manually. But the /etc/hosts is already the same content with what the osascript attempt to do. I guess the script is able to modify the file before. I'm on macOS Sonoma, and I'm able to enter game with mingw wine(wine-9.2).

**Screenshots**
<img width="532" alt="Screenshot 2024-06-06 at 4 01 45 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/43397551/28858db8-0995-4695-9fec-e4471f29a55c">
<img width="1157" alt="Screenshot 2024-06-06 at 4 02 03 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/43397551/2961bc63-f749-4919-b1dc-042db8b7da39">

**System Information (please complete the following information):**
 - macOS: [14.5 Sonoma]
 - Device: [e.g. MacbookPro M1 Pro 14inch]
 - CPU: [Apple M1 Pro]
 - RAM: [ 16G ]

**Additional context**
None
**Logs (if any)**
[neutralinojs.log](https://github.com/user-attachments/files/15607322/neutralinojs.log)

**Comment by Zqanx** [comment]
You can use whatever wine works for you. Or try crossover's wine.

**Comment by Micuks** [comment]
> You can use whatever wine works for you. Or try crossover's wine.

But with this error I'm unable to enter yaagl to switch to other wine distros. Is there any way to modify related configurations with terminal? or reset yaagl's configurations?

**Comment by Zqanx** [comment]
Uninstall and redownload yaagl launcher (game files don't need to be touched). Method is on the main page.

**Comment by Sipperz** [comment]
Just checking in to see if the Issue was resolved?

**Comment by Sipperz** [comment]
Closing issue because of no response, feel free to re-open the issue if further help is required.
