### ISSUE TITLE
画面异常 Abnormal rendering

### ISSUE THREAD

**Issue by gaohecheng1** [yaagl/yet-another-anime-game-launcher#358]
渲染异常 Abnormal rendering

![截屏2024-06-07 08 25 50](https://github.com/yaagl/yet-another-anime-game-launcher/assets/134496553/f3db9ca3-d9e9-4a3f-a640-4537bc9941b2)
![截屏2024-06-07 08 24 54](https://github.com/yaagl/yet-another-anime-game-launcher/assets/134496553/25302605-8f91-4f2f-8d6e-b526e6f0d823)
![截屏2024-06-07 08 22 38](https://github.com/yaagl/yet-another-anime-game-launcher/assets/134496553/d701712d-5ab6-417a-bedf-96636af644e5)

 - macOS: [14.5 Sonoma]
 - Device: [MacbookPro 16inch 2023 ]
 - CPU: [Apple M3 Max, 30核GPU]
 - Dedicated GPU (if any): [Metal GPU ]
 - RAM: [36G ]
-  wine: [9.2]
Additional context：
画质全最高，出现画面泛白，把阴影质量降低后画面泛白消失，但是阴影异常仍然存在
The picture quality is the highest, and the picture is white. After the shadow quality is reduced, the picture is white and disappears, but the shadow is still abnormal.

**Comment by Menelkir** [comment]
Try disabling bloom and/or volumetric fog. This issue is usually related to one of them (or both).

**Comment by gaohecheng1** [comment]
> 渲染异常异常渲染
> 
> ![截屏2024-06-07 08 25 50](https://private-user-images.githubusercontent.com/134496553/337480551-f3db9ca3-d9e9-4a3f-a640-4537bc9941b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTUxLWYzZGI5Y2EzLWQ5ZTktNGEzZi1hNjQwLTQ1MzdiYzk5NDFiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGM1NDQ2ZWY2MDVlODZlOWJmYzc4ZjkwZjNmODYzZmNkZDYyNDYwMzhlYTU5Mjc4Y2U4MzYwZWYyOTA3Y2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UeXL0XWR7Yd186io-NCq6u7W44nAu3HN1dta3kmNpPg) ![截屏2024-06-07 08 24 54](https://private-user-images.githubusercontent.com/134496553/337480556-25302605-8f91-4f2f-8d6e-b526e6f0d823.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTU2LTI1MzAyNjA1LThmOTEtNGYyZi04ZDZlLWI1MjZlNmYwZDgyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTg2MjFkNzkwYThlMGExZmNlNDU2YzAyNmUzYzJiZTVhMDM5NjFlNmM2NmM5YThjODZkMmIzNzhmYWJmZDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.74GhtLlHGhchkd1YcsBd_Jrb6nLQg1w1NNg_ChZokl4) ![截屏2024-06-07 08 22 38](https://private-user-images.githubusercontent.com/134496553/337480561-d701712d-5ab6-417a-bedf-96636af644e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTYxLWQ3MDE3MTJkLTVhYjYtNDE3YS1iZWRmLTk2NjM2YWY2NDRlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmQ4YjVmMTY3MTg3NDkyMGQ0NGNjNTE3ZDQ5MmY2ODEwOGQ4YmQ1NjBmYmNjZTAxNWViMWIwZmI4ZjQ3MjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oAsxNRvuwh15yukYdLMTgtJqdY4neYG3Z4IY0ryOYz0)
> 
> * macOS：[14.5 Sonoma]
> * 设备：[MacbookPro 16inch 2023]
> * CPU：[Apple M3 Max，30核GPU]
> * 专用GPU（如果有的话）：[金属GPU]
> * 内存：[36G]
> * 葡萄酒：[9.2]附加上下文：画质全最高，出现画面泛白，把阴影质量降低后画面泛白消失，但阴影异常仍然存在图片质量最高，图片是白色的。阴影质量降低后，图片是白色的，消失了，但阴影仍然不正常。

所有NPC靠近都只剩一张脸，另外，整个地图都没有草
There is only one face left when all NPCs are close. In addition, there is no grass on the whole map.

**Comment by Sipperz** [comment]
> > 渲染异常异常渲染
> > ![截屏2024-06-07 08 25 50](https://private-user-images.githubusercontent.com/134496553/337480551-f3db9ca3-d9e9-4a3f-a640-4537bc9941b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTUxLWYzZGI5Y2EzLWQ5ZTktNGEzZi1hNjQwLTQ1MzdiYzk5NDFiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGM1NDQ2ZWY2MDVlODZlOWJmYzc4ZjkwZjNmODYzZmNkZDYyNDYwMzhlYTU5Mjc4Y2U4MzYwZWYyOTA3Y2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UeXL0XWR7Yd186io-NCq6u7W44nAu3HN1dta3kmNpPg) ![截屏2024-06-07 08 24 54](https://private-user-images.githubusercontent.com/134496553/337480556-25302605-8f91-4f2f-8d6e-b526e6f0d823.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTU2LTI1MzAyNjA1LThmOTEtNGYyZi04ZDZlLWI1MjZlNmYwZDgyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTg2MjFkNzkwYThlMGExZmNlNDU2YzAyNmUzYzJiZTVhMDM5NjFlNmM2NmM5YThjODZkMmIzNzhmYWJmZDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.74GhtLlHGhchkd1YcsBd_Jrb6nLQg1w1NNg_ChZokl4) ![截屏2024-06-07 08 22 38](https://private-user-images.githubusercontent.com/134496553/337480561-d701712d-5ab6-417a-bedf-96636af644e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTYxLWQ3MDE3MTJkLTVhYjYtNDE3YS1iZWRmLTk2NjM2YWY2NDRlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmQ4YjVmMTY3MTg3NDkyMGQ0NGNjNTE3ZDQ5MmY2ODEwOGQ4YmQ1NjBmYmNjZTAxNWViMWIwZmI4ZjQ3MjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oAsxNRvuwh15yukYdLMTgtJqdY4neYG3Z4IY0ryOYz0)
> > 
> > * macOS：[14.5 Sonoma]
> > * 设备：[MacbookPro 16inch 2023]
> > * CPU：[Apple M3 Max，30核GPU]
> > * 专用GPU（如果有的话）：[金属GPU]
> > * 内存：[36G]
> > * 葡萄酒：[9.2]附加上下文：画质全最高，出现画面泛白，把阴影质量降低后画面泛白消失，但阴影异常仍然存在图片质量最高，图片是白色的。阴影质量降低后，图片是白色的，消失了，但阴影仍然不正常。
> 
> 所有NPC靠近都只剩一张脸，另外，整个地图都没有草 There is only one face left when all NPCs are close. In addition, there is no grass on the whole map.

Disable Dynamic character resolution.

**Comment by gaohecheng1** [comment]
> > > 渲染异常异常渲染
> > > ![截屏2024-06-07 08 25 50](https://private-user-images.githubusercontent.com/134496553/337480551-f3db9ca3-d9e9-4a3f-a640-4537bc9941b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTUxLWYzZGI5Y2EzLWQ5ZTktNGEzZi1hNjQwLTQ1MzdiYzk5NDFiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGM1NDQ2ZWY2MDVlODZlOWJmYzc4ZjkwZjNmODYzZmNkZDYyNDYwMzhlYTU5Mjc4Y2U4MzYwZWYyOTA3Y2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UeXL0XWR7Yd186io-NCq6u7W44nAu3HN1dta3kmNpPg) ![截屏2024-06-07 08 24 54](https://private-user-images.githubusercontent.com/134496553/337480556-25302605-8f91-4f2f-8d6e-b526e6f0d823.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTU2LTI1MzAyNjA1LThmOTEtNGYyZi04ZDZlLWI1MjZlNmYwZDgyMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTg2MjFkNzkwYThlMGExZmNlNDU2YzAyNmUzYzJiZTVhMDM5NjFlNmM2NmM5YThjODZkMmIzNzhmYWJmZDAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.74GhtLlHGhchkd1YcsBd_Jrb6nLQg1w1NNg_ChZokl4) ![截屏2024-06-07 08 22 38](https://private-user-images.githubusercontent.com/134496553/337480561-d701712d-5ab6-417a-bedf-96636af644e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MjgyMzcsIm5iZiI6MTcxNzgyNzkzNywicGF0aCI6Ii8xMzQ0OTY1NTMvMzM3NDgwNTYxLWQ3MDE3MTJkLTVhYjYtNDE3YS1iZWRmLTk2NjM2YWY2NDRlNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNjI1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmQ4YjVmMTY3MTg3NDkyMGQ0NGNjNTE3ZDQ5MmY2ODEwOGQ4YmQ1NjBmYmNjZTAxNWViMWIwZmI4ZjQ3MjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oAsxNRvuwh15yukYdLMTgtJqdY4neYG3Z4IY0ryOYz0)
> > > 
> > > * macOS：[14.5 Sonoma]
> > > * 设备：[MacbookPro 16inch 2023]
> > > * CPU：[Apple M3 Max，30核GPU]
> > > * 专用GPU（如果有的话）：[金属GPU]
> > > * 内存：[36G]
> > > * 葡萄酒：[9.2]附加上下文：画质全最高，出现画面泛白，把阴影质量降低后画面泛白消失，但阴影异常仍然存在图片质量最高，图片是白色的。阴影质量降低后，图片是白色的，消失了，但阴影仍然不正常。
> > 
> > 
> > 所有NPC靠近都只剩一张脸，另外，整个地图都没有草 There is only one face left when all NPCs are close. In addition, there is no grass on the whole map.
> 
> Disable Dynamic character resolution.

我关闭了动态角色高精度，NPC的问题解决了，但是整张地图上依然没有草，渲染错误的问题依旧存在
I turned off theDynamic character resolution, and the problem of NPC was solved, but there was still no grass on the whole map, and the problem of rendering errors still existed.

**Comment by Sipperz** [comment]
Sorry for late reply didn't get notified, Since you have 36 GB of RAM Would recommend using Crossover wine through Yaagl.

**Comment by gaohecheng1** [comment]
> 很抱歉回复晚了，没有收到通知，由于您有36 GB的RAM，建议您通过Yaagl使用Crossover葡萄酒。
I installed crossover but I can't see it in yaagl

**Comment by Sipperz** [comment]
> > 很抱歉回复晚了，没有收到通知，由于您有36 GB的RAM，建议您通过Yaagl使用Crossover葡萄酒。
> 
> I installed crossover but I can't see it in yaagl

Give Yaagl full disc access and it should show up.

**Comment by Sipperz** [comment]
Closing issue cause no further response was given, feel free to re-open issue if required.
