### ISSUE TITLE
Verification didnt show up

### ISSUE THREAD

**Issue by bikinmalu** [yaagl/yet-another-anime-game-launcher#359]
**Describe the bug**
I already uncheck ac patch, uncheck workaround, but still the same, the verification pict didnt show up

**Screenshots**

**System Information (please complete the following information):**
 - macOS: Sonoma 14.5
 - Device: imac 2019
 - CPU: Intel i7 3.2 Ghz
 - Dedicated GPU (if any): Radeon Pro 560X 4GB
 - RAM: 16GB

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Sipperz** [comment]
> **Describe the bug**
> 
> I already uncheck ac patch, uncheck workaround, but still the same, the verification pict didnt show up
> 
> 
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> 
> 
> **System Information (please complete the following information):**
> 
>  - macOS: Sonoma 14.5
> 
>  - Device: imac 2019
> 
>  - CPU: Intel i7 3.2 Ghz
> 
>  - Dedicated GPU (if any): Radeon Pro 560X 4GB
> 
>  - RAM: 16GB
> 
> 
> 
> **Additional context**
> 
> Add any other context about the problem here.
> 
> 
> 
> **Logs (if any)**
> 
> 
> 
> > If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
> 
> 
> 
> > If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
> 
> 

Which wine version are u using?

**Comment by bikinmalu** [comment]
> > **Describe the bug**
> > I already uncheck ac patch, uncheck workaround, but still the same, the verification pict didnt show up
> > **Screenshots**
> > If applicable, add screenshots to help explain your problem.
> > **System Information (please complete the following information):**
> > 
> > * macOS: Sonoma 14.5
> > * Device: imac 2019
> > * CPU: Intel i7 3.2 Ghz
> > * Dedicated GPU (if any): Radeon Pro 560X 4GB
> > * RAM: 16GB
> > 
> > **Additional context**
> > Add any other context about the problem here.
> > **Logs (if any)**
> > > If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory
> > 
> > 
> > > If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
> 
> Which wine version are u using?

v9.2-mingw

**Comment by Sipperz** [comment]
switch to "unstable-bh-gptk-1.0"

**Comment by bikinmalu** [comment]
> switch to "unstable-bh-gptk-1.0" .
> 
> or try all of the following -
> 
> 1. do it blind by drag drop the puzzle
> 2. alt-tab minimise/maximise genshin before login
> 3. try on-off AC patch for the above
> 4. when on Cpatcha screen spam "Return/Enter" key.

nothings happen, i try unstable-bh-gptk-1.0, game isnt launch

**Comment by Sipperz** [comment]
Oh I am Sorry, I Mistook ur Specs, Intel won't work with Unstable

Try Crossover instead.

**Comment by bikinmalu** [comment]
> Oh I am Sorry, I Mistook ur Specs, Intel won't work with Unstable
> 
> Try Crossover instead.
> 
> 1. Download Crossover/Trial from Codeweavers website
> 2. Install it > Launch it one time
> 3. Go back to Yaagl > Settings > wine >"should see crossover as option".

still the same

**Comment by bikinmalu** [comment]
<img width="2048" alt="Screenshot 2024-06-12 at 15 19 43" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/161714653/898010c7-89fc-42a2-9d79-bf48297b627a">
dis i use crossover, but veerif isnt show up

**Comment by Sipperz** [comment]
Don't know what else is left to try then, last thing I can suggest is use a DNS like 8.8.8.8 and 8.8.4.4, Minimize the game few times when the verify is up.

**Comment by Sipperz** [comment]
Closing this issue because no further response was received, feel free to re-open the issue if required.
