### ISSUE TITLE
须弥沙漠没脚印效果

### ISSUE THREAD

**Issue by TLuuuLT** [yaagl/yet-another-anime-game-launcher#361]
须弥沙漠没有脚印效果
macOS：14.5 Sonoma
设备：MacbookPro 14英寸2023
CPU：Apple M2 Pro
内存：16G
须弥沙漠没有脚印效果

**Comment by Sipperz** [comment]
No footprints for everyone, its a known thing but no solution as of now.

**Comment by Sipperz** [comment]
Update related to this -

**Dev Beta** for Mac OS 15 Sequoia + Gptk 2.0 ( Game Porting Tool Kit)

Does happen to render Footsteps in sumeru desert by Combining Gptk 2.0 + Whisky.

This was Tested on M3 PRO Model only atm, Very early testing it can change in the future versions.
