### ISSUE TITLE
Game Won't Launch

### ISSUE THREAD

**Issue by lunarberries** [yaagl/yet-another-anime-game-launcher#362]
**Describe the bug**
When the launcher is opened and the "launch" button is pressed, the loading bar shows up saying "Game launching, do not close launcher" but goes back to the launch button again. Wine was changed to unstable-bh-gptk-1.0 and launch happens successfully, but the graphics are poor, game lags, and certain actions like in-game speech are unavailable. Tested with mingw wine and shain but it still will not launch. 

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. Sonoma 14.5 ]
 - Device: [e.g. MacbookPro 16inch 2023 ]
 - CPU: [e.g. Apple M2 Max ]
 - RAM: [e.g. 32G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Sipperz** [comment]
Use crossover wine instead of gptk

Download Crossover/Trial from Codeweavers website

Install it > Launch it one time

Go back to Yaagl > Settings > wine >"should see crossover as option".

**Comment by lunarberries** [comment]
Crossover wine isn't showing up in wine settings on Yaagl. Is there something I need to do in the Crossover application? It is in the applications folder.

**Comment by Sipperz** [comment]
it should Just pick it up, Nothing else to do,
Give Yaagl full disk access(it is not needed mostly)

System Settings > Privacy and Security > Full disk access > Toggle Yaagl (if you don't see Yaagl, bottom left has a "+" navigate to Yaagl and add it).

**Comment by Sipperz** [comment]
@lunarberries checking in to see if everything is working, if not please reply and tell us what more issues are happening.

**Comment by lunarberries** [comment]
I was able to get crossover wine and everything runs as before like nothing had happened! Thank you very much for the help.

**Comment by Sipperz** [comment]
Good to hear, Happy gaming!
Will close this Issue now.
