### ISSUE TITLE
The Launcher is unable to open some particular file and won't turn on

### ISSUE THREAD

**Issue by Sh1buraji** [yaagl/yet-another-anime-game-launcher#364]
The Launcher fires an error that is out of my realm of understanding, would be really grateful for some help

<img width="1285" alt="SCR-20240612-mgla" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/140177673/fe5aa834-7394-47e2-90a0-2af7013d30ff">

 - macOS: 14.5 Sonoma
 - Device: 13 inch Macbook Air 2020
 - CPU: Apple M1
 - Dedicated GPU: None
 - RAM: 8Gb

Logs:-
[neutralinojs.log](https://github.com/user-attachments/files/15801002/neutralinojs.log)

**Comment by Sipperz** [comment]
Replied to this on Discord Support already.

**Comment by Sipperz** [comment]
Your Yaagl is not in /Application -

Delete Yaagl, Delete Yaagl OS folder in /Applications Support, Reinstall in /Applications.
