### ISSUE TITLE
Wine Error when Lauching game

### ISSUE THREAD

**Issue by cascadex5** [yaagl/yet-another-anime-game-launcher#365]
**Describe the bug**
Everything in the laucher works perfectly fine. However, when i launched the game, a fatal error "failed to load il2cpp appears". I tested v9.2-mingw, v8.16-3shain, unstable-bh-gptk-1.0, and even tried crossover, but the error still appears on launch. After pressing "ok" in the error box the game just quits itself.

**Screenshots**
<img width="1512" alt="Screenshot 2024-06-12 at 22 09 50" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/92843678/60e3661e-064a-482e-97e5-77d94d303875">

**System Information (please complete the following information):**
 - macOS: [14.5 Sonoma]
 - Device: [MacbookPro 14inch 2023 ]
 - CPU: [Apple M3 Pro 11 Core ]
 - RAM: [18G ]

**Additional context**

**Logs (if any)**

File not found.

46305.833:00b8:err:service:validate_context_handle Access denied - handle created with access 34, needed 10000
46306.448:0150:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\\windows\\system32\\HoYoKProtect.sys") not found
46306.449:0150:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\HoYoProtect": c0000142
[experimental-async-load] Disabled 
[2024-06-12 22:09:36.697] MultiThreadStackTrace init success!
46306.588:0128:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
46306.590:0128:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
46306.590:0128:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
Set new unhandled exception filter 00006FFFFCC540F0 to replace 00006FFFFCDA4060
url fetch responce: {"code":0}
url fetch responce: {"code":0,"message":"app running","milliTs":"1718201377265"}
url fetch responce: {"retcode":0,"message":"success","data":null}

**Comment by Sipperz** [comment]
it seems some files are missing, Reinstall the launcher

Uninstall Yaagl app > after Delete Yaagl OS folder in /Applications Support > Then make sure to reinstall it and move it to /Applications before opening.

Also may I ask where is ur Game download located?

**Comment by cascadex5** [comment]
It is downloaded in my user folder.

**Comment by Sipperz** [comment]
> It is downloaded in my user folder.

Good good, its in a folder rite just to be sure "game" or something.

**Comment by cascadex5** [comment]
Is it normal that it is fixing game files?
<img width="1512" alt="Screenshot 2024-06-12 at 23 05 35" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/92843678/62995da5-7db4-457d-9ad0-413dc67380e9">

**Comment by Sipperz** [comment]
Sorry for late reply, yes integrity check scans files and makes sure everything that is needed is downloaded and working as they are intended, your error did show some files were missing so completely normal.

**Comment by cascadex5** [comment]
The same error still appears after reinstalling.

Logs:

File not found.

78096.533:014c:err:module:import_dll Library WDFLDR.SYS (which is needed by L"C:\\windows\\system32\\HoYoKProtect.sys") not found
78096.536:014c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\HoYoProtect": c0000142
[experimental-async-load] Disabled 
[2024-06-13 06:59:27.160] MultiThreadStackTrace init success!
78097.211:0124:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
78097.299:0124:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
78097.299:0124:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
Set new unhandled exception filter 00006FFFFCC540F0 to replace 00006FFFFCDA4060
[astrolabe:288:392:0613/065927.608:78097337:ERROR:hoyo_chrome_pref_service_factory.cc(27)] 6
url fetch responce: {"code":0,"message":"app running","milliTs":"1718233171349"}
url fetch responce: {"code":0}
url fetch responce: {"retcode":0,"message":"success","data":null}

**Comment by Sipperz** [comment]
that makes me thing your game is not in a folder, which is resulting in Yaagl not being able to find

**Comment by Sipperz** [comment]
<img width="1032" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/120113737/17f5cf17-3c47-4c7b-8984-ee5fec653299">
For example

**Comment by cascadex5** [comment]
<img width="1046" alt="Screenshot 2024-06-13 at 14 06 49" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/92843678/efb73b63-5f30-4a4f-86a9-16c21d4a63b3">

Game folder

**Comment by cascadex5** [comment]
i just realized there is a log file you don't have its {GenshinImpact.gc.log}

the log in the file:

(0) Failed to allocate 262144 (aligned 262144) bytes at 0x0000070081040000: 487
    VQ: BA=0x0000070081040000 AB=0x000006FFFFFF0000 AP=0x1 RS=6425411584 S=0x2000 P=0x0 T=0x20000

**Comment by Sipperz** [comment]
weird, give Yaagl full disk access and see if it makes a diff 

System settings > Privacy & security > Full disc > add Yaagl.

**Comment by cascadex5** [comment]
Same error. Should i reinstall the game?

**Comment by Sipperz** [comment]
> Same error. Should i reinstall the game?

Yeah unfortunately have to

**Comment by Sipperz** [comment]
Also, are u using any Anti cheats?

**Comment by cascadex5** [comment]
No im not using any. I reinstalled the game and it works now. Thanks for ur help

**Comment by Sipperz** [comment]
Everything working now rite? I see the message was edited so waited to ask if any problems still.

**Comment by Sipperz** [comment]
asking again to check in if everything is working as expected? will close this issue in 9 hours if no response, feel free to reopen if needed.
