### ISSUE TITLE
game closes as soon as i launch

### ISSUE THREAD

**Issue by akitort** [yaagl/yet-another-anime-game-launcher#366]
<img width="1440" alt="Screenshot 2024-06-13 at 9 49 06 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/d850f5ed-0a2e-4cf3-acfd-336cf37a5331">
im using m1 mac 8gb ram 14.5 sonoma

**Comment by Sipperz** [comment]
@akitort Press show details, and upload them so we can have an idea what the error is

**Comment by akitort** [comment]
> @akitort Press show details, and upload/Copy paste it here so we can have an idea what the error is

how do i do that gimme some instructions

**Comment by akitort** [comment]
> @akitort Press show details, and upload/Copy paste it here so we can have an idea what the error is

like after i click show details then copy everything?

**Comment by Sipperz** [comment]
![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/120113737/02ea0ee9-b77e-4fd3-b544-96a1262afd9f)

When u get the error pop up, it says show details there, take a screen shot of what it shows.

**Comment by akitort** [comment]
> @akitort Press show details, and upload/Copy paste it here so we can have an idea what the error is

<img width="1440" alt="Screenshot 2024-06-14 at 8 32 23 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/a3c4492d-f55e-4e2f-b93c-281cf256a4ba">

**Comment by Sipperz** [comment]
Your Yaagl is not in /Applications folder

Delete Yaagl > in Finder search for "Yaagl OS" Folder that should be in /Applications support > delete the Yaagl folder > Reinstall Yaagl in /Applications.

**Comment by Sipperz** [comment]
I didn't see the Second Message asking about what all to copy paste, was replying on mobile, My bad.

**Comment by akitort** [comment]
> I didn't see the Second Message asking about what all to copy paste, was replying on mobile, My bad.

its fine thanx a lot imma delete it and reinstall and let u know if its working

**Comment by akitort** [comment]
> Your Yaagl is not in /Applications folder
> 
> Delete Yaagl > in Finder search for "Yaagl OS" Folder that should be in /Applications support > delete the Yaagl folder > Reinstall Yaagl in /Applications.

in installation directory i should make a new folder on application and install there right?

**Comment by akitort** [comment]
<img width="1440" alt="Screenshot 2024-06-14 at 11 26 47 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/8a875fda-d9e2-4605-ba17-d29ebe861a86">
Like this?

**Comment by Sipperz** [comment]
> <img alt="Screenshot 2024-06-14 at 11 26 47 PM" width="1440" src="https://private-user-images.githubusercontent.com/142984210/339860032-8a875fda-d9e2-4605-ba17-d29ebe861a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NDAwNDgsIm5iZiI6MTcxODQzOTc0OCwicGF0aCI6Ii8xNDI5ODQyMTAvMzM5ODYwMDMyLThhODc1ZmRhLWQ5ZTItNDYwNS1iYTE3LWQyOWViZTg2MWE4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQwODIyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTEyMDQ0ZDNmYTBhOTMyNzI3MjgzNzMwZDVmZDMxOTA4NDYzM2RlOWE1N2ZhOGMwNzAyOTUyNzIyOTAxODJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HxnBDJ2rz67jan-gN83PvDndNDle3h-BTkxxrcH9fDc"> Like this?

Here like this 
<img width="1001" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/120113737/50808e91-d87a-4e43-833b-06023aa26848">

**Comment by Sipperz** [comment]
then put the game in ur Home like this 
<img width="1001" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/120113737/48726a78-fa27-423d-8bbf-d487d536d02e">

**Comment by Sipperz** [comment]
if u want quick response because it is taking a while, feel free to our Join discord.

**Comment by akitort** [comment]
> if u want quick response because it is taking a while, feel free to our Join discord.

thanx buddy and im already in the discord ;)

**Comment by Sipperz** [comment]
> > if u want quick response because it is taking a while, feel free to our Join discord.
> 
> thanx buddy and im already in the discord ;)

oh nice, ask whenever u have free time we will get it done very soon

**Comment by akitort** [comment]
> > > if u want quick response because it is taking a while, feel free to our Join discord.
> > 
> > 
> > thanx buddy and im already in the discord ;)
> 
> oh nice, ask whenever u have free time we will get it done very soon

<img width="1440" alt="Screenshot 2024-06-17 at 11 35 00 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/aa2fd089-a55d-4579-ad9a-e651d0d84f25">

**Comment by akitort** [comment]
> > > if u want quick response because it is taking a while, feel free to our Join discord.
> > 
> > 
> > thanx buddy and im already in the discord ;)
> 
> oh nice, ask whenever u have free time we will get it done very soon
<img width="1440" alt="Screenshot 2024-06-17 at 11 37 36 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/ff2db4c8-50be-408f-b842-81a1d66d28ef">
<img width="1440" alt="Screenshot 2024-06-17 at 11 37 45 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/379b925b-78c4-4d1d-9761-538dcf9c6a72">

**Comment by Sipperz** [comment]
maybe for some reason Rosetta was not installed

**Comment by akitort** [comment]
> Open terminal Type this - softwareupdate --install-rosetta

how to i do that ?

**Comment by Sipperz** [comment]
Search Terminal in Spotlight > open it and just copy paste it

**Comment by akitort** [comment]
> softwareupdate --install-rosetta

done

**Comment by Sipperz** [comment]
restart Mac, and launch game

**Comment by akitort** [comment]
> restart Mac, and launch game
<img width="1440" alt="Screenshot 2024-06-17 at 11 48 53 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/c5ed47d3-f7b7-4459-9d00-aa6a03e67093">
nah closed again

**Comment by Sipperz** [comment]
so go to /users/YOUR USER NAME/Library/Application Support/ Delete Yaagl os only and open launcher

**Comment by akitort** [comment]
> so go to /users/YOUR USER NAME/Library/Application Support/ Delete Yaagl os only and open launcher

ok done

**Comment by Sipperz** [comment]
it should have redownloaded environment

**Comment by akitort** [comment]
> so go to /users/YOUR USER NAME/Library/Application Support/ Delete Yaagl os only and open launcher

failed to launch aria2


> it should have redownloaded environment

yea

**Comment by Sipperz** [comment]
aria 2 is nothing
just reopen

**Comment by akitort** [comment]
> it should have redownloaded environment

i reinstall it now?

**Comment by akitort** [comment]
> it should have redownloaded environment

and choose the yaagl folder?

**Comment by Sipperz** [comment]
yes

**Comment by akitort** [comment]
<img width="1440" alt="Screenshot 2024-06-17 at 12 00 13 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/ae00dcc4-ecff-4434-9c66-b3f088127580">

**Comment by Sipperz** [comment]
> <img alt="Screenshot 2024-06-17 at 12 00 13 PM" width="1440" src="https://private-user-images.githubusercontent.com/142984210/340199786-ae00dcc4-ecff-4434-9c66-b3f088127580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDYxMzQsIm5iZiI6MTcxODYwNTgzNCwicGF0aCI6Ii8xNDI5ODQyMTAvMzQwMTk5Nzg2LWFlMDBkY2M0LWVjZmYtNDQzNC05YzY2LWIzZjA4ODEyNzU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwNjMwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmEwOTg2NTgxMWI1Yjk0YWQxN2Y4YmMxZWI0MWI4NmUwZWI3ZGZiYjhlYjU3YmVjZGMxNzcwZmJkZmE5Zjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yKd_HnrVWsZw8ZvIk31GX_YUN2jnKxXUAdAMOcw__Q8">
yes choose that

**Comment by akitort** [comment]
like this?

**Comment by akitort** [comment]
<img width="1440" alt="Screenshot 2024-06-17 at 12 01 18 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/1e208fac-7762-4300-ab9e-a9c6ee62db48">

**Comment by Sipperz** [comment]
are u not on the latest version of yaagl?

**Comment by akitort** [comment]
> are u not on the latest version of yaagl?

should i re download? yaagl

**Comment by Sipperz** [comment]
might as well

**Comment by Sipperz** [comment]
make sure it is latest

**Comment by Sipperz** [comment]
and for good measure change the YAAGL folder where genshin is located to something like "AnimeGame"

**Comment by akitort** [comment]
> make sure it is latest

done

**Comment by akitort** [comment]
checking file integrity

**Comment by Sipperz** [comment]
noice

**Comment by akitort** [comment]
<img width="1440" alt="Screenshot 2024-06-17 at 12 10 40 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/2d91a2a2-3ce0-4ab4-869d-2c2de352b953">
i think yaagl doesnt like me T_T

**Comment by Sipperz** [comment]
seems that way

**Comment by akitort** [comment]
> seems that way

sed

**Comment by Sipperz** [comment]
we have tried Full disc access right?

**Comment by akitort** [comment]
> we have tried Full disc access right?

nah whats that

**Comment by Sipperz** [comment]
in system settings > Privacy & security > Full disc > add Yaagl

**Comment by akitort** [comment]
<img width="1440" alt="Screenshot 2024-06-17 at 12 32 16 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/18d2e0c5-e7cc-4593-8c4e-3b15a77e6fd6">
nope

**Comment by Sipperz** [comment]
I will assign other members we have tried everything to my knowledge, Maybe they have something I am missing, Sorry it is taking this long

**Comment by akitort** [comment]
> I will assign other members we have tried everything to my knowledge, Maybe they have something I am missing, Sorry it is taking this long
ok

**Comment by akitort** [comment]
what to do now?

**Comment by Sipperz** [comment]
can only wait, they are most likely sleeping because Timezones

**Comment by akitort** [comment]
> can only wait, they are most likely sleeping because Timezones

oh ok

**Comment by Zqanx** [comment]
@akitort So I've noticed one thing that has not been tried here is changing wine version. Try changing your wine version to something else.

**Comment by akitort** [comment]
> can only wait, they are most likely sleeping because Timezones

thanx for ur help bro but i think i should just uninstall it imma try hsr on the mac i hope that works
bye bud
