### ISSUE TITLE
Can't type password.

### ISSUE THREAD

**Issue by Phaozini** [yaagl/yet-another-anime-game-launcher#367]
At the login screen window I can type login, but can't type password. Tried to copy-paste it - not working. Switching language - not working.

**System Information:**
 - macOS: 14.5 Sonoma
 - Device: Mac mini M1 2020
 - RAM: 16Gb

**Comment by Phaozini** [comment]
Thank you!

**Comment by Sipperz** [comment]
> Thank you!

is everything working now?

**Comment by Phaozini** [comment]
Yes. It’s working.

**Comment by Sipperz** [comment]
Noice, I will close this then, feel free to reopen if another problem come sup.
