### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by creepiersunn** [yaagl/yet-another-anime-game-launcher#368]
**Describe the bug**
Recently after updating the launcher to be able to play GI 4.7 the game will not launch at all. When I press the button to launch the game, the loading bar starts working and says 'DO NOT CLOSE THE LAUNCHER' which is perfectly normal. After a moment it briefly says 'Reverting Patches' above the loading bar before the bar disappears and just shows the game launch button. I have tried everything from reinstalling the launcher multiple times including the game files and even trying to download wine from winehq.org and launching it through that instead of yaagl. I would attach a screenshot but the reverting patches pops up so quickly I couldn't get it on screenshot. Also just as a psa the whole yaagl launcher and wine worked perfectly fine on GI 4.6 and ran the game with no issue even though I am on 8GB of RAM.

**Screenshots**

**System Information (please complete the following information):**
 - macOS: 14.5 Sonoma
 - Device: Macbook 13 inch M1 2020
 - CPU: Apple M1
 - Dedicated GPU (if any): 
 - RAM: 8 GB

**Additional context**

**Logs (if any)**
[neutralinojs.log](https://github.com/user-attachments/files/15855018/neutralinojs.log)

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Sipperz** [comment]
Hmm, where is ur Yaagl and Game files located?

**Comment by creepiersunn** [comment]
They're in a folder called Genshin Impact in my user directory

**Comment by creepiersunn** [comment]
Oh and yaagl is in the applications

**Comment by Sipperz** [comment]
change the wine to "unstable-bh-gptk-1.0"
and see if it makes a difference

**Comment by Sipperz** [comment]
Did you have to clean ur Mac before the update by any chance?

**Comment by creepiersunn** [comment]
What do you mean by cleaning the mac? Like wiping everything on it?

**Comment by creepiersunn** [comment]
Oh no i just got a prompt to update the launcher when I opened it yesterday and it just downloaded the resources and updated

**Comment by Sipperz** [comment]
Hmm okey, was making sure if Rosetta 2 didn't get uninstall in the process.

**Comment by Sipperz** [comment]
Still worth a shot tho, "softwareupdate --install-rosetta" in Terminal and see what happens.

**Comment by creepiersunn** [comment]
Did the rosetta thing and it said it installed so it must’ve uninstalled itself

**Comment by creepiersunn** [comment]
Just gonna reload yaagl and see if it’s fixed

**Comment by creepiersunn** [comment]
Anddd its all working now, changed the wine like you said and installed rosetta again cuz it uninstalled istelf

**Comment by creepiersunn** [comment]
Thanks so much for the help <3

**Comment by Sipperz** [comment]
noice, Have fun
