### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by KexinyingLife** [yaagl/yet-another-anime-game-launcher#369]
TypeError: Right side of assignment cannot be destructured
<img width="532" alt="截屏2024-06-17 12 19 03" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/109
<img width="532" alt="截屏2024-06-17 12 19 03" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/109401143/4db1b0fd-efec-40fe-8328-00d2bc81d0ba">
401143/c6d9d46f-390b-422f-b54b-1cd61f014355">

**Comment by Sipperz** [comment]
HSR?

**Comment by KexinyingLife** [comment]
yes，hsr

**Comment by Sipperz** [comment]
Seems to be API error will update in a bit if any solution is found.

**Comment by Sipperz** [comment]
Check the pre-release in "Releases Tab", download the new ones, it works.

**Comment by Menelkir** [comment]
FYI: HSR is unplayable outside the supported platforms atm.
