### ISSUE TITLE
Yaagl HSR.app: TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by winfan1314** [yaagl/yet-another-anime-game-launcher#370]
**Describe the bug**
Yaagl-HSR report TypeError when launched.
TypeError: Right side of assignment cannot be destructured

**Screenshots**
<img width="488" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/59993589/53902818-8318-49c3-bc1f-43b25c9efbaf">

**System Information:**
 - macOS: macOS 15.0 (24A5264n)
 - Device: MacbookPro 16inch 2023
 - CPU: Apple M3 Max (12P+4E+40G)
 - Dedicated GPU (if any): 
 - RAM: 64G

**Additional context**
I think this problem is related to the v2.3 update of the game.

**Comment by Sipperz** [comment]
It's mostly API Error will check in a bit to see if I can recreate it.

**Comment by zijunchen68** [comment]
I come across the same problem

**Comment by KevinXC5** [comment]
Yes, I'm having the same problem, my current system is MacOS sequoia

**Comment by Sipperz** [comment]
We are aware, it will not work for anyone atm unfortunately, we are looking into the issue

**Comment by hyan46** [comment]
> Yes, I'm having the same problem, my current system is MacOS sequoia

I suspect this could be 2.3 update as well. Because prior to 2.3, I think it works perfectly even with the Mac OS Sequoia. It could also be interaction between 2.3 and  Mac OS Sequoia

**Comment by Sipperz** [comment]
It is because Hoyo is moving to HoyoPlay and have changed API and server side links, nothing to do with 2.3 or Mac itself.

**Comment by Sipperz** [comment]
we also suspect within 9-10 hours the "main" Yaagl game will have the same error as they announced today they are dropping support for that launcher as well Starting today.

**Comment by Sipperz** [comment]
Check the pre-release in "Releases Tab", download the new ones, it works
<img width="1800" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/120113737/5030deee-dd4d-4157-b667-d60c2947b046">

**Comment by winfan1314** [comment]
> Check the pre-release in "Releases Tab", download the new ones, it works <img alt="image" width="1800" src="https://private-user-images.githubusercontent.com/120113737/340468074-5030deee-dd4d-4157-b667-d60c2947b046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjYxNjQsIm5iZiI6MTcxODcyNTg2NCwicGF0aCI6Ii8xMjAxMTM3MzcvMzQwNDY4MDc0LTUwMzBkZWVlLWRkNGQtNDE1Ny1iNjY3LWQ2MGMyOTQ3YjA0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxNTUxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTM4MDMxZTFhMGQ0M2NhNWY0ZmI4NDE0YmRlZDczZWU1OWJiYzY2MzU3NGJmNzIwNTlkMzY1ZDNhNjJlMTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Reqt2zPP7B0d6hm1Mn5WmltEP5SfiDXPNmce7DYtK0c">

fine! It works!
<img width="1392" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/59993589/cabc5962-f567-4752-998f-6ad8d07ac630">
