### ISSUE TITLE
YAAGL OS problem

### ISSUE THREAD

**Issue by Mary52-eng** [yaagl/yet-another-anime-game-launcher#372]
**Describe the bug**
I tried to install the crossover version but it won't appear there in my launcher. I can't uninstall the current launcher.

**System Information (please complete the following information):**
 - macOS: [e.g. 14.5 Ventura]
 - Device: [e.g. MacBook Air 15inch 2024 ]
 - CPU: [e.g. Apple M3, Intel i7 9750H ]
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Mary52-eng** [comment]
pLEASE HELP

**Comment by Zqanx** [comment]
Make sure to open crossover at least one time and make sure both yaagl and crossover are in applications.

**Comment by Sipperz** [comment]
since idk the correct ram number from copy paste, if you don't have more than 8 gb RAM Crossover will not appear.

**Comment by Menelkir** [comment]
What is the CPU? What is the macos version? How much ram?
Reopen when you're able to provide this data.
