### ISSUE TITLE
HSR Does not launch in v 2.3.0

### ISSUE THREAD

**Issue by hyan46** [yaagl/yet-another-anime-game-launcher#373]
**Describe the bug**
HSR Doesn't launch. Invalid UnityPlayer.dll checksum: 0xa4876121. This patch is intended to be used with HSR v 2.2.0. 

**Screenshots**
<img width="1258" alt="Screenshot 2024-06-18 at 4 32 39 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/1113404/a37354f0-94d7-413a-85e6-e80a358399b5">

**System Information (please complete the following information):**
 - macOS: [e.g. 15.0 Beta]
 - Device: [e.g. MacbookPro 16inch 2021 ]
 - CPU: [e.g. Apple M1 Pro ]
 - RAM: [e.g. 16G ]
 - Version: Pre-release 0.1.13

**Comment by Menelkir** [comment]
The launcher needs to be updated.
Worth noting HSR launcher is unsupported, as you can read [here](https://github.com/yaagl/yet-another-anime-game-launcher/releases/tag/0.1.11).
