### ISSUE TITLE
HSR OS

### ISSUE THREAD

**Issue by Skittles107** [yaagl/yet-another-anime-game-launcher#375]
my launcher will open but when i try to launch the game this pops up

![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/137018441/841f88de-f7a5-4dee-92d7-bd18b4de37cd)

**System Information (please complete the following information):**
 - macOS: 14.5 Sonma
 - Device: Macbook air m2 2022  13.6 inch
 - CPU: Apple M2
 - Dedicated GPU: dont even know what this means
 - RAM: 8G 

i have never experienced this before predownloading the 2.3 update

**Comment by Sipperz** [comment]
HSR will not work atm, only playable on supported platforms, wait for a update.

**Comment by Skittles107** [comment]
thanks
