### ISSUE TITLE
Genshin Won't Open

### ISSUE THREAD

**Issue by dnkenneth** [yaagl/yet-another-anime-game-launcher#376]
**Describe the bug**
After I installed and I press Launch Game it says, "Game is running (DO NOT CLOSE LAUNCHER)", but the game doesn't launch. Occasionally, Wine Debugger opens up and says "Can't attach process: error 87).

**Screenshots**
<img width="1508" alt="Screenshot 2024-06-19 at 8 58 24 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/173312595/13341090-5b7a-4d52-a87d-fc60b132513e">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.2.1
 - Device: Macbook Pro 16" 2021
 - CPU: Apple M1 Pro
 - Dedicated GPU (if any): None
 - RAM: 16GB

**Additional context**
I have tried:
- switching to all Wine versions including Crossover.
- installing Rosetta 2
- redownloading the game
- redownloading YAAGL/deleting Application support>YAAGL

**Logs (if any)**

File not found.

592055.991:0124:err:seh:call_stack_handlers invalid frame 00006FFFFBBD0D1F (0000000000022000-0000000000120000)
592055.991:0124:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.

**Comment by Menelkir** [comment]
It's written on the main page, update your mac.
