### ISSUE TITLE
Genshin won't start

### ISSUE THREAD

**Issue by Soliturd** [yaagl/yet-another-anime-game-launcher#377]
**Describe the bug**
Launcher opens fine, but when i click to launch, it loads while saying (the game is running), then after stops. i dont know if there are any screenshots for it but it just wont start

macOS: [Sonoma Version 14.4.1]
Device: [MacBook Air 13" 2020]
CPU: [Apple M1 (i cant find anymore info on the cpu)]
RAM: [8GB]

**Additional context**
Weird other thing but the app logo background is white now, normally transparent.

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory  (i still dont know how to do this)

**Comment by Menelkir** [comment]
It's written in the readme of the main page, needs Sonoma 14.4 for ARM.

**Comment by Sipperz** [comment]
Sorry about that GitHub didn't update the edit, this seems to be a Rosetta 2 issue, go to Terminal and type -

softwareupdate --install-rosetta

Follow through the prompts and see what happens.

**Comment by davecarrijo** [comment]
> softwareupdate --install-rosetta

it not help, still with the problem.

**Comment by Sipperz** [comment]
> it not help, still with the problem.

Any errors it is putting out?

**Comment by Soliturd** [comment]
> > it not help, still with the problem.
> 
> Any errors it is putting out?

1st off, how do i do your first request, im extremely bad at computer stuff so if you can be as detailed as possible that would be super awesome. 
and 2nd, im not getting any errors, it literally just wont launch.

**Comment by Soliturd** [comment]
> > it not help, still with the problem.
> 
> Any errors it is putting out?

OH SORRY, i get what your first reply meant now. I installed rosetta and it still isnt working. after installing i also reset my computer and force quit installer. Also checked file integrity, nothing working so far.

im gonna try deleting yaagl and redownloading though.

**Comment by Sipperz** [comment]
its all good I will be more detailed

Did u delete Yaagl OS folder in /Applications Support?

You can Locate the folder in Library(it is a hidden folder)

when you are on a Finder window > Press "Go" on the left Menu bar > Then press "Go to Folder" > Type Library .

Locate a Folder called "Applications support" > inside that folder should be Yaagl OS.

**Comment by Soliturd** [comment]
> its all good I will be more detailed
> 
> Did u delete Yaagl OS folder in /Applications Support?
> 
> You can Locate the folder in Library(it is a hidden folder)
> 
> when you are on a Finder window > Press "Go" on the left Menu bar > Then press "Go to Folder" > Type Library .
> 
> Locate a Folder called "Applications support" > inside that folder should be Yaagl OS.

i did that now, just redownloaded it after fully wiping yaagl off my laptop. finally at least getting an error message .

{"code":"NE_FS_FILRDER","message":"Unable to open file: /Applications/GenshinImpact_Data/globalgamemanagers"}

cant pick a file

**Comment by davecarrijo** [comment]
Guys, remember to just restart the pc. it helps

**Comment by Soliturd** [comment]
> Guys, remember to just restart the pc. it helps

i did a few times, no clue why it wont work

**Comment by sineoxan** [comment]
what are you opening it with?
crossover, wine, whisky?

**Comment by Sipperz** [comment]
> > its all good I will be more detailed
> > Did u delete Yaagl OS folder in /Applications Support?
> > You can Locate the folder in Library(it is a hidden folder)
> > when you are on a Finder window > Press "Go" on the left Menu bar > Then press "Go to Folder" > Type Library .
> > Locate a Folder called "Applications support" > inside that folder should be Yaagl OS.
> 
> i did that now, just redownloaded it after fully wiping yaagl off my laptop. finally at least getting an error message .
> 
> {"code":"NE_FS_FILRDER","message":"Unable to open file: /Applications/GenshinImpact_Data/globalgamemanagers"}
> 
> cant pick a file

Make sure Yaagl has the needed access and game is in a single folder not spread across ur home

**Comment by Soliturd** [comment]
> what are you opening it with? crossover, wine, whisky?

the default, i haven't tried anything different for it. everything is just the default

**Comment by Soliturd** [comment]
> > > its all good I will be more detailed
> > > Did u delete Yaagl OS folder in /Applications Support?
> > > You can Locate the folder in Library(it is a hidden folder)
> > > when you are on a Finder window > Press "Go" on the left Menu bar > Then press "Go to Folder" > Type Library .
> > > Locate a Folder called "Applications support" > inside that folder should be Yaagl OS.
> > 
> > 
> > i did that now, just redownloaded it after fully wiping yaagl off my laptop. finally at least getting an error message .
> > {"code":"NE_FS_FILRDER","message":"Unable to open file: /Applications/GenshinImpact_Data/globalgamemanagers"}
> > cant pick a file
> 
> Make sure Yaagl has the needed access and game is in a single folder not spread across ur home

Also mentioning @sineoxan as they seem to know about wine (i have no clue how to work wine.)

i just realized that these are my only wine options. normally its a LOT. idk what this is 
<img width="999" alt="Screenshot 2024-06-25 at 4 16 16 PM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/168102066/41e44c1d-e815-48a7-949f-09b9bad00977">

**Comment by sineoxan** [comment]
For me specifically I have a few options as well. Personally I want to run crossover as my emulator but the option won't pop up. I am currently running genshin on a version shown below 
![Screenshot 2024-06-25 at 10 12 31 PM](https://github.com/yaagl/yet-another-anime-game-launcher/assets/173768511/cacb1492-e0d9-4d99-b661-df4674125ca2)

**Comment by Soliturd** [comment]
> For me specifically I have a few options as well. Personally I want to run crossover as my emulator but the option won't pop up. I am currently running genshin on a version shown below ![Screenshot 2024-06-25 at 10 12 31 PM](https://private-user-images.githubusercontent.com/173768511/343016367-cacb1492-e0d9-4d99-b661-df4674125ca2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Mzg1MDQsIm5iZiI6MTcxOTQzODIwNCwicGF0aCI6Ii8xNzM3Njg1MTEvMzQzMDE2MzY3LWNhY2IxNDkyLWUwZDktNGQ5OS1iNjYxLWRmNDY3NDEyNWNhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQyMTQzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGEyZGYzZmVhODFmYTIyYzA0OTU1MmIyMWRmYzViZWE3YzZhN2MyMDc3Yjg5Y2M0YWYwM2MwNjAwYTliNDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JYbS_DOLCT6f5vcC7ivbeSbZ7sbaDUal5d8P-6vBbEg)
> 
> its very finniky not being able to alt tab and change windows through my first and second monitor. I hope this is just a me problem and that you won't encounter it when you boot it up. (very funky but this wine version works best for me)

AH THANK YOU!! the game actually started and is continually staying on. Im going to download it all and if anything happens ill mention it, but if nothing happens ill close this. Thank you guys so so much for helping
