### ISSUE TITLE
环境异常

### ISSUE THREAD

**Issue by gaohecheng1** [yaagl/yet-another-anime-game-launcher#378]
环境异常，使用GPTK，因为使用wine渲染有问题，尝试过重启，没有用

 - macOS: [e.g. 14.5 Sonoma]
 - Device: [MacBook Pro 2023]
 - CPU:  [M3Max]
 - RAM: [ 36G ]

**Comment by Sipperz** [comment]
Use Crossover wine.

**Comment by gaohecheng1** [comment]
> Use Crossover wine.

I'm using crossover wine

**Comment by Sipperz** [comment]
Describe the full problem you are having

**Comment by gaohecheng1** [comment]
> Describe the full problem you are having

I had solve this problem by changing an network ，thank you
