### ISSUE TITLE
hsr isnt opening 

### ISSUE THREAD

**Issue by akitort** [yaagl/yet-another-anime-game-launcher#379]
it says right side of assignment cant be destructered
im using m1 mac 8 gb ram 14.5 sonoma

**Comment by Sipperz** [comment]
Delete YAAGL HSR folder in /Applications Support, open Star rail it should re-download the environment.

**Comment by akitort** [comment]
> Delete YAAGL HSR folder in /Applications Support, open Star rail it should re-download the environment.

wassup friend we meet again but in diff topic now

**Comment by Sipperz** [comment]
we do indeed, hopefully this time the solution works.

**Comment by akitort** [comment]
> we do indeed, hopefully this time the solution works.

nah it didnt

**Comment by Sipperz** [comment]
you are using the 0.1.14 pre release version?

**Comment by akitort** [comment]
> you are using the 0.1.14 pre release version?

the latest one

**Comment by Sipperz** [comment]
hmm if u look in #Honkai-star-rail chat in discord there is a pinned comment by me, maybe try that build.

**Comment by akitort** [comment]
> you are using the 0.1.14 pre release version?

wait its 0.1.12

**Comment by Sipperz** [comment]
oh that will explain

**Comment by Sipperz** [comment]
its not supported anymore update to new version

**Comment by akitort** [comment]
what to do?

**Comment by Sipperz** [comment]
download the pre-release from "releases" section, delete Yaagl HSR folder from /Applications Support, and install new version.

**Comment by Sipperz** [comment]
oh weird no pre-release tab for u
https://github.com/yaagl/yet-another-anime-game-launcher/releases/tag/0.1.14

**Comment by akitort** [comment]
> oh weird no pre-release tab for u https://github.com/yaagl/yet-another-anime-game-launcher/releases/tag/0.1.14

thanx bro

**Comment by akitort** [comment]
ill let u in if it works in a min

**Comment by Sipperz** [comment]
sounds good

**Comment by Sipperz** [comment]
can be a reason, I am using old release still for genshin, there are weird cases one persons genshin would not work with anything, next version of Yaagl it worked no problem.

**Comment by akitort** [comment]
By The Way yea it opened and is downloading

**Comment by akitort** [comment]
> can be a reason, I am using old release still for genshin, there are weird cases one persons genshin would not work with anything, next version of Yaagl it worked no problem.

should i try it again

**Comment by Sipperz** [comment]
noice it should work rite away, if there is an error open this issue again.

**Comment by Sipperz** [comment]
> > can be a reason, I am using old release still for genshin, there are weird cases one persons genshin would not work with anything, next version of Yaagl it worked no problem.
> 
> should i try it again

worth a shot

**Comment by akitort** [comment]
> noice it should work rite away, if there is an error open this issue again.

ok

**Comment by akitort** [comment]
<img width="1440" alt="Screenshot 2024-06-22 at 9 33 50 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/449d80a0-fee8-41a7-89bd-73db4d4d4744">
this happended twice

**Comment by Sipperz** [comment]
> <img width="1440" alt="Screenshot 2024-06-22 at 9 33 50 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/142984210/449d80a0-fee8-41a7-89bd-73db4d4d4744">
> 
> this happended twice 

Crashing during cutscene? Yeah unfortunately that is the only codec issue we have atm,everything else will work great it will crash during cutscenes, login to star rail on your phone or something to let the cutscene play then launch back on Mac.

**Comment by Sipperz** [comment]
because there is a cutscene when u do that

**Comment by yogithesymbian** [comment]
any updates for the new release ? i would like to try hsr but need confirm this already solved ? 
i see new release on 2 days ago https://github.com/yaagl/yet-another-anime-game-launcher/releases/tag/0.1.19

my engine
```
 mbpm1 ( 8GB ) Sonoma 14.5 
```

**Comment by Menelkir** [comment]
> any updates for the new release ? i would like to try hsr but need confirm this already solved ? i see new release on 2 days ago https://github.com/yaagl/yet-another-anime-game-launcher/releases/tag/0.1.19
> 
> my engine
> 
> ```
>  mbpm1 ( 8GB ) Sonoma 14.5 
> ```

With 8GB I would doubt if you have a good time. HSR is already complicated for people with 16.

**Comment by Sipperz** [comment]
> > > any updates for the new release ? i would like to try hsr but need confirm this already solved ? i see new release on 2 days ago https://github.com/yaagl/yet-another-anime-game-launcher/releases/tag/0.1.19
> > > my engine
> > > ```
> > >  mbpm1 ( 8GB ) Sonoma 14.5 
> > > ```
> > 
> > 
> > With 8GB I would doubt if you'll have a good time. HSR is already complicated for people with 16.
> 
> Ah, okay, thank you for the information. I would like to test with others (maybe Crossover or Parallel Desktop). I can play HSR at 60 FPS with an Android emulator ( m1 ) , but it's paid, not free. So, I am still looking for other solutions.

Crossover cannot run HSR without some tweaking, Parallels requires a lot more RAM to emulate a game like HSR, u can use Playcover to play mobile version of the game, its Completely FREE.
