### ISSUE TITLE
Genshin Impact: Some NPCs only show their faces when you get close

### ISSUE THREAD

**Issue by Usakapi** [yaagl/yet-another-anime-game-launcher#380]
When you turn Dynamic Character Resolution On in Settings / Graphics, some NPCs only show their faces.
It's fine if you turn it Off, but you won't be able to experience Dynamic Character Resolution.

macOS: [Sonoma Version 15.0 Beta (24A5264h)]
Device: [MacBook Pro 14" 2023]
CPU: [Apple M3Pro]
RAM: [36GB]
![スクリーンショット 2024-06-21 16 57 26](https://github.com/yaagl/yet-another-anime-game-launcher/assets/41817604/c779c87f-ea19-4ed4-96cd-a4365911f578)
![スクリーンショット 2024-06-21 17 04 27](https://github.com/yaagl/yet-another-anime-game-launcher/assets/41817604/0e0188a3-08bf-4c62-a420-c5e7ee8f0c3b)
![スクリーンショット 2024-06-21 16 59 24](https://github.com/yaagl/yet-another-anime-game-launcher/assets/41817604/d1c0e50f-8bf4-4bff-bf6a-bf112d77928f)

**Comment by Sipperz** [comment]
its a known thing, Dynamic character resolution cannot be translated correctly

**Comment by Sipperz** [comment]
no workaround for it either, better to have it off as of now.

**Comment by Usakapi** [comment]
I understand. Thank you for your answer.

**Comment by Sipperz** [comment]
The Dynamic Character Resolution smoothens out the edges of characters to make it less pixelated. so there isn't much missing if u have a 1440p or 4k monitor.
