### ISSUE TITLE
The game does not start on wine distributions 9.2 and 8.16

### ISSUE THREAD

**Issue by OksanaMiran** [yaagl/yet-another-anime-game-launcher#381]
The game does not start on wine distributions 9.2 and 8.16

<img width="1273" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/106094748/13246ba6-e30b-4659-8bc6-c38ee832caf9">

System Information:
 - macOS: Sonoma 14.5
 - Device: macBook pro 16 2021
 - CPU: Apple M1 Pro
 - RAM: 16G

Genshin runs only from the wine distribution unstable-bh-gptk-1.0, but the game lags even on minimum settings. I used to use the Wine 9.2 distribution and would like to use it again.
When switching to the 9.2 distribution, the launcher is loading, but then a message about rolling back patches is displayed and the game does not start, and an error message is displayed in the terminal:

<img width="569" alt="image" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/106094748/549ee6bb-41fb-496b-893a-fec6b5bd7ead">

*Rosetta 2 is accurately installed.

**Comment by Sipperz** [comment]
Error is unable to find the protect file which is causing the error, have u tried the pre-release versions?

**Comment by Sipperz** [comment]
Since you have 16gb RAM will recommend using Crossover as wine option for best gameplay.

**Comment by OksanaMiran** [comment]
> Since you have 16gb RAM will recommend using Crossover as wine option for best gameplay.

**Comment by OksanaMiran** [comment]
> Error is unable to find the protect file which is causing the error, it also doesn't have access to the folder where that file is located ,have u tried the pre-release versions? Try giving Yaagl Full disc access and see if that helps.

Yes, I'm currently using Pre-release 0.1.14. Yaagl has full disk access in settings.

**Comment by Sipperz** [comment]
Where are u game files located?

**Comment by OksanaMiran** [comment]
> Where are u game files located?

/Users/oksana/Genshin

**Comment by 3Shain** [comment]
not sure what's the problem but the errors in log are irrelevant, it's presented for everybody.

**Comment by Sipperz** [comment]
Weird issue

**Comment by OksanaMiran** [comment]
Perhaps this matters, but the game stopped launching when the OS update came out about a month ago

**Comment by Sipperz** [comment]
Didn't get reports from other ppl about it, but could be related.
