### ISSUE TITLE
Games keeps minimizing itself

### ISSUE THREAD

**Issue by SeverusBlack** [yaagl/yet-another-anime-game-launcher#383]
16-inch MacBook Pro 
System: MacOS 14.6
Chip: M1 Max
RAM: 32 GB
ENV: crossover (24.0.3)
GAME: GenShin Impact （国服-官服）

The game keeps minimizing itself with uncertain interval. I closed all window organizing tools and apps that might cause this issue (ie. loop, synergy, bartender), but the problem persists. I initial doubled that it was automatically switching to another app with CMD+TAB, but it's not. It's just the game minimizing itself.

**Comment by Zqanx** [comment]
Maybe stage manager? 台前调度

**Comment by SeverusBlack** [comment]
I tried. The issue persists regardless of whether stage manager is on or off. The issue first appeared after I updated to public beta of MacOS 14.6.

**Comment by Zqanx** [comment]
Might be the beta software then... For now, perhaps playing on windowed mode would prevent minimizing? It's up to you at this point.

**Comment by Sipperz** [comment]
Closing this since no response or confirmation on the topic, feel free to re-open the issue if required further help.
