### ISSUE TITLE
I know this is a short form but I need help

### ISSUE THREAD

**Issue by sineoxan** [yaagl/yet-another-anime-game-launcher#384]
not a bug but I want to know why I can't use crossover I have 16 gigs of ram don't I? 
![Screenshot 2024-06-24 at 11 49 07 PM](https://github.com/yaagl/yet-another-anime-game-launcher/assets/173768511/74e13f09-7dd9-4869-bc72-a30ae031d8b2)

**Comment by Sipperz** [comment]
because Yaagl cannot see where u put crossover, give Yaagl and Crossover full disc access to see if that helps

**Comment by sineoxan** [comment]
I checked my disc access and it seems that only crossover can get full disc access
do you know why that happens?

**Comment by sineoxan** [comment]
I granted both full disc access but it still doesn't seem to work

**Comment by Sipperz** [comment]
where is Yaagl and Crossover located on ur system?

**Comment by sineoxan** [comment]
I have 2 different folders for genshin and honkai, honkai works flawlessly but not the same for genshin
do I need to have my files in a specific location?

**Comment by Sipperz** [comment]
different folders are nice, no specific location, just prefer $Home and where Icloud cannot see.

**Comment by sineoxan** [comment]
I see, I there anything I can do to make genshin run with crossover though? or is it just a dealbreaker

**Comment by Sipperz** [comment]
idk what would be causing it to not see crossover, it should work without needing to change anything. Maybe Try reinstalling both, and make sure the apps are in /Applications, (Game files will not be deleted if u delete Yaagl till u put both in one folder).

**Comment by sineoxan** [comment]
just wondering does it matter which patch of genshin it should be?

**Comment by Sipperz** [comment]
patch? no it doesn't matter it works for all patches otherwise wouldn't be a sustained thing
