### ISSUE TITLE
Blank captcha box

### ISSUE THREAD

**Issue by velevetzrose** [yaagl/yet-another-anime-game-launcher#387]
I launched the game and tried to log in, so when it comes to captcha, nothing appears, I looked for the solutions and disabled and enabled AC patch, so it didn't work, are there any suggestions? Thank you

<img width="836" alt="Screenshot 2024-06-27 at 12 21 46 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/173957263/27493588-c4d5-455e-b6a2-1bc7507179ce">

System Information 
 - macOS: Sonoma 14.5
 - Device: MacBook Air M1
 - CPU: Apple M1
 - RAM: 8GB

**Comment by Sipperz** [comment]
1. do it blind by drag drop the puzzle
2. alt-tab minimise/maximise genshin before login
3. try on-off AC patch for the above
4. Spam return key

These are some "workarounds" that has helped int he past give them a try.

**Comment by Sipperz** [comment]
Closing this issue because no response back for quite a while, if u still have this issue feel free to re-open the issue.
