### ISSUE TITLE
please choose a path that is not inside “desktop” “downloads” or “documents”

### ISSUE THREAD

**Issue by virulim** [yaagl/yet-another-anime-game-launcher#389]
**Describe the bug**
i downloaded the genshin launcher and everything but whenever i start up the launcher it says im choosing an invalid path but there’s no other place to put the file, idk what to do. also i watched a tutorial and the guy in the video had a tab under the location thing and i dont have that. 

**Screenshots** 
![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/174260856/017c4dac-54dc-42c4-8a7c-8efdd634e5cb)
![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/174260856/fb4d7442-0525-4318-9528-a1777c8bfaa3) - macOS:  13.6.6 Ventura
 - Device: iMac Retina 5k 27nch 2017
 - CPU: 3.5 GHz Quad-Core Intel Core i5
 - Dedicated GPU (if any): Radeon Pro 575 4 GB

**Comment by Sipperz** [comment]
is ur launcher in /Applications?

Make sure it is in /Applications and not /Applications Support

**Comment by virulim** [comment]
> is ur launcher in /Applications?
> 
> Make sure it is in /Applications and not /Applications Support

it is in applications, yes

**Comment by Sipperz** [comment]
Put it in ur $Home

**Comment by virulim** [comment]
> Put it in ur $Home, Seems like Yaagl didn't get the required permissions to put stuff on those paths, can fix that by giving it full disk access.

oh my god it worked tysm 😭 ![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/174260856/de95e114-2ee8-4ba5-8f5d-97da4edbb0f2)

**Comment by nayandjam3018** [comment]
> Put it in ur $Home, Seems like Yaagl didn't get the required permissions to put stuff on those paths, can fix that by giving it full disk access.

Hello, how do you do this?
