### ISSUE TITLE
decompressing files

### ISSUE THREAD

**Issue by virulim** [yaagl/yet-another-anime-game-launcher#391]
**Describe the bug**
does anyone know how long it takes for the files to decompress in the launcher? its been an hour and it still hasnt done anything

**Screenshots**
![image](https://github.com/yaagl/yet-another-anime-game-launcher/assets/174260856/33e41d70-b165-40ca-aec5-06b869bfd906)

**Comment by Sipperz** [comment]
usually about 20 to 35 mins

**Comment by Sipperz** [comment]
Just closing this cause I believe it was solved in discord chat.
