### ISSUE TITLE
Trying to lunch after downloading it and closing it 

### ISSUE THREAD

**Issue by nuteIq** [yaagl/yet-another-anime-game-launcher#393]
im trying to open YAAGL on the file I chose after downloading it but it keeps saying {"code":"NE_FS_FILRDER", "message":"Unable to open file: /Applications/genshin/GenshinImpact_Data/globalgamemanagers"} 
<img width="623" alt="Screenshot 2024-07-03 at 12 19 25 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/174576007/c0ff76a1-d908-4887-a0b9-eda88b2bfeef">

 - macOS: Version 14.5 
 - Device: mcbook air m3
 - CPU: Apple M3
 - RAM: 16 GB
I downloaded it and clicked launch but I forgot to choose cross over on wine so it dint work, now idk how to reopen it to fix it

**Comment by Sipperz** [comment]
Where are the game files located?

**Comment by nuteIq** [comment]
on applications 
<img width="677" alt="Screenshot 2024-07-03 at 12 31 03 AM" src="https://github.com/yaagl/yet-another-anime-game-launcher/assets/174576007/77fbb4bc-8fee-4b0a-bd42-c62724575a92">

**Comment by Sipperz** [comment]
thats the problem, don't put game file sin Applications, put them in ur $Home in a Folder

**Comment by nuteIq** [comment]
I opened one and moved the files there, still not working its making me download it all over again 🙁

**Comment by Sipperz** [comment]
run integrity check in Yaagl settings

**Comment by nuteIq** [comment]
I'm sorry, can I ask where the integrity option is I can't find it, or is it inside the file?
![Uploading Screenshot 2024-07-03 at 12.52.32 AM.png…]()
