### ISSUE TITLE
Support Zenless Zone Zero

### ISSUE THREAD

**Issue by Bob-cheng** [yaagl/yet-another-anime-game-launcher#395]
Could the author add support for the latest release of Zenless Zone Zero (ZZZ)?

It is just published by miHoYo and requires the miHoYo launcher to start and download, which cannot run on MacOS yet.

Appreciate it so much.

**Comment by Menelkir** [comment]
Yaagl doesn't depend on hoyolauncher at all, so it doesn't matter. What is matter is the time 3Shain will have to implement that. 
And afaik, 3Shain is quite busy right now, so no ETAs, sorry.
