### ISSUE TITLE
Error: Fail to launch aria2.

### ISSUE THREAD

**Issue by superfeimao** [yaagl/yet-another-anime-game-launcher#398]
**Error: Fail to launch aria2.**
Open software prompt Error: Fail to launch aria2 .

**Screenshots**
Error: Fail to launch aria2

**System Information (please complete the following information):**
 - macOS: [版本13.5.2 (22G91) Ventura]
 - Device: [MacbookPro 13.3inch 2020 ]
 - CPU: [Apple M1]
 - RAM: [16G ]

**Comment by Sipperz** [comment]
It's nothing just open it again

**Comment by Sipperz** [comment]
And also read the FAQ For M series 14.4+ Sonoma is required

**Comment by superfeimao** [comment]
> It's nothing just open it again

ok, thanks 

> And also read the FAQ For M series 14.4+ Sonoma is required

ok, thanks
