### ISSUE TITLE
“wine-preloader” Unexpected exit。

### ISSUE THREAD

**Issue by superfeimao** [yaagl/yet-another-anime-game-launcher#399]
**Describe the bug**
Flashback after entering the game for one minute，“wine-preloader” Unexpected exit。

**Screenshots**
<img width="1607" alt="image" src="https://github.com/user-attachments/assets/e93bf951-dd90-44e9-8503-be55cdfbe867">

**System Information (please complete the following information):**
 - macOS: [14.5  Ventura]
 - Device: [MacbookPro 13.3inch 2020 ]
 - CPU: [Apple M1]
 - RAM: [16G ]

**Additional context**
wine version v9.2-mingw

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
[neutralinojs.log](https://github.com/user-attachments/files/16194174/neutralinojs.log)

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory
[ZenlessZoneZero_d3d11.log](https://github.com/user-attachments/files/16194192/ZenlessZoneZero_d3d11.log)

**Comment by Menelkir** [comment]
Arm macs needs Sonoma, it's written in the readme on this repo.

**Comment by superfeimao** [comment]
> Arm macs needs Sonoma, it's written in the readme on this repo.

sorry, I write it wrongly， Actually, my system is Sonoma14.5

**Comment by Menelkir** [comment]
I didn't checked the screenshot either so I've reopened, lol.
Anyways, can you try with crossover? The trial is enough.

**Comment by superfeimao** [comment]
> I didn't checked the screenshot either so I've reopened, lol. Anyways, can you try with crossover? The trial is enough.

What does' try with crossover 'mean， How to operate

**Comment by Menelkir** [comment]
https://github.com/yaagl/yet-another-anime-game-launcher/wiki/FAQ#4-what-is-crossover-and-what-is-wine

**Comment by Sipperz** [comment]
was the error resolved? Make sure to reopen this issue if it wasn't.
