### ISSUE TITLE
Red Screen Upon Launching

### ISSUE THREAD

**Issue by cadauncie** [yaagl/yet-another-anime-game-launcher#400]
I used the Andrew Tsai method/tutorial from youtube, downloaded all the things, am using crossover, yadda yadda, but when I try to open and launch the game It opens with on of two screens. A white screen with a a very faded "hoyoverse" or a bright red screen with nothing else on it. every other time I open it I'll also get at small box in the upper right hand corner with computer info.

I am by no means smart with computer stuff. I don't know computer lingo or anything like that, but im trying my best to understand!! Thank you for the help!

<img width="1680" alt="Screenshot 2024-07-13 at 4 38 20 PM" src="https://github.com/user-attachments/assets/1620f400-7675-4d97-b39a-0e32a5ead2cb">

<img width="1680" alt="Screenshot 2024-07-14 at 10 12 48 AM" src="https://github.com/user-attachments/assets/a2df0a10-a07c-4c1e-a9ed-fdd2b7df1735">

 - macOS: Sonoma 14.5
 - Device: MacBook Pro 15-inch, 2018
 - CPU: 2.2 GHz 6-Core Intel Core i7
 - RAM: 16GB

**Comment by Sipperz** [comment]
how much VRam does your Mac have?

**Comment by cadauncie** [comment]
> how much VRam does your Mac have?

this is what my graphics/memory says

graphics: Intel UHD Graphics 630 1536 MB
memory: 16 GB 2400 MHz DDR4

**Comment by HackingU0** [comment]
Bro this only support Apple Silicon mac because it is based on GPTK.
It is a framework to translate DX instruction set to Metal instruction set

**Comment by HackingU0** [comment]
You can just run the game by using wine, or bootcamp, not by using winecx.
But the game maybe really slow on intel mac.

**Comment by Menelkir** [comment]
> Bro this only support Apple Silicon mac because it is based on GPTK. It is a framework to translate DX instruction set to Metal instruction set

That's not true, isn't based at all only in GPTK, and GPTK only appears if you have an arm mac.

> You can just run the game by using wine, or bootcamp, not by using winecx. But the game maybe really slow on intel mac.

That's not true either, winecx is based on crossover, crossover works quite well on intel macs, isn't arm exclusive. Only d3dmetal is arm exclusive.

**Comment by cadauncie** [comment]
@HackingU0 @Menelkir okay!! I don't know entirely all the things you guys are talking about haha! do either of you know what might be the problem? or have any ideas I could try to resolve it??

Thanks!!<3

**Comment by Menelkir** [comment]
You could try deleting the Yaagl folder inside Application Support, because it seems that something got wrong with the prefix. Are you on the latest crossover? What is the GPU of this macbook?

**Comment by cadauncie** [comment]
@Menelkir yes! im on the latest crossover! my gpu is Intel UHD Graphics 630 1536 MB ?? at least I think? haha!

**Comment by cadauncie** [comment]
@Menelkir I didn't know that haha! and yes??? I have no idea lol I'm gonna be watching some other videos tonight to see if theres a better method for macbook pro with an intel processor :)

**Comment by Menelkir** [comment]
> @Menelkir I didn't know that haha! and yes??? I have no idea lol I'm gonna be watching some other videos tonight to see if theres a better method for macbook pro with an intel processor :)

Well.. for a matter of an example, years ago I've run GI with everything at mid-to-low with a GTX 650 TI Boost with 2G of VRAM and was on the limit. I mean, it probably can run with 1.5G of VRAM, yeah, but that's can also be a limiting factor.

**Comment by Sipperz** [comment]
> > how much VRam does your Mac have?
> 
> this is what my graphics/memory says
> 
> graphics: Intel UHD Graphics 630 1536 MB memory: 16 GB 2400 MHz DDR4

I see we have driven away from the actual issue, was the Issue resolved at all? if not reopen this issue and reply back.
