### ISSUE TITLE
Some characters and objects not loaded properly

### ISSUE THREAD

**Issue by YJK0617** [yaagl/yet-another-anime-game-launcher#402]
**Describe the bug**
Some characters and objects are not loaded properly after updating Yaagl launcher. I have tried with all wines available, the game doesn't launch at all or has this problem. Dynamic character resolution is disabled

**Screenshots**
<img width="1440" alt="스크린샷 2024-07-17 오전 11 11 40" src="https://github.com/user-attachments/assets/2ae2c193-6d5a-448e-9def-3a46578bbfb9">
<img width="1440" alt="스크린샷 2024-07-17 오전 11 12 11" src="https://github.com/user-attachments/assets/cc5f2d0f-b526-4492-a245-74175b63eefa">
<img width="1440" alt="스크린샷 2024-07-17 오전 11 12 35" src="https://github.com/user-attachments/assets/54ed6968-3936-4ed3-8f86-35bb2373283f">
<img width="1440" alt="스크린샷 2024-07-17 오전 11 13 23" src="https://github.com/user-attachments/assets/6987e622-d37d-4021-98eb-e6148f2ec748">
<img width="1440" alt="스크린샷 2024-07-17 오전 11 13 52" src="https://github.com/user-attachments/assets/f1b558ab-8ba3-472c-a72f-1fcd4205465c">

**System Information (please complete the following information):**
 - macOS: [Sonoma 14.5]
 - Device: [Macbook Air 13 inch 2020]
 - CPU: [Apple M1]
 - RAM: [8GB]

**Comment by Sipperz** [comment]
Which wine version are you using?

**Comment by LostCrystal** [comment]
The same thing happens to me, I take care of v9.2-mingw

**Comment by sriram-jakka** [comment]
same happened with me too

**Comment by sriram-jakka** [comment]
i used the same v9.2-mingw which it gives on default

**Comment by casobi1** [comment]
I've got same problem

**Comment by Soliturd** [comment]
try and switch your wine to unstable-bh-gptk-1.0 works pretty ok for me, not sure if there is any other fix

**Comment by Sipperz** [comment]
GPTK or Crossover wine option is best options for all ARM Macs atm, Consider switching to them right away.
