### ISSUE TITLE
Ground isn't rendering correctly.

### ISSUE THREAD

**Issue by Soliturd** [yaagl/yet-another-anime-game-launcher#405]
**Describe the bug**
just really weird bug where the ground is either completely black or rainbow. 
IT ONLY DOES THIS IN THE EVENT AREA. NO WHERE ELSE.
**Screenshots**
<img width="1440" alt="Screenshot 2024-07-21 at 3 49 58 PM" src="https://github.com/user-attachments/assets/fcb803ac-ceaf-4687-91d2-9cb85029f7e6">

**System Information (please complete the following information):**
 -macOS: [Sonoma Version 14.4.1]
Device: [MacBook Air 13" 2020]
CPU: [Apple M1 (i cant find anymore info on the cpu)]
RAM: [8GB]

**Additional context**
I can't tell if this is a glitch with YAAGL, wine or genshin itself. Im using the unstable-bh-gptk-1.0 as I don't have any clue how to use crossover (plus I'm too broke for crossover wine)

**Logs (if any)**

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory. (I can't find this.)

**Comment by Soliturd** [comment]
<img width="1440" alt="Screenshot 2024-07-21 at 7 39 24 PM" src="https://github.com/user-attachments/assets/106aab89-1f00-4ee7-8131-696f7ded5135">
adding this because it didnt look like this before...

**Comment by GafaiZheung** [comment]
same issue here, try settings->wine, change wine version to v8.16-3shain if you are using whisky(I fixed it after doing that)

**Comment by Soliturd** [comment]
> same issue here, try settings->wine, change wine version to v8.16-3shain if you are using whisky(I fixed it after doing that)

I tried that ver of wine and it made my characters look very broken (there is another glitch listed here recently about those wines)

im also not sure what whisky is or how to use it, would that help me?

**Comment by GafaiZheung** [comment]
> > same issue here, try settings->wine, change wine version to v8.16-3shain if you are using whisky(I fixed it after doing that)
> 
> I tried that ver of wine and it made my characters look very broken (there is another glitch listed here recently about those wines)
> 
> im also not sure what whisky is or how to use it, would that help me?

Character issues may be due to low system memory, try lowing image quality( especially make character dramatic resolution disable). From my experience, Whisky has a similar problem, and  in terms of community feedback, crossover maybe the best wine version, try it if you never tried.

**Comment by Soliturd** [comment]
> > > same issue here, try settings->wine, change wine version to v8.16-3shain if you are using whisky(I fixed it after doing that)
> > 
> > 
> > I tried that ver of wine and it made my characters look very broken (there is another glitch listed here recently about those wines)
> > im also not sure what whisky is or how to use it, would that help me?
> 
> Character issues may be due to low system memory, try lowing image quality( especially make character dramatic resolution disable). From my experience, Whisky has a similar problem, and in terms of community feedback, crossover maybe the best wine version, try it if you never tried.

yaagl is the only thing currently on this laptop, says i have 123 GB left in my system. though i dont think im speaking enough about how terrible the characters are on the other types of wine, game is unplayable due to there being items missing, people deformed and the sky literally making everything hard to see.

 i think i might be too broke for crossover regardless tho, way to expensive. (also this isnt me trying to be mean at all, im just super bad at tech stuff and am really dumb 😭)

**Comment by GafaiZheung** [comment]
> yaagl is the only thing currently on this laptop, says i have 123 GB left in my system. though i dont think im speaking enough about how terrible the characters are on the other types of wine, game is unplayable due to there being items missing, people deformed and the sky literally making everything hard to see.
> 
> i think i might be too broke for crossover regardless tho, way to expensive. (also this isnt me trying to be mean at all, im just super bad at tech stuff and am really dumb 😭)

I mean the RAM of system, if lowing image quality not worked, just try crossover.

you don't have to buy it, just download and you will have a 14 days of free trial, following this steps listed at following page, and just change wine version to crossover at Yaagl, environment configuration will be done automatically.

https://github.com/yaagl/yet-another-anime-game-launcher/wiki/CrossOver:-use-latest-MoltenVK

don't worry if your trial is expired, it still works to play the game.

**Comment by Soliturd** [comment]
> > yaagl is the only thing currently on this laptop, says i have 123 GB left in my system. though i dont think im speaking enough about how terrible the characters are on the other types of wine, game is unplayable due to there being items missing, people deformed and the sky literally making everything hard to see.
> > i think i might be too broke for crossover regardless tho, way to expensive. (also this isnt me trying to be mean at all, im just super bad at tech stuff and am really dumb 😭)
> 
> I mean the RAM of system, if lowing image quality not worked, just try crossover.
> 
> you don't have to buy it, just download and you will have a 14 days of free trial, following this steps listed at following page, and just change wine version to crossover at Yaagl, environment configuration will be done automatically.
> 
> https://github.com/yaagl/yet-another-anime-game-launcher/wiki/CrossOver:-use-latest-MoltenVK
> 
> don't worry if your trial is expired, it still works to play the game.

sorry for being such a goofus but i dont understand exactly what im supposed to do with the instructions in the link ya gave me. im genuinely just smooth brained when it comes to tech stuff. am i supposed to do sumthin with terminal? or is it like downloading and adding something to crossover. already downloaded both crossover and the thing that the link told me to download, just not sure what to do now.

**Comment by GafaiZheung** [comment]
> sorry for being such a goofus but i dont understand exactly what im supposed to do with the instructions in the link ya gave me. im genuinely just smooth brained when it comes to tech stuff. am i supposed to do sumthin with terminal? or is it like downloading and adding something to crossover. already downloaded both crossover and the thing that the link told me to download, just not sure what to do now.

 first, download and install crossover on your laptop. Go to https://www.codeweavers.com/crossover/download, finish the form on the page and click 'download trial now', then install it. Choose to trial 14 days if you are required to activate liscense. 

second, download the file and replace it. Quit your crossover app if it's running, click the link below to download a dylib file.
> https://github.com/3Shain/winecx/releases/download/gi-wine-1.0/libMoltenVK.dylib

then open your finder app, press command + shift + G, copy and paste the path to the dialog, then drag the dylib file into the  folder you just opening.
> /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64

last, go to Yaagl app, change the wine version to crossover, confirm modify, enter. your password and just wait.

glad to help you if you have other problems.

**Comment by Soliturd** [comment]
> > sorry for being such a goofus but i dont understand exactly what im supposed to do with the instructions in the link ya gave me. im genuinely just smooth brained when it comes to tech stuff. am i supposed to do sumthin with terminal? or is it like downloading and adding something to crossover. already downloaded both crossover and the thing that the link told me to download, just not sure what to do now.
> 
> first, download and install crossover on your laptop. Go to https://www.codeweavers.com/crossover/download, finish the form on the page and click 'download trial now', then install it. Choose to trial 14 days if you are required to activate liscense.
> 
> second, download the file and replace it. Quit your crossover app if it's running, click the link below to download a dylib file.
> 
> > https://github.com/3Shain/winecx/releases/download/gi-wine-1.0/libMoltenVK.dylib
> 
> then open your finder app, press command + shift + G, copy and paste the path to the dialog, then drag the dylib file into the folder you just opening.
> 
> > /Applications/CrossOver.app/Contents/SharedSupport/CrossOver/lib64
> 
> last, go to Yaagl app, change the wine version to crossover, confirm modify, enter. your password and just wait.
> 
> glad to help you if you have other problems.

i tried it but im not sure where i went wrong. i might not understand what replacing a file means but honestly i could be doing any  part of this wrong honestly. i put the dylib in the folder but nothing is showing up on yaagl

**Comment by GafaiZheung** [comment]
> i tried it but im not sure where i went wrong. i might not understand what replacing a file means but honestly i could be doing any part of this wrong honestly. i put the dylib in the folder but nothing is showing up on yaagl

when you drag the dylib file into the folder, you will see a dialog says 'there is already a same name file, and will you replace or keep them all', choose to replace, and just go to yaagl, change the wine version to crossover, wait for environment configuration and you can play.

**Comment by Soliturd** [comment]
> > i tried it but im not sure where i went wrong. i might not understand what replacing a file means but honestly i could be doing any part of this wrong honestly. i put the dylib in the folder but nothing is showing up on yaagl
> 
> you mean you cannot find crossover option in yaagl? or just doubting why yaagl has nothing showing up after you replace the file? for the former case, check if you are surely installed crossover app( you can find it at your launchpad), and repeat follow steps: when you drag the dylib file into the folder, you will see a dialog says 'there is already a same name file, and will you replace or keep them all', choose to replace, and just go to yaagl, change the wine version to crossover, wait for environment configuration and you can play. for the latter case, there DO HAVE nothing showing in yaagl when you successfully replace the dilib file, just change the wine version to crossover is ok.

ok so i did replace the file in just the general area, i wasnt sure if i was supposed to open anything other than the one using the command. Other than that, i clicked replace file, opened yaagl launcher and checking the wine options it wasnt there

**Comment by GafaiZheung** [comment]
> ok so i did replace the file in just the general area, i wasnt sure if i was supposed to open anything other than the one using the command. Other than that, i clicked replace file, opened yaagl launcher and checking the wine options it wasnt there

I'm not sure what's went wrong during your installation of crossover, if you can find crossover app at launchpad you will see crossover option at wine distribution in yaagl app like the screenshot below.
![截屏2024-07-27 08 32 11](https://github.com/user-attachments/assets/73575c36-5b65-477c-afa7-41b946b189b1)

**Comment by Soliturd** [comment]
> > ok so i did replace the file in just the general area, i wasnt sure if i was supposed to open anything other than the one using the command. Other than that, i clicked replace file, opened yaagl launcher and checking the wine options it wasnt there
> 
> I'm not sure what's went wrong during your installation of crossover, if you can find crossover app at launchpad you will see crossover option at wine distribution in yaagl app like the screenshot below. maybe try to restart your laptop and check if it's here again. ![截屏2024-07-27 08 32 11](https://private-user-images.githubusercontent.com/95577157/352687722-73575c36-5b65-477c-afa7-41b946b189b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1Mzg4MDAsIm5iZiI6MTcyMjUzODUwMCwicGF0aCI6Ii85NTU3NzE1Ny8zNTI2ODc3MjItNzM1NzVjMzYtNWI2NS00NzdjLWFmYTctNDFiOTQ2YjE4OWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE4NTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTZhMzM2YTY0NDExOWRjNWUzNjMxODhlZjA4ZDY4OGFhNWJhMjQ2NzEzZjc1ZTNkZjU2MzhkMDNhMjYzZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rU4LcohMxs_JChGd5-lY2IIHQXC-JyyTnKOE-guL38A)

weirdly enough after the launcher updated it showed up! im checking if it works now. and just to confirm, this can be used after the trial right?

**Comment by GafaiZheung** [comment]
> weirdly enough after the launcher updated it showed up! im checking if it works now. and just to confirm, this can be used after the trial right?

according to me, yes

**Comment by Soliturd** [comment]
> > weirdly enough after the launcher updated it showed up! im checking if it works now. and just to confirm, this can be used after the trial right?
> 
> according to me, yes

sorry, totally forgot to close this, works great now, thanks!

**Comment by Sipperz** [comment]
Nice good to hear thank you for the response, have a good gaming time.
