### ISSUE TITLE
Crossover wine isn't detected if crossover is installed in $HOME Applications directory

### ISSUE THREAD

**Issue by ashuramaruzxc** [yaagl/yet-another-anime-game-launcher#411]
**Describe the bug**
I have specific user crossover installation for it to not bloat my computer because i'm not only who uses it, in various issues ([#399](https://github.com/yaagl/yet-another-anime-game-launcher/issues/399#issuecomment-2225697955), etc... )i found suggestions to use crossover's wine yet i haven't found an option for it at all despite having >=16GB of Unified memory.
In frustrations went into reading source code which suggested to me that yaagl is configured to lookup for crossover's wine in case it installed system-wide e.g `/Applications`
[src/wine/crossover](https://github.com/yaagl/yet-another-anime-game-launcher/blob/main/src/wine/crossover.ts#L1C1-L11C94)

**Screenshots**
![image](https://github.com/user-attachments/assets/b577a7b0-3128-4243-b6b2-65805e1eb844)

**System Information (please complete the following information):**
 - macOS: [ Sonoma 14.5 ]
 - Device: [ Mac Mini 2023 ]
 - CPU: [ M2 PRO ]
 - RAM: [ 16G ]

**Comment by Zqanx** [comment]
Crossover needs to be in /Applications yes, and it needs to be named exactly "CrossOver".

**Comment by ashuramaruzxc** [comment]
did that and it now detects the crossover's wine

Still wouldn't it be better to look in both ~/Applications and /Applications just to be sure that it would get detected regardless or at least adding some section in readme about that?

**Comment by Zqanx** [comment]
I will add this to the FAQ.
