### ISSUE TITLE
Error 31-4302, enable AC patch does not fix. 

### ISSUE THREAD

**Issue by isamon614** [yaagl/yet-another-anime-game-launcher#413]
reinstalled game files before this bug because i was having loading issues with gi and hsr, where gi wouldnt open past the launcher, and that hsr would freeze after i encountered a second loading screen. installed everything again, only to be met with Error 31-4302. previous threads mentioned to enable turn off AC patch, but does not work for me. 

**System Information (please complete the following information):**
14.5 Sonoma
Macbook Pro 14 inch 2021
Apple M1 Pro
16 GB ram

these issues occured after i installed hsr because i wanted to try the game out. im uncertain whether or not installing hsr affected genshin in some way because genshin just would not boot up after installing hsr, then suddenly hsr just would freeze after i get to a loading screen after the first one at the menu. so i uninstalled everything and installed again.

[neutralinojs.log](https://github.com/user-attachments/files/16466646/neutralinojs.log)

**Comment by isamon614** [comment]
does this fix error code 31-4302? i tried your steps and the issue still persists. but i admit im not very good at terminal stuff... the launcher and everything work fine.

**Comment by Sipperz** [comment]
those are steps for CN servers, if ur not on CN servers/Build it might not resolve the issue, please reply to confirm if the issue is resolved or not.

**Comment by Sipperz** [comment]
@GafaiZheung Sorry to delete ur comment without any warning but please do not list those on the issues page, and 3shain is working on putting those straight to the launcher so that step wont be required in the near future.

**Comment by 3Shain** [comment]
it's known problem with no solution.
