### ISSUE TITLE
can't log into genshin

### ISSUE THREAD

**Issue by PEACEBOI712** [yaagl/yet-another-anime-game-launcher#414]
im trying to launch my game from the external hard drive to save space but can login as captcha is on full white . any help anyone!!!
<img width="1440" alt="Screenshot 2024-08-02 at 11 34 23 PM" src="https://github.com/user-attachments/assets/098a1c77-1516-49ec-b824-d222bc328639">

**Comment by PEACEBOI712** [comment]
it happens even while doing verification

**Comment by gaohecheng1** [comment]
turn on ac patch when u login

**Comment by PEACEBOI712** [comment]
ok will try and let u know

**Comment by Sipperz** [comment]
There are few other things one can try, this is not an issue on our end it also happens on other platforms, here are some things that seem to work - 

1. do it blind by drag drop the puzzle
2. alt-tab minimise/maximise genshin before login
3. try on-off AC patch for the above
4. Spam return key.
