### ISSUE TITLE
zzz launcher crash if you try install in a folder where already is ZZZ installed

### ISSUE THREAD

**Issue by milotic** [yaagl/yet-another-anime-game-launcher#417]
**Describe the bug**
zzz launcher crash if you try install in a folder where already is ZZZ installed

**Screenshots**

![Sin título](https://github.com/user-attachments/assets/00bf48ee-cef8-40b6-b40f-6e8b1387c135)

**System Information (please complete the following information):**
 - macOS: sonoma 14.5
 - Device: macbook pro 14, 2021
 - CPU: m1
 - RAM: 16

**Additional context**
doing the same with star rail the launcher accept the game and change the button to "play"

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory

[neutralinojs.d.zip](https://github.com/user-attachments/files/16515316/neutralinojs.d.zip)

**Comment by Zqanx** [comment]
You should try reinstalling the launcher. Make sure to delete the yaagl folder in application support.

**Comment by 3Shain** [comment]
It's a known bug that has been fixed in the pre-release already, or you can wait for the release.

**Comment by milotic** [comment]
ok thanks
