### ISSUE TITLE
Crash at start and somtimes Error 31-4202

### ISSUE THREAD

**Issue by Vohrt** [yaagl/yet-another-anime-game-launcher#420]
**Describe the bug**
When I direct  start the game, the game crash immediately. And if i turn off the internet, the game will start, but will got ERROR 31-4302 when loading to the scene (turn on the internet after game start)

I have selected and unselected anti-cheat pass. no changes happened

**Screenshots**
<img width="1710" alt="截屏2024-08-08 23 26 16" src="https://github.com/user-attachments/assets/6472e68b-5322-4809-b91d-f1914788f6df">

<img width="1710" alt="截屏2024-08-08 23 32 34" src="https://github.com/user-attachments/assets/17808a57-9009-46d6-ba02-57437bc3102e">

**System Information (please complete the following information):**
 - macOS: 15
 - Device: MacBook Air 15inch 2023
 - CPU: Apple M2
 - Dedicated GPU (if any): No
 - RAM: 8G

**Additional context**
Unhandled exception: page fault on execute access to 0x0000000007916d80 in 64-bit code (0x00000007916d80).
Register dump:
 rip:0000000007916d80 rsp:00000000095cfc98 rbp:0000000000000000 eflags:00000206 (   - --  I   - -P- )
 rax:0000000008b90000 rbx:0000000000000000 rcx:00006ffffff9fae0 rdx:0000000007916d80
 rsi:0000000000000000 rdi:0000000000000000  r8:00006ffffff9fae0  r9:0000000000000000 r10:0000000000000000
 r11:0000000000000000 r12:0000000000000000 r13:0000000000000000 r14:0000000000000000 r15:0000000000000000
Stack dump:
0x000000095cfc98:  00006fffffeecc89 0000000000000000
0x000000095cfca8:  0000000000000000 0000000000000000
0x000000095cfcb8:  0000000000000000 0000000000000000
0x000000095cfcc8:  00006ffffff9fb65 0000000000000000
0x000000095cfcd8:  0000000000000000 0000000000000000
0x000000095cfce8:  0000000000000000 0000000000000000
0x000000095cfcf8:  0000000000000000 00000000095cfea0
0x000000095cfd08:  00006ffffffb0f30 00006ffffff56f80
0x000000095cfd18:  0000000000000000 00000000095cfd00
0x000000095cfd28:  0000000000000000 00000000095cfcd0
0x000000095cfd38:  0000000000000000 0000000000000000
0x000000095cfd48:  0000000000000000 0000000000000000
Backtrace:
=>0 0x00000007916d80 (0000000000000000)
0x00000007916d80: add %al, (%rax)
Modules:
Module	Address					Debug info	Name (24 modules, 44 for wow64 not listed)
ELF	0000000000001000-0000000000005000	Deferred        <wine-loader>
ELF	000000000452b000-00000000045e3000	Deferred        ntdll.so
PE	00000000685cc000-00000000685fc000	Deferred        libpng16.16.dylib
ELF	00000000686e3000-00000000686ef000	Deferred        dnsapi.so
ELF	00000000686fc000-00000000688b0000	Deferred        win32u.so
PE	0000000068a98000-0000000068b38000	Deferred        libfreetype.6.dylib
ELF	000000006abde000-000000006abea000	Deferred        ws2_32.so
ELF	000000006abf5000-000000006ac05000	Deferred        bcrypt.so
ELF	000000006ac19000-000000006ac25000	Deferred        crypt32.so
PE	000000006ac3c000-000000006ac60000	Deferred        libintl.8.dylib
PE	000000006ac8c000-000000006aca8000	Deferred        libtasn1.6.dylib
ELF	000000006acd9000-000000006add9000	Deferred        opengl32.so
PE	000000006af34000-000000006af70000	Deferred        libidn2.0.dylib
PE	000000006afd3000-000000006b023000	Deferred        libnettle.8.8.dylib
PE	000000006b077000-000000006b0bf000	Deferred        libhogweed.6.8.dylib
PE	000000006b109000-000000006b2e5000	Deferred        libgnutls.30.dylib
PE	000000006b502000-000000006b646000	Deferred        libp11-kit.0.dylib
PE	000000006b889000-000000006b8fd000	Deferred        libgmp.10.dylib
PE	000000006b9d3000-000000006bb8f000	Deferred        libunistring.5.dylib
ELF	000000006be60000-000000006be70000	Deferred        secur32.so
ELF	000000006beb1000-000000006bf3d000	Deferred        winemac.so
PE	00007ff801b9d000-00007ff801bd9000	Deferred        libsystem_kernel.dylib
PE	00007ff801bd9000-00007ff801be5000	Deferred        libsystem_pthread.dylib
PE	00007ff801c12000-00007ff801c1c000	Deferred        libsystem_platform.dylib
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 start.exe
	00000024    0     
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000078    0     wine_rpcrt4_io
	000000a8    0     wine_rpcrt4_io
	000000c4    0     wine_rpcrt4_io
	000000d8    0     
	000000e4    0     wine_rpcrt4_io
	00000194    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000d0    0     
00000068 winedevice.exe
	0000006c    0     
	0000007c    0     
	00000080    0     wine_sechost_service
	00000084    0     
	00000088    0     
	0000008c    0     
	00000090    0     
00000070 explorer.exe
	00000074    0     
	00000094    0     
	000000a0    0     wine_rpcrt4_server
00000098 plugplay.exe
	0000009c    0     
	000000b0    0     
	000000b4    0     wine_sechost_service
	000000b8    0     wine_rpcrt4_server
000000bc svchost.exe
	000000c0    0     
	000000c8    0     
	000000cc    0     wine_sechost_service
000000dc rpcss.exe
	000000e0    0     
	000000e8    0     
	000000ec    0     wine_sechost_service
	000000f0    0     wine_rpcrt4_server
	000000f4    0     wine_rpcrt4_server
	000000f8    0     wine_rpcrt4_io
00000100 cmd.exe
	00000104    0     
00000118 (D) Z:\Volumes\Ventoy\Games\Genshin Impact Game\YuanShen.exe
	0000011c    0     
	00000120    0     
	0000012c    0     
	00000134    0     wine_threadpool_worker
	00000138    0     wine_threadpool_waitqueue
	0000013c    0     
	0000017c    0     
	00000180    0     wine_threadpool_worker
	00000184    0     wine_threadpool_worker
	00000188    0     
	0000018c    0     
	00000190    0     
	00000198    0     wine_threadpool_timerqueue
	0000019c    0     ShaderLoadManagerT
	000001a0    0     
	000001a4    0     
	000001b0    0     
	000001b4    0     wine_threadpool_worker
	000001b8    0     wine_threadpool_worker
	000001bc    0     wine_threadpool_worker
	000001c0    0     wine_threadpool_worker
	000001c4    0     ThreadPoolServiceThread
	000001c8    0     ThreadPoolForegroundWorker
	000001cc   -2     ThreadPoolBackgroundWorker
	000001d0    0     astrolale_main_default
	000001dc    0     
	000001e0   -2     ThreadPoolBackgroundWorker
	000001e4    0     
	000001e8    0     
	000001ec    0     
	000001f0    0     
	000001f4    0     
	000001f8    0     
	000001fc    0     astrolale_url_fetcher
	00000200    0     astrolale_logback
	00000204    0     astrolale_network
	00000208    0     
	0000020c    0 <== 
	00000210    0     
	00000214    0     ThreadPoolForegroundWorker
	00000218    0     PAC thread #0
	0000021c    0     
	00000224    0     wine_threadpool_worker
	00000228    0     wine_threadpool_worker
000001d4 conhost.exe
	000001d8    0     
System information:
    Wine build: wine-8.17
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Darwin
    Host version: 24.0.0

**Logs (if any)**

[neutralinojs.log](https://github.com/user-attachments/files/16550400/neutralinojs.log)
[game_1723131129388.log](https://github.com/user-attachments/files/16550411/game_1723131129388.log)

**Comment by Huaerispro** [comment]
Same, I encountered this problem too. It would be stuck on the loading page right after you enter the door on loading. Then it wouldnt load at all. I tried redownloading the entire game including launcher, and I get the wine error you got.

**Comment by 3Shain** [comment]
32-4202 = we can't really do anything about this

fyi someone get it work by turn on/off ac patch.
