### ISSUE TITLE
Cannot open Yaagl launcher

### ISSUE THREAD

**Issue by YJK0617** [yaagl/yet-another-anime-game-launcher#421]
**Describe the bug**
When I try to open the launcher, it doesn't open and prints {"isTrusted":true} after a while.

**Screenshots**
<img width="1440" alt="스크린샷 2024-08-09 오후 12 15 19" src="https://github.com/user-attachments/assets/c62eaaaf-bc66-4952-ba16-42d2a940d4c2">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.6.1 (It started before updating MacOS)
 - Device: Macbook Air 13 inch 2020
 - CPU: Apple M1
 - RAM: 8G

**Comment by 3Shain** [comment]
are you using the latest version of yaagl? uninstall it completely and try again.

**Comment by milotic** [comment]
Same here, yesterday was working fine


    macOS: sonoma 14.5
    Device: macbook pro 14, 2021
    CPU: m1
    RAM: 16

**Comment by AKSHITXSHARMA** [comment]
I DONE these thing already what to do now

**Comment by AKSHITXSHARMA** [comment]
<img width="1286" alt="Screenshot 2024-08-22 at 11 13 12 AM" src="https://github.com/user-attachments/assets/9c108443-fffb-444f-9e58-76a1b33ba4f8">
I can't open the game launcher what to do??
