### ISSUE TITLE
Error code 31-4302…

### ISSUE THREAD

**Issue by mase25s** [yaagl/yet-another-anime-game-launcher#428]
I’ve tried https://github.com/yaagl/yet-another-anime-game-launcher/issues/255#issuecomment-1950778029 solution, but it hasn’t worked on my MacBook. I can log into the game, but if I enable or not “turn off the ac patch” it doesn’t work. Maybe there’s some problem in 4.8 version or smth else?

**Comment by lorenmt** [comment]
Same here.
