### ISSUE TITLE
cannot open the game , crashes after start game 

### ISSUE THREAD

**Issue by karan68** [yaagl/yet-another-anime-game-launcher#429]
**Describe the bug**

**Screenshots**

**System Information (please complete the following information):**
 - macOS:1 4.5 (23F79)
 - Device: macbook pro 2022
 - CPU: Apple M1 Pro
 
![Uploading Screenshot 2024-08-21 at 7.34.24 PM.png…]()

 - RAM: 16

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by karan68** [comment]
![Uploading Screenshot 2024-08-21 at 7.34.24 PM.png…]()

**Comment by Zqanx** [comment]
We can't see the screenshot.

**Comment by karan68** [comment]
https://ibb.co/HxD54DD

**Comment by karan68** [comment]
I have uploaded the image here :   https://ibb.co/HxD54DD

**Comment by Zqanx** [comment]
Try toggling ac patch

**Comment by AKSHITXSHARMA** [comment]
<img width="1286" alt="Screenshot 2024-08-22 at 11 13 12 AM" src="https://github.com/user-attachments/assets/4430ce95-f95d-4a91-b97f-5e316b39a111">
what I do now I can't open it

**Comment by Zqanx** [comment]
Reinstall launcher, make sure to delete yaagl os folder in /Application support
