### ISSUE TITLE
Error: failed to fetch game information: hk4e_cn

### ISSUE THREAD

**Issue by KexinyingLife** [yaagl/yet-another-anime-game-launcher#432]
show this when launch Yaagl
<img width="532" alt="截屏2024-08-27 17 03 24" src="https://github.com/user-attachments/assets/485792ba-862b-4ed0-b8b2-05f9884cc211">

**Comment by ka2048** [comment]
I also received the same error message.

**Comment by ka2048** [comment]
I deleted the software after it went to the recycle bin, and then I also deleted the directory /Users/username/Library/Application Support/Yaagl. After reinstalling, I no longer encountered this error.
