### ISSUE TITLE
Can't launch the game

### ISSUE THREAD

**Issue by VoidicChaos** [yaagl/yet-another-anime-game-launcher#439]
**Describe the bug**
When I hit launch game, it says "Game is running (DO NOT CLOSE THE LAUNCHER), but after that, all messages disappear, I can hit the Launch Game button again, but no game opens.

**System Information (please complete the following information):**
 - macOS: Sonoma 14.6.1
 - Device: 24-inch, M1, 2021
 - CPU: Apple M1
 - RAM: 8GB

**Comment by blackspider-ops** [comment]
Hii I had the same issue i think it is with the wine patch they are using I used Crossover and its wine patch it worked and even the graphics are slightly better

CrossOver gives free access and is paid but you can always go to the sea and get it 

System Information (please complete the following information):

macOS: Sequia 15.1 beta 3
Device: 13-inch, M3, 2024
CPU: Apple M3
RAM: 16GB
