### ISSUE TITLE
Launcher not start

### ISSUE THREAD

**Issue by JustRin** [yaagl/yet-another-anime-game-launcher#440]
**Describe the bug**
I changed from DXVK to Whisky and see this on reboot launcher 

**Screenshots**
<img width="1283" alt="Снимок экрана 2024-09-09 в 08 35 21" src="https://github.com/user-attachments/assets/e701f838-56c9-4865-bb03-500a217ae58b">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.6.1
 - Device: MacBook Air M3
 - CPU: Apple M3
 - RAM: 16GB

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 
[neutralinojs.log](https://github.com/user-attachments/files/16925958/neutralinojs.log)

**Comment by 3Shain** [comment]
reinstall completely.
