### ISSUE TITLE
File error

### ISSUE THREAD

**Issue by Fimmm520** [yaagl/yet-another-anime-game-launcher#442]
**Describe the bug**
After updating, the launcher displays "install game" in stead of "launch", but my game files are still in my disk.
When I clicked the "install" button and selected the original folder, the box bellow appeared. Now I cannot launch the game.
**Screenshots**
<img width="532" alt="Screenshot 2024-09-11 at 12 48 53 PM" src="https://github.com/user-attachments/assets/42499beb-8760-4538-829e-92978ab90c92">

**System Information (please complete the following information):**
 - macOS: Sonoma 14.6.1
 - Device: Macbook air M3
 - CPU: M3 
 - Dedicated GPU (if any):M3 10cores
 - RAM:16gb

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by 3Shain** [comment]
Don't put game files in `/Applications`
