### ISSUE TITLE
Empty captcha

### ISSUE THREAD

**Issue by Phaozini** [yaagl/yet-another-anime-game-launcher#444]
Hello! When I'm loging in an empty captcha shows up. Can't pass this puzzle.

**System Information (please complete the following information):**
 - macOS: [Sonoma 14.6.1]
 - Device: [Mac mini M1 2020]
 - CPU: [Apple M1]
  - RAM: [16G ]
![Screenshot 2024-09-14 at 14 10 03](https://github.com/user-attachments/assets/12e69686-1a12-4e24-a19b-59efcba947ea)

**Comment by Zqanx** [comment]
Try toggling ac patch in launcher settings

**Comment by levitskyyy** [comment]
> Try toggling ac patch in launcher settings

please show AC patch checkbox

**Comment by Zqanx** [comment]
> please show AC patch checkbox

It's in launcher settings (gear icon)
