### ISSUE TITLE
Game is keep crashing (Genshin impact)

### ISSUE THREAD

**Issue by 12wer10** [yaagl/yet-another-anime-game-launcher#446]
**Describe the bug**
when I click the start game button, game runs, and crashes after the hoyoverse logo comes out. 
I can't figure out what is the problem is...

**Screenshots**

https://github.com/user-attachments/assets/1260800a-67cb-4b20-82c8-d6e67dddde0d

![image](https://github.com/user-attachments/assets/28f05b1a-0baa-4956-a2d2-aab24a8f8b9b)

**System Information (please complete the following information):**
 - macOS: [14.6.1]
 - Device: [MacbookPro 13 2022 ]
 - CPU: [Apple M2]
 - RAM: [8G ]

**Additional context**
using korean version of Genshin. 
and tried rentia mode, and turn it off again. Didn’t touched other options

**Logs (if any)**

I don’t know the logs are...
> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by 12wer10** [comment]
oh, and I download at my home file. 
<img width="134" alt="스크린샷 2024-09-14 16 12 55" src="https://github.com/user-attachments/assets/cc52660d-cb09-4db3-9497-77b32e4f4f63">

**Comment by Zqanx** [comment]
What wine version are you using? I will recommend gptk here.

**Comment by 12wer10** [comment]
> What wine version are you using? I will recommend gptk here.

oh! I just solve the problem using gptk
thank you for your help☺️
