### ISSUE TITLE
Not sure what to do? 

### ISSUE THREAD

**Issue by Jp-bl** [yaagl/yet-another-anime-game-launcher#447]
I just tried reinstalling Genshin on my Mac, but every time I open YAAGL a fatal error occurs. I looked to see on the FAQ but couldnt find anything, many thanks.

**System Information (please complete the following information):**
 - macOS: 14.6.1 Sonoma
 - Device: Macbook Air 13 Inch 2020
 - CPU: Intel i7 1.2GHz
 - RAM: 16G
 
<img width="1440" alt="Screenshot 2024-09-14 at 18 20 02" src="https://github.com/user-attachments/assets/74619781-d264-40c4-94e6-e92880eac6ca">

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory

**Comment by Zqanx** [comment]
Maybe try reinstalling the launcher completely. Method is on main page of the repo.

**Comment by Jp-bl** [comment]
This worked to get it to start installing, however now im files are installed, when i press launch game, the game doesn't open? thanks.

**Comment by Zqanx** [comment]
You will have to elaborate more for me to be able to help. For now, I will suggest trying different wine versions.

**Comment by Huaerispro** [comment]
> This worked to get it to start installing, however now im files are installed, when i press launch game, the game doesn't open? thanks.

This is a problem with the wine, it usually is resolved by going into settings then choosing a different wine
