### ISSUE TITLE
It's downloading in a loop

### ISSUE THREAD

**Issue by Aisha567L** [yaagl/yet-another-anime-game-launcher#448]
<img width="1275" alt="Screenshot 2024-09-18 at 12 52 19 PM" src="https://github.com/user-attachments/assets/d7a0601e-6012-4be1-93e0-b27fd149d17a">
The version Yaagl.OS.app.tar.gz of 0.2.2

I was downloading this version , but whenever 10Gib is done it again starts to download and forms a loop again and again 

**System Information (please complete the following information):**
 - macOS: ventura 13.5
 - Device: 13.3 inch
 - CPU:  Apple M1
 

please help

**Comment by PTH2023** [comment]
thats because it splits the game into i think about seven parts and you have to download all of them

**Comment by ScathachSkadi** [comment]
Read the FAQ, it has multiple zips. Read the readme, it requires Sonoma 14.4 or up.
