### ISSUE TITLE
Ground isn't rendering correctly.

### ISSUE THREAD

**Issue by wujiki** [yaagl/yet-another-anime-game-launcher#451]
**Describe the bug**

The ground does not render correctly

**Screenshots**
<img width="1512" alt="截屏2024-09-21 17 45 47" src="https://github.com/user-attachments/assets/2c359063-fdbb-4edd-8642-73c3dc1e204b">
<img width="1512" alt="截屏2024-09-21 17 47 17" src="https://github.com/user-attachments/assets/61ef603d-711f-47e5-a737-9c91169a4754">

**System Information (please complete the following information):**
 - macOS: [14.1 Ventura]
 - Device:  MacbookPro 14inch 2021 ]
 - CPU: [ Apple M1pro  ]
 - RAM: [ 16G ]

**Additional context**
The problem only exists in Nata
![图像2024-9-21 18 34](https://github.com/user-attachments/assets/38c3c08a-9134-4098-adc9-5cb8a57fb9bc)

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Zqanx** [comment]
1. Make sure to update to at least sonoma 14.4 to get latest rosetta 2 update
2. In most cases, it is preferable to use crossover dxvk as your wine version, but cases may vary

**Comment by wujiki** [comment]
I tried crossover dxvk,it made sense.Thanks
