### ISSUE TITLE
genshin impact- game won't load after updating to sequoia 15.0

### ISSUE THREAD

**Issue by demmmmmmm** [yaagl/yet-another-anime-game-launcher#452]
after installing the newest version of my macOS, and opening my launcher- once entering in, it remains on the "hoyoverse" screen for a second before staying on a white screen.

is there any way to fix this??

**Comment by demmmmmmm** [comment]
nvm,, i figured out why
I am not wasting my time figuring out how to go back to a past version omds 🙏

**Comment by Zqanx** [comment]
Good to hear that you were able to solve the problem by yourself, you can reopen issue if necessary.
