### ISSUE TITLE
fatal error load il2cpp

### ISSUE THREAD

**Issue by Uraboros08** [yaagl/yet-another-anime-game-launcher#455]
<img width="1440" alt="Снимок экрана 2024-09-25 в 14 21 56" src="https://github.com/user-attachments/assets/c926258d-9c30-4503-b8ea-b566465cea2d">
<img width="1440" alt="Снимок экрана 2024-09-25 в 14 28 04" src="https://github.com/user-attachments/assets/8a3eed0b-b3a9-4f97-bb4f-a82fdea240d5">

**Comment by SipperzZz** [comment]
Launcher is not updated for current version look out for an update in release tab, updating to latest version should resolve the issue.

**Comment by Laggerman784** [comment]
so when is the estimated releasee for the update?

**Comment by ScathachSkadi** [comment]
no ETA
