### ISSUE TITLE
unable to install the game

### ISSUE THREAD

**Issue by grandmasterofalco** [yaagl/yet-another-anime-game-launcher#457]
**Describe the bug**
every time trying to install genshin impact a different error comes up: unable to open, permission denied etc. tried to put game in different folders. i read faq, but found nothing about the problem
I'll be grateful if somebody helps me
**System Information
 - macOS: [15.0]
 - Device: [MacBook Air m1 2020 ]
 - CPU: [Apple M1 ]
![Снимок 26 09 2024 в 11 59](https://github.com/user-attachments/assets/29bad776-7959-4e2e-8324-0afab058ecf1)

 - RAM: [8G ]

**Comment by SipperzZz** [comment]
<img width="876" alt="image" src="https://github.com/user-attachments/assets/fb8ebf1c-ff30-4c82-86c5-ffee73c4e44c">
As the last point states, do not put it in /Applications

Move it to ur $Home in a Folder > Reinstall Launcher > Press Install > Direct it to the folder with game files

**Comment by grandmasterofalco** [comment]
> <img alt="image" width="876" src="https://private-user-images.githubusercontent.com/157293890/371068645-fb8ebf1c-ff30-4c82-86c5-ffee73c4e44c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDI1NzksIm5iZiI6MTcyNzM0MjI3OSwicGF0aCI6Ii8xNTcyOTM4OTAvMzcxMDY4NjQ1LWZiOGViZjFjLWZmMzAtNGM4Mi04NmM1LWZmZWU3M2M0ZTQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwOTE3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGM3NWNkZjQ0Mjc0N2FlYzBlOTYwZDYwMWY1MGJiZTA2ZTBjNmU3NzY3NmU4ZGYzNTFiM2JlYmZjZmI4MDkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nPq3pim4PdsJMlIfP3YIV96tTPNHu87HKu8CIMLyaS4"> As the last point states DO NOT put game files in /Applications
> If u already have the game files downloaded- Move it to ur $Home in a Folder > Reinstall Launcher > Press Install > Direct it to the folder with game files

oops, I missed it. but anyway I tried to put it to almost every folder. but thanks, I'll try to do what you said

**Comment by SipperzZz** [comment]
If it still denies give Yaagl Full disc access from - System settings > Privacy & Security > Full Disc access

If Yaagl wasn't given required permission when it was first launched it will have certain errors

**Comment by grandmasterofalco** [comment]
> If it still denies give Yaagl Full disc access from - System settings > Privacy & Security > Full Disc access
> 
> If Yaagl wasn't given required permission when it was first launched it will have certain errors

 thank you a lot! it started downloading

**Comment by SipperzZz** [comment]
Nice, Your welcome I will close the ticket now IF you bump into more problems feel free to reopen this one

**Comment by grandmasterofalco** [comment]
I'm not sure if this problem connected to previous one, but I'll write it here. ran into some graphics bug
![2024-09-27 16 24 49](https://github.com/user-attachments/assets/75ddb199-8baa-4985-ae45-c73f89276014)
![2024-09-27 16 24 43](https://github.com/user-attachments/assets/d2f1d1b9-ebbc-49f3-84de-647e90c0799c)
![2024-09-27 16 25 02](https://github.com/user-attachments/assets/8af171c6-20ec-40a8-80d5-f9b4f1da7060)
![2024-09-27 16 31 53](https://github.com/user-attachments/assets/bbd3b26e-a9cf-44c3-9d1c-e9268da079b2)
