### ISSUE TITLE
Is it allowed for the hard drive to have many disk space but the internal disk small?

### ISSUE THREAD

**Issue by XaviPlayz** [yaagl/yet-another-anime-game-launcher#459]
**Describe the bug**
I am asking if it is allowed to have small gb on the internal disk bc it says on the faq u need 100g on the internal disk.

**Screenshots**

**System Information (please complete the following information):**
 - macOS: Sequoia 15.0
 - Device: Mac Mini 2020
 - CPU: Apple M1
 - Dedicated GPU (if any): N/A
 - RAM: 8G
 
**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by SipperzZz** [comment]
If u want lower space what u can do is either play it on Playcover OR Install the game then move it to a external drive (make sure drive is APFS Format)
