### ISSUE TITLE
graphics bug

### ISSUE THREAD

**Issue by grandmasterofalco** [yaagl/yet-another-anime-game-launcher#460]
appears mostly in dialogues (actually every dialogue looks like that) and sometimes while playing 

System Information
 - macOS: 15.0
 - Device:  MacBook Air m1 2020
 - CPU: Apple M1
 - RAM: 8G
 using wine 9.9 (not experimental one)
 
![2024-09-27 16 24 49](https://github.com/user-attachments/assets/16af47b2-e2a8-4b51-a7a9-80e5b38c038e)

![2024-09-27 16 31 53](https://github.com/user-attachments/assets/15bb8f71-82ff-490d-a2d7-e1d199e2746e)
![2024-09-27 16 24 43](https://github.com/user-attachments/assets/334868ca-2bb7-4a3a-9550-397a4260b2c6)

I already have an issue, but tbh I didn't manage to reopen it, so i decided to create another.... I'm not sure why I made photos not screenshots, but i guess it doesn't matter

**Comment by SipperzZz** [comment]
8 GB Ram Mac Models with 9.9 wine have these issues, Try Switching to either GPTK or 9.9 DXMT (Experimental)

**Comment by grandmasterofalco** [comment]
> 8 GB Ram Mac Models with 9.9 wine have these issues, Try Switching to either GPTK or 9.9 DXMT (Experimental)

thanks! I switched to 9.9 because the game did't work with "original" wine that was there before. I guess I'll try this one

**Comment by grandmasterofalco** [comment]
It worked, they look normal again!!
