### ISSUE TITLE
So im playing genshin on MacOs with YAAGL OS, and im experiencing this bug(found image on internet but it matches my problem 

### ISSUE THREAD

**Issue by SkibidiSigma0425** [yaagl/yet-another-anime-game-launcher#461]
<img width="607" alt="Screenshot 2024-10-01 at 9 45 45 PM" src="https://github.com/user-attachments/assets/1f0d1631-3d9e-4f25-88a4-970d737e89cc">
<img width="882" alt="Screenshot 2024-10-01 at 9 45 58 PM" src="https://github.com/user-attachments/assets/b600d4f5-4b49-4b4b-ba71-d373abb9cb0d">
pls tell me how to fix

**Comment by 1146839821** [comment]
turn off Dynamic character
