### ISSUE TITLE
Error: failed to fetch game information: hk4e_cn

### ISSUE THREAD

**Issue by OrangeLee03** [yaagl/yet-another-anime-game-launcher#462]
**Describe the bug**
在我打开Yaagl的时候，弹出了一个窗口显示“Error: failed to fetch game information: hk4e_cn”，请问这是什么情况？我需要怎么做？
When I open Yaagl ,a window told me "Error: failed to fetch game information: hk4e_cn" .What's happened ?And what should I do?

**Screenshots**
<img width="532" alt="截屏2024-10-08 21 10 03" src="https://github.com/user-attachments/assets/a11ca765-6244-4104-ad58-ef5ac282ad17">

**System Information (please complete the following information):**
 - macOS: 15.1 Beta Sequoia (24B5046f)
 - Device: MacbookPro 14inch 2021
 - CPU: Apple M1 Pro
 - Dedicated GPU (if any): N/A
 - RAM: 16G

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Stapxs** [comment]
+1
<img width="420" alt="image" src="https://github.com/user-attachments/assets/e428ea61-04c0-4516-8615-67802f38a268">

**Comment by lyzpapo** [comment]
+1

**Comment by ka2048** [comment]
Before the Genshin Impact 5.1 version update, I also encountered this error, but after the version update, it was gone. You can check this discussion on Discord.
[https://discord.com/channels/1085010808678912090/1293136492138467358](url)

**Comment by OrangeLee03** [comment]
This problem is solved now.

**Comment by lyzpapo** [comment]
yeah it appears again

**Comment by hugeBlack** [comment]
It seems that the game company forgot to add a background for `hk4e_cn` and yaagl consider it an error and exit.
```json
{"game":{"id":"1Z8W5NHUQb","biz":"hk4e_cn"},"backgrounds":[]}
```

The code that throws error is:
```ts
  const game = ret.data.game_info_list.find(x => x.game.biz == server.id);
  if (!game || game.backgrounds.length < 1)
    throw new Error(`failed to fetch game information: ${server.id}`);
  return game.backgrounds[0];
```
If this happens every time before version update, can we set a default background for yaagl?
