### ISSUE TITLE
 Wine Mono Installer Fails with Checksum Error When Changing to Wine 9.9 DXMT (Experimental)

### ISSUE THREAD

**Issue by kenryu42** [yaagl/yet-another-anime-game-launcher#463]
### Description:
When attempting to change the wine distribution to Wine 9.9 DXMT (Experimental), the Wine Mono installer consistently fails with a checksum error. This issue persists even after checking the integrity of the installation.

### Steps to Reproduce:
1. Open the wine configuration settings.
2. Attempt to change the wine distribution to Wine 9.9 DXMT (Experimental).
3. Observe the Wine Mono installer initiating.
4. The installer fails with a checksum error.

### Expected Behavior:
The Wine Mono installer should complete successfully, allowing the change to Wine 9.9 DXMT (Experimental) distribution.

### Actual Behavior:
The Wine Mono installer fails with a checksum error, preventing the successful change to the desired wine distribution.

### Additional Information:
- Attempted to check the integrity of the installation, but the issue persists.
- This error occurs consistently on multiple attempts.

### System Information:
- Hardware: Apple M3 Pro
- Memory: 36GB
- Operating System: macOS Sonoma 14.6.1
<img width="385" alt="Screenshot 2024-10-10 at 13 02 51" src="https://github.com/user-attachments/assets/08a532a4-8368-49e6-b172-d1997536e4ca">
<img width="311" alt="Screenshot 2024-10-10 at 13 11 37" src="https://github.com/user-attachments/assets/7b011539-5e7b-4a3a-aa34-1a2e51c5bc79">

**Comment by Zqanx** [comment]
Reinstall launcher completely, make sure you're not using cleaners.
