### ISSUE TITLE
Cannot use controller under Wine 9.9 DXMT

### ISSUE THREAD

**Issue by Fimmm520** [yaagl/yet-another-anime-game-launcher#465]
The game detected the controller. But after I swithed to the controller, it cannot respond.
The controller performs properly under DXVK environment.

**System Information (please complete the following information):**
 - macOS: 15.0.1 sequoia
 - Device: macbook air 13inch 2023 
 - CPU:  Apple M3 
 - Dedicated GPU (if any): Apple M3 10 cores
 - RAM: 16 GB

**Comment by Zqanx** [comment]
It's probably related to wine itself. Perhaps future dxmt release will fix it.

**Comment by Kaiber7** [comment]
Same it still has not been fixed in 2026
