### ISSUE TITLE
您的机器环境异常，请重启机器

### ISSUE THREAD

**Issue by ShawnDiego** [yaagl/yet-another-anime-game-launcher#466]
每次启动都会报“您的机器环境异常，请重启机器”
<img width="751" alt="截屏2024-10-13 09 55 15" src="https://github.com/user-attachments/assets/86f8f9ae-9672-46b1-9fcc-2693b6b63b49">

**Comment by Stapxs** [comment]
之前只会弹一次重新进就好了……这版本重进还会弹，有点苦恼了

**Comment by 1379485765** [comment]
我用whisy 和crossover也报 应该是游戏的事吧 看看有没有新补丁了

**Comment by Stapxs** [comment]
我用 crossover 官启开都报 😮‍💨

**Comment by wujiki** [comment]
i'm the same

**Comment by KexinyingLife** [comment]
一样😭

**Comment by bob-fly** [comment]
一样

**Comment by ka2048** [comment]
+1

**Comment by Zqanx** [comment]
目前没有解决办法，而且问题不止出现在 Mac 上，隔壁 Linux AAGL 也一样报错。各位先 Playcover 什么的将就一下。

**Comment by ShawnDiego** [comment]
这个问题因为米哈游的程序员检测机器的代码了吗在 2024年10月14日，23:00，Anmeifan ***@***.***> 写道：﻿
目前没有解决办法，而且问题不止出现在 Mac 上，隔壁 Linux AAGL 也一样报错。各位先 Playcover 什么的将就一下。

**Comment by bob-fly** [comment]
> 这个问题因为米哈游的程序员检测机器的代码了吗在 2024年10月14日，23:00，Anmeifan ***@***.***> 写道：﻿ 目前没有解决办法，而且问题不止出现在 Mac 上，隔壁 Linux AAGL 也一样报错。各位先 Playcover 什么的将就一下。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

有大概什么时候修复吗？

**Comment by bob-fly** [comment]
> security_server_default_iplist_cn_gf01
我这里看了下，日志里面内容没有报错也触发了，奇怪。

**Comment by Zqanx** [comment]
> 希望有用非国服的朋友提供一下信息进行比对

国际服好像没有这个文件或类似的


另外这是 Linux 端现在用的方法，可以参考一下。https://github.com/kamikaze211/linux_hoyogames?tab=readme-ov-file#xxxxx-4001%E5%BC%B9%E7%AA%97%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

**Comment by littlewu2508** [comment]
> 另外这是 Linux 端现在用的方法，可以参考一下。https://github.com/kamikaze211/linux_hoyogames?tab=readme-ov-file#xxxxx-4001%E5%BC%B9%E7%AA%97%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

我之前用过这个方法，5.1 最新的情况下已经失效了

**Comment by KexinyingLife** [comment]
> > 另外这是 Linux 端现在用的方法，可以参考一下。https://github.com/kamikaze211/linux_hoyogames?tab=readme-ov-file#xxxxx-4001%E5%BC%B9%E7%AA%97%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
> 
> 我之前用过这个方法，5.1 最新的情况下已经失效了

那个改云游戏的方法还可以使用

**Comment by littlewu2508** [comment]
> > > 另外这是 Linux 端现在用的方法，可以参考一下。https://github.com/kamikaze211/linux_hoyogames?tab=readme-ov-file#xxxxx-4001%E5%BC%B9%E7%AA%97%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
> > 
> > 
> > 我之前用过这个方法，5.1 最新的情况下已经失效了
> 
> 那个改云游戏的方法还可以使用

感谢！我复现成功了。接下来研究一下如何让虚拟手柄设备切回键鼠。我找到了 https://github.com/GrantEdwards/uinput-joystick-demo

**Comment by KexinyingLife** [comment]
> > > > 另外这是 Linux 端现在用的方法，可以参考一下。https://github.com/kamikaze211/linux_hoyogames?tab=readme-ov-file#xxxxx-4001%E5%BC%B9%E7%AA%97%E9%97%AE%E9%A2%98%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88
> > > 
> > > 
> > > 我之前用过这个方法，5.1 最新的情况下已经失效了
> > 
> > 
> > 那个改云游戏的方法还可以使用
> 
> 感谢！我复现成功了。接下来研究一下如何让虚拟手柄设备切回键鼠。我找到了 https://github.com/GrantEdwards/uinput-joystick-demo

但我只会用crossover操作，不知道yaagl怎么弄。有什么方法吗

**Comment by mx6436** [comment]
加入启动参数：
```
-platform_type CLOUD_THIRD_PARTY_PC
```
archlinux AAGL 可以正常运行

**Comment by Zqanx** [comment]
> 感谢！我复现成功了。接下来研究一下如何让虚拟手柄设备切回键鼠。我找到了 https://github.com/GrantEdwards/uinput-joystick-demo

不知道为什么之前这么长时间没人试过，但 -use_mobile_platform -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1 或 -use_mobile_platform -platform_type CLOUD_THIRD_PARTY_MAC -is_cloud 1 就能跑了。。。

**Comment by littlewu2508** [comment]
> -platform_type CLOUD_THIRD_PARTY_PC

嗯，我直接用 wine 在命令行跑，这个参数就足够了，无需 `-is_cloud 1` `use_mobile_platform`

**Comment by duanyoushi** [comment]
> > -platform_type CLOUD_THIRD_PARTY_PC
> 
> 嗯，我直接用 wine 在命令行跑，这个参数就足够了，无需 `-is_cloud 1` `use_mobile_platform`

可以提供完整的命令么？我也想试试，感谢

**Comment by littlewu2508** [comment]
> 可以提供完整的命令么？

`WINEPREFIX=<your_wine_prefix> WINEARCH=win64 wine explorer /desktop=test,3840x2160 YuanShen.exe -platform_type CLOUD_THIRD_PARTY_PC`

**Comment by littlewu2508** [comment]
我适配了一下 34736384 / genshin-fps-unlock (pull request 477) 使其可以自定义参数

**Comment by bob-fly** [comment]
> 我适配了一下 34736384 / genshin-fps-unlock (pull request 477) 使其可以自定义参数

老哥，问一下你这里是用mac还是在linux上跑的？我试了下用yaagl的wine跑一致报错

**Comment by Zqanx** [comment]
> 老哥，问一下你这里是用mac还是在linux上跑的？我试了下用yaagl的wine跑一致报错

yaagl 需要自己 build 的。可能 crossover 的话直接 .\YuanShen.exe -platform_type CLOUD_THIRD_PARTY_PC 就可以了。

Build 的话 Github 主页 Readme 的 code 看一下，有方案。参数放在这个位置：yet-another-anime-game-launcher/src/clients/mhy/hk4e/program-launch-game.ts。

<img width="923" alt="截屏2024-10-18 上午10 27 11" src="https://github.com/user-attachments/assets/0e97b8f7-185e-4687-905e-518a0ab9fe0c">

**Comment by duanyoushi** [comment]
> > 老哥，问一下你这里是用mac还是在linux上跑的？我试了下用yaagl的wine跑一致报错
> 
> yaagl 需要自己 build 的。可能 crossover 的话直接 .\YuanShen.exe -platform_type CLOUD_THIRD_PARTY_PC 就可以了。
> 
> Build 的话 Github 主页 Readme 的 code 看一下，有方案。参数放在这个位置：yet-another-anime-game-launcher/src/clients/mhy/hk4e/program-launch-game.ts。
> 
> <img alt="截屏2024-10-18 上午10 27 11" width="923" src="https://private-user-images.githubusercontent.com/163211683/377905711-0e97b8f7-185e-4687-905e-518a0ab9fe0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDI2NTYsIm5iZiI6MTcyOTMwMjM1NiwicGF0aCI6Ii8xNjMyMTE2ODMvMzc3OTA1NzExLTBlOTdiOGY3LTE4NWUtNDY4Ny05MDVlLTUxOGEwYWI5ZmUwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwMTQ1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2FiNzVhMjViNjI5NjM0YTcwMmFmZjE2ZjA1MGI0ZWMxMzdiMzExMThhZjFhM2FkMjE2MGVmYThkN2YxMGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BQ_Aql_vHpavjyb11VAmOzoXFhL7sxBj8ZuH1KHKMOk">

果真直接用Crossover添加参数就可以运行。

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/feb80d2a-d5ed-4a63-9847-25efe3483a76">

**Comment by bob-fly** [comment]
> > > 老哥，问一下你这里是用mac还是在linux上跑的？我试了下用yaagl的wine跑一致报错
> > 
> > 
> > yaagl 需要自己 build 的。可能 crossover 的话直接 .\YuanShen.exe -platform_type CLOUD_THIRD_PARTY_PC 就可以了。
> > Build 的话 Github 主页 Readme 的 code 看一下，有方案。参数放在这个位置：yet-another-anime-game-launcher/src/clients/mhy/hk4e/program-launch-game.ts。
> > <img alt="截屏2024-10-18 上午10 27 11" width="923" src="https://private-user-images.githubusercontent.com/163211683/377905711-0e97b8f7-185e-4687-905e-518a0ab9fe0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDI2NTYsIm5iZiI6MTcyOTMwMjM1NiwicGF0aCI6Ii8xNjMyMTE2ODMvMzc3OTA1NzExLTBlOTdiOGY3LTE4NWUtNDY4Ny05MDVlLTUxOGEwYWI5ZmUwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwMTQ1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2FiNzVhMjViNjI5NjM0YTcwMmFmZjE2ZjA1MGI0ZWMxMzdiMzExMThhZjFhM2FkMjE2MGVmYThkN2YxMGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BQ_Aql_vHpavjyb11VAmOzoXFhL7sxBj8ZuH1KHKMOk">
> 
> 果真直接用Crossover添加参数就可以运行。
> 
> <img alt="image" width="1145" src="https://private-user-images.githubusercontent.com/3644321/378042356-feb80d2a-d5ed-4a63-9847-25efe3483a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjk0ODUsIm5iZiI6MTcyOTMyOTE4NSwicGF0aCI6Ii8zNjQ0MzIxLzM3ODA0MjM1Ni1mZWI4MGQyYS1kNWVkLTRhNjMtOTg0Ny0yNWVmZTM0ODNhNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTlUMDkxMzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGVmMDM2Y2Q4ODY1NmZhZDc4NWQzN2Y3ZTE3OTg1ZTBkMGZlYTE4NWYxYjBkMGE4MzMzZDZiZjU5OTUxZDZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IoNWVW9sedjY_BGXzYECfQ8ETzo74Npvey4il6GSZkY">

我咋没想到呢，直接在crossover用。
找了半天自己把wine装了一遍～

**Comment by bob-fly** [comment]
> > 老哥，问一下你这里是用mac还是在linux上跑的？我试了下用yaagl的wine跑一致报错
> 
> yaagl 需要自己 build 的。可能 crossover 的话直接 .\YuanShen.exe -platform_type CLOUD_THIRD_PARTY_PC 就可以了。
> 
> Build 的话 Github 主页 Readme 的 code 看一下，有方案。参数放在这个位置：yet-another-anime-game-launcher/src/clients/mhy/hk4e/program-launch-game.ts。
> 
> <img alt="截屏2024-10-18 上午10 27 11" width="923" src="https://private-user-images.githubusercontent.com/163211683/377905711-0e97b8f7-185e-4687-905e-518a0ab9fe0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzAyNjUsIm5iZiI6MTcyOTMyOTk2NSwicGF0aCI6Ii8xNjMyMTE2ODMvMzc3OTA1NzExLTBlOTdiOGY3LTE4NWUtNDY4Ny05MDVlLTUxOGEwYWI5ZmUwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwOTI2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTViYmM3NjJmZjdiMDY2MTU5ZjliMjI5NDk4OWU1YzQ5ZDM4NmY5OWRiMjA4ZDFiZTdkYTM4YTJmYmE4ODI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4Jh6RLKiOe2BGKmqziR72PfB6d598FNQmQeVJOB4Ik4">

发现wine mac安装编译兼容性具复杂，因此找了个编译好的wine https://github.com/gcenx/homebrew-wine
安装完直接加上yaagl的 prefix就可以运行了，命令如下：

WINEESYNC=1 \
WINEPREFIX=/Users/{user}/Library/Application\ Support/Yaagl/wineprefix \
WINEARCH=win64 \
wine ~/{path}/YuanShen.exe -platform_type CLOUD_THIRD_PARTY_PC

**Comment by 3Shain** [comment]
should be fixed by latest release
