### ISSUE TITLE
Left alt keybind not working

### ISSUE THREAD

**Issue by AbdulKhalid009** [yaagl/yet-another-anime-game-launcher#470]
When playing genshin, i want to use my cursor which has the left alt binding but nothing seems to work

System Infomation
 - macOS: [15.01.1]
 - Device: [e.g. MacbookPro 16inch]
 - CPU: [Apple M2 Pro ]
 - RAM: [e.g. 16G ]

**Comment by Sipperz** [comment]
Check Yaagl settings and try messing around with Mapping to CMD
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/e15fee9a-aa53-44c4-bfc2-3264762f9b9d">

**Comment by AbdulKhalid009** [comment]
THANKS SOOOOO MUCH, i had it one already so I just turned it off thank you
