### ISSUE TITLE
Stuck on "Patching Gaming Files"

### ISSUE THREAD

**Issue by Awesomeplayer165** [yaagl/yet-another-anime-game-launcher#471]
**Describe the bug**
After installing Genshin Impact (on 0.2.6, Yaagl.OS.app.tar.gz), my game stays stuck on "Patching Game Files"

**Screenshots**

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/30e61012-d9f9-4cd6-a1dd-6ece8521d5d6">

**System Information (please complete the following information):**
 - macOS: macOS Sequoia 15.1
 - Device: Macbook Pro 14 inch, 2021
 - CPU: Apple M1 Max
 - RAM: 64GB (yes, 64)

**Additional context**
I accidentally installed and played the `Yaagl.app.tar.gz` and was able to get into the game. The text was in Chinese I believe? Logging into the game didn't work. so I deleted those game files and reinstalled the game through Yaagl.OS.app.tar.gz. both were running `0.2.6`. I've tried uninstalling (I did a uninstall of the following directories via raycast).

Integrity check passes.

Also, I would like to note that I have tried removing both the Yaagl and Yaagl OS application support folders along with the above image. Directories are `~/Library/Application Support/Yaagl` and `~/Library/Application Support/Yaagl OS`

It has stayed on `Patching Game Files` for 1 hour (the longest I've left it on). I've tried multiple times through the method I've described earlier.

**Logs (if any)**
[neutralinojs.log](https://github.com/user-attachments/files/17485293/neutralinojs.log)

**Comment by Sipperz** [comment]
Probably related to wine not being able to patch, try changing wine to 9.9 DXMT experimental

**Comment by Sipperz** [comment]
issue was solved in discord server support chat
