### ISSUE TITLE
Struggling to install HSR game

### ISSUE THREAD

**Issue by nayandjam3018** [yaagl/yet-another-anime-game-launcher#472]
**Describe the bug**

Currently having a hard time trying to install HSR using the Yaagl launcher- Keeps saying I change the download path other than those listed below in the screenshots, then whenever I try to lead it to a different path other than the ones it doesn't allow, it says this error.

**Screenshots**
<img width="474" alt="Screenshot 2024-10-23 at 19 41 26" src="https://github.com/user-attachments/assets/3c02dfa8-3ee0-41a6-bee2-f4b7f215012f">
<img width="803" alt="Screenshot 2024-10-23 at 19 41 21" src="https://github.com/user-attachments/assets/7dc45ab0-1362-4cee-86a6-faa686eb5939">
<img width="407" alt="Screenshot 2024-10-23 at 19 32 22" src="https://github.com/user-attachments/assets/51bb314e-b9b3-4009-b91f-d8ad235d9618">

**System Information (please complete the following information):**
 - macOS: Sequoia 15.0.1 
 - Device: Retina 4K, 21.4-inch, 2019
 - CPU: 3 GHz 6-Core Intel Core i5
 - Dedicated GPU (if any): Radeon Prop 560X 4 GB
 - RAM: 8GB

**Comment by Sipperz** [comment]
Permission issues, Give Yaagl full disc access in system settings

**Comment by nayandjam3018** [comment]
> Permission issues, Give Yaagl full disc access in system settings

I've already done it, still says the same thing

**Comment by 3Shain** [comment]
Fully uninstall and reinstall yaagl

Go to discord for any further problem support.
