### ISSUE TITLE
数据异常，请完全卸载游戏，并从官方渠道重新下载安装错误码：31-4302

### ISSUE THREAD

**Issue by ShawnDiego** [yaagl/yet-another-anime-game-launcher#479]
<img width="861" alt="截屏2024-10-26 11 13 15" src="https://github.com/user-attachments/assets/f043067a-9640-4ba2-85cc-e54ab9e476a8">
最新版还是这样

**Comment by Shrungior** [comment]
我也一样，好几天了，不知道问题在哪。

用之前的老方法，Crossover里运行命令，yuanshen.exe -platform_type CLOUD_THIRD_PARTY_PC

这样可以启动游戏不报错。

**Comment by ShawnDiego** [comment]
我输入我完整路径才能启动
"完整的路径" -platform_type CLOUD_THIRD_PARTY_PC
