### ISSUE TITLE
HSR installation doesnt work

### ISSUE THREAD

**Issue by Nor-maxz** [yaagl/yet-another-anime-game-launcher#480]
it cant install
it gives an error when trying to install

**Screenshots**

![Screenshot 2024-10-31 at 4 18 19 PM](https://github.com/user-attachments/assets/2e579333-0219-4d23-82c8-81ec391d372d)
**System Information (please complete the following information):**
![Screenshot 2024-10-31 at 4 19 07 PM](https://github.com/user-attachments/assets/703fabc2-c4b4-49e9-b0fd-1a1efeebe4e2)

this is the official installer from this github page

**Comment by 1146839821** [comment]
Please refer to #441
