### ISSUE TITLE
The launcher encountered Error: Assertation failed (gameSegmentZips.length > 1) on HSR. idk how to fix that

### ISSUE THREAD

**Issue by akachi484** [yaagl/yet-another-anime-game-launcher#483]
I download yaagl open it everything is fine when i install however it shows me an error (sc below)
 
 <img width="420" alt="Screenshot 2024-11-06 at 13 04 12" src="https://github.com/user-attachments/assets/8b112c38-e2fb-4693-81ce-4b88b3c26252">
 
 - macOS: 13.2.1 Ventura
 - Device:  MacbookPro 13.3 inch 
 - CPU: Apple M1
 - RAM: 8GB

**Comment by sohardcement** [comment]
same to me 

macOS 15.1  M1 pro

**Comment by ScathachSkadi** [comment]
It's a 7zip decompression error. We don't support 7zip decompression. You need to get the game files elsewhere and move over.
