### ISSUE TITLE
Error installing yaagl hsr

### ISSUE THREAD

**Issue by VoidEUW** [yaagl/yet-another-anime-game-launcher#485]
I got a problem installing the hsr anime game. After selecting a location for the game (on a SSD not the internal drive for storage shortage reasons) it crashes immediately throwing this error:

Error: Assertation failed (gameSegmentZips.length > 1)! please file an issue.

Here as a screenshot:
<img width="532" alt="Error" src="https://github.com/user-attachments/assets/d791a114-fb55-43db-8fd6-a97c5d86ee7d">

**System Information (please complete the following information):**
 - macOS: Sequoia Developer Beta
 - Device: MacBook Air 2020
 - CPU: M1
 - Dedicated GPU (if any): M1
 - RAM: 16GB
 - Wine Distribution: -

**Comment by ScathachSkadi** [comment]
we don't support 7zip decompression. Please use sth else to download the game and move the files over. Void, there is literally the alternatives on Discord check it.
