### ISSUE TITLE
encounter "TypeError: Invalid Version" after GI 5.2 updated

### ISSUE THREAD

**Issue by mashimaro221** [yaagl/yet-another-anime-game-launcher#487]
**Describe the bug**
Encounter "TypeError: Invalid Version" after GI 5.2 updated.  
After GI 5.2 pre-download and decompress , I've encountered this problem when opening Yaagl.
However after Yaagl reinstalled(uninstalled with application support folder removed), when installing game within the exist GI folder, this problem is still exist.

**Screenshots**
![image](https://github.com/user-attachments/assets/6a620dab-85c4-4fa3-aa34-be1251f4312b)

**System Information (please complete the following information):**
 - macOS: 14.5 (23F79)
 - Device: MacbookPro 14-inch, 2021 
 - CPU: Apple M1 Pro
 - Dedicated GPU (if any): [e.g.  AMD Radeon Pro 5300M ]
 - RAM: 32G
 - Wine Distribution: [check it in Setting]

**Additional context**

**Logs (if any)**

![image](https://github.com/user-attachments/assets/3a2b7f76-3bf8-495a-8864-7a9a6bbbca24)

**Comment by potatoprincess988** [comment]
I'm having this same issue. idk anything about coding i just want my welkin moon :(

**Comment by ScathachSkadi** [comment]
Launcher problems. Wait until we update or open manually with wine.

**Comment by Uraboros08** [comment]
and how to do it?

**Comment by ScathachSkadi** [comment]
> and how to do it?

1. Wait until launcher update.
2. Launch manually with wine.
3. Read English.

**Comment by Uraboros08** [comment]
and without updating via wine?

**Comment by ScathachSkadi** [comment]
> and without updating via wine?how to open the app via wine

🤣
If you don't know, **wait**

**Comment by Uraboros08** [comment]
does not work

**Comment by ScathachSkadi** [comment]
> does not work

It works after the update. It's your problem.

**Comment by Zharbali** [comment]
It still doesn't work

**Comment by ScathachSkadi** [comment]
> It still doesn't work

Reinstall launcher completely. Make sure you followed github readme(main page). I have seen people on Discord claiming it doesn't work but they eventually figured it out. We fixed it. It's on your side.
