### ISSUE TITLE
Patching game files forever

### ISSUE THREAD

**Issue by TheSwagHaver** [yaagl/yet-another-anime-game-launcher#494]
Yaagl ZZZ OS continually patching game files for a very long time.

<img width="682" alt="Screenshot 2024-11-30 at 10 30 15 PM" src="https://github.com/user-attachments/assets/91903239-a4fd-4547-81b6-26f26ac0f87e">

**System Information (please complete the following information):**
 - macOS: 15.1.1 Sequoia
 - Device: Macbook Air 13 inch
 - CPU: Apple M3
 - RAM: 8G
 - Wine Distribution: wine 9.2 DVXK

I have tried open and close and reinstall.
The game was previously running perfectly fine, it only randomly did this.

**Comment by ScathachSkadi** [comment]
Where did you install game files and the launcher?

**Comment by Adiylikeorange** [comment]
same problem is with me except i have M1 chip

**Comment by ScathachSkadi** [comment]
> > Where did you install game files and the launcher?
> 
> applications

You again. I told you to read the readme. You are not supposed to put it there!

**Comment by TheSwagHaver** [comment]
Sorry for late reply. Fixed it by just changing around the wine version, try latest and downgrade if it doesn’t work.

**Comment by ScathachSkadi** [comment]
Yes. DXMT is best for hoyoverse games currently.
