### ISSUE TITLE
HSR Crashes When Loading Bath Scene at end of Room Decoration Questline

### ISSUE THREAD

**Issue by jckirton** [yaagl/yet-another-anime-game-launcher#500]
**Describe the bug**
When trying to load the cutscene, the game crashes. This includes when trying to load into the game again.

**Screenshots**

**System Information (please complete the following information):**
 - macOS: 15.1
 - Device: MacBook Pro 2020
 - CPU: Apple M1 Pro
 - Dedicated GPU (if any): N/A
 - RAM: 32GB
 - Wine Distribution: Crossover DXVK

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

Log: [game_1733798325621.log](https://github.com/user-attachments/files/18070815/game_1733798325621.log)

**Comment by 1146839821** [comment]
From the log you provided, the gstreamer carried by the crossover is missing some dynamic libraries.
try other wine distribution options
Wine 9.9 DXMT(Experimentl)
DXMT can achieve better performance

**Comment by jckirton** [comment]
> From the log you provided, the gstreamer carried by the crossover is missing some dynamic libraries. try other wine distribution options Wine 9.9 DXMT(Experimentl) DXMT can achieve better performance

That fixed it! Thanks!
