### ISSUE TITLE
Stuck on Allocating Files when Installing

### ISSUE THREAD

**Issue by BentoMic** [yaagl/yet-another-anime-game-launcher#501]
Same issue as before, where I get stuck on the 'allocating files on disk' loading bar when trying to install Genshin Impact 5.1. I left it on all night and it was still loading in a loop, no progress made. The folder I have it in is empty and all the past versions I've downloaded are deleted.

macOS Montery Version 12.5
Macbook Air 13 inch 2019
Apple M1
8 GB

I recall having this problem with past versions (4.0 patches) which I mentioned in another issues. It eventually began downloading resources but it didn't take as long as an entire night.

**Comment by ScathachSkadi** [comment]
Please read the readme. You need macOS 14.4 or later.

**Comment by Adiylikeorange** [comment]
> Please read the readme. You need macOS 14.4 or later.

i have macOS 15.1.1 but same issue is with me too
