### ISSUE TITLE
Error code: 10351-4001 (Abnormal activity detected on your device's operating environment, please restart your machine.)

### ISSUE THREAD

**Issue by Electrizzity** [yaagl/yet-another-anime-game-launcher#507]
This error started at December 18, 2024 (I was using Yaagl since a month or two, and I have had a smooth experience using it until now)
I tried changing the wine distribution a few times, but it did not solve the issue for me. Obviously, I tried restarting and reinstalling. For the other games, Honkai: Star Rail and Zenless Zone Zero, i do not encounter this error, only in Genshin

System Information 
 - macOS: 15.3 Beta (24D5034f)
 - Device: 13-inch, M1, 2020
 - CPU: Apple M1
 - RAM: 16GB
 - Wine Distribution: Wine 9.9 DXMT (Experimental)

<img width="1680" alt="Screenshot 2024-12-19 at 2 00 21 PM" src="https://github.com/user-attachments/assets/232e83a2-4737-41cd-a3e9-002e3c889591" />

[game_1734583712052.log](https://github.com/user-attachments/files/18193347/game_1734583712052.log)

**Comment by ScathachSkadi** [comment]
We are aware of this issue and we think it is related to what happened on the CN server #466 .
Unlike everyone being affected by it on CN, I personally have not experienced this issue. After we confirm this can be a fix to global servers as well, we will probably push the fix. However, it is also worth noting that CN players got banned recently. So, be careful when playing.

**Comment by Electrizzity** [comment]
Thank you for responding and yes, I will be careful

**Comment by Elf0833** [comment]
I have 2 accounts. All accounts are in the Asia server. Whenever I play the main account, this error occurs, but never occurs when playing the sub-account.

**Comment by b0ldtitans** [comment]
> I have 2 accounts. All accounts are in the Asia server. Whenever I play the main account, this error occurs, but never occurs when playing the sub-account.

Can confirm, error could possibly account-related. I also have 2 accounts, both in Asia, and only one is affected by the error (but on mobile both are fine), and I always get the error right after loading the game (after white screen loading the error pops-up)

**Comment by PFang7** [comment]
Same issue for me

**Comment by TechPanda1** [comment]
having the same issue just today :(

**Comment by Jiei-Dux** [comment]
same situation here ;-;

tried changing to:
- Wine-Staging-TkG
- Wine-GE-Proton
- GE-Proton

none worked...

**Comment by ItsXiggy** [comment]
hello Im on the steam deck OLED running through the official launcher using the proton compatibility layer and connecting to the CN server I just started getting this issue today after playing perfectly fine for the past week

OS: SteamOS Holo
OS Version: 3.6.20
Proton version: 9.0-4 
Genshin Server: Asia

**Comment by binnewbs** [comment]
Same thing happened to me, it just happened yesterday, i've been playing the last months without any issues

- EndeavourOS
- Lutris with wine-ge 8-26
- Asia server

I tried changing the wine prefix location but that didn't work

**Comment by UdayPrakashMinz** [comment]
Same problem ‼️
• KDE Neon
• Heroic Game Launcher 
• Wine GE 8-26
Starting from 20/12/24 just after new update live stream. I have been playing on Linux since way before 4.0. 
Today I was able to complete the daily adventure quest, but to do the domain once I have to open the game twice.

**Comment by TUYUygo** [comment]
I am playing on desktop and it is also happening to me. When will it be fixed?

**Comment by feltryzyke** [comment]
Hi! Any update on this guys? I am running an anime game launcher when playing GI and this issue still keeps on popping out.

**Comment by ScathachSkadi** [comment]
Check the new pre-release. You need to manually update. Use at your own risk.

**Comment by feltryzyke** [comment]
Hi, 

Thank you for replying specifically to my inquiry. If ypu don't mind brother, can you specifically direct me by sending me the link where can I manually update my launcher. I am sorry, I am quite not that techy and linux is just my familiar place. 
Thank you. 
Sincerely, 
Brian

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Dec 22, 2024 at 8:42 pm, ***@***.***> wrote:   


Check the new pre-release. You need to manually update. Use at your own risk.

**Comment by ScathachSkadi** [comment]
@feltryzyke This is for macOS. You came to the wrong repository.

**Comment by feltryzyke** [comment]
Oh sorry for that. 

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Dec 22, 2024 at 8:56 pm, ***@***.***> wrote:   


@feltryzyke This is for macOS. You came to the wrong repository.

**Comment by ScathachSkadi** [comment]
@Lzyct This is closed for a reason. If you are on macOS, check releases for pre-release. If you came from AAGL, you are in the wrong repo.

**Comment by UdayPrakashMinz** [comment]
try adding `-platform_type CLOUD_THIRD_PARTY_PC` in the environment: it works for me and i am on linux
![Screenshot_20241225_102824](https://github.com/user-attachments/assets/91b8c810-6e3d-45af-98cd-8346b210cc20)

**Comment by ScathachSkadi** [comment]
@UdayPrakashMinz THIS IS CLOSED FOR A REASON. THE FIX IS ALREADY THERE ON THE PRE-RELEASE FOR MACOS. FOR LINUX, YOUR FIX WORKS AND IT IS THE SAME FOR MACOS.

**Comment by Theadre** [comment]
Many thanks! it was our Christmas gift!

**Comment by SatanOPhehe** [comment]
> @UdayPrakashMinz THIS IS CLOSED FOR A REASON. THE FIX IS ALREADY THERE ON THE PRE-RELEASE FOR MACOS. FOR LINUX, YOUR FIX WORKS AND IT IS THE SAME FOR MACOS.

Is there any fix for YAAGL os?

**Comment by ScathachSkadi** [comment]
@SatanOPhehe bruh, you are joking right? Read the exact sentence you replied to. CHECK THE PRE-RELEASE. Go to releases. I am not replying to this issue starting from now on.

**Comment by S3meer** [comment]
Yes, just solve this problem and its very simple when you are launching (Yaagl) go to seeting and unselect all the thing and use in build win 9 abd then run, you are good to go try this tomorrow i will share the screenshot  as well

**Comment by SatanOPhehe** [comment]
> Yes, just solve this problem and its very simple when you are launching (Yaagl) go to settings and unselect all the thing and use in build win 9  and then run, you are good to go try this tomorrow i will share the screenshot  as well

Could you share the screen shot
