### ISSUE TITLE
[MAC] At first launch it is asking access to your important folders (Photos included)

### ISSUE THREAD

**Issue by jonpol01** [yaagl/yet-another-anime-game-launcher#54]
At first launch.. it is asking access permisions to these critical folders.
I chose to "Don't allow" to all, and seems no problem running the game.
Can we patch not to ask these on first launch?

![Screenshot 2023-04-04 at 10 18 14](https://user-images.githubusercontent.com/10163076/229661704-944f8d86-7c96-4359-a5c3-72fea0dc93d6.png)
![Screenshot 2023-04-04 at 10 18 09](https://user-images.githubusercontent.com/10163076/229661708-c8d9d124-369a-4e6f-9d7b-a3a973f09427.png)
![Screenshot 2023-04-04 at 10 18 05](https://user-images.githubusercontent.com/10163076/229661711-0a011a93-e758-40a0-b2c5-abfd7289ebd3.png)
![Screenshot 2023-04-04 at 10 18 01](https://user-images.githubusercontent.com/10163076/229661712-2f02a967-a828-45b8-a4e0-cd8e21313c4c.png)
![Screenshot 2023-04-04 at 10 17 56](https://user-images.githubusercontent.com/10163076/229661714-22d34ae4-80bf-40fb-b205-6def95bb9850.png)
![Screenshot 2023-04-04 at 10 17 51](https://user-images.githubusercontent.com/10163076/229661717-74049c15-529a-40e7-a241-4eda31f61fee.png)

**Comment by 3Shain** [comment]
That's weird to me because I never asked these permission (maybe by accident? but I've never encounter these prompts). Is there anyone else have the same problem?

**Comment by jonpol01** [comment]
Yeah I understand, that these happens unintentionally.
Haven't found any in your code that explicitly asks for this. 😁

There might be a way to put away this Apple bullshit in some other way.

**Comment by SimplySora** [comment]
I never got these popups.

**Comment by Menelkir** [comment]
Never got this kind of issue in many installs I did to count. I would close this for now since it's weird (?)
