### ISSUE TITLE
The games crash every time I tried to download a language pack

### ISSUE THREAD

**Issue by Flynn-Hill** [yaagl/yet-another-anime-game-launcher#57]
Every time I tried to download a language pack, it initially downloaded quickly at first but after a few second, the download stopped and the game just crashed, very strange so let me know if everyone is experiencing that as well. 

Sorry, I couldn't provide any screenshots, when the game crashes, no crash log from apple was created to I don't even know what's the issue myself. 

 - macOS: macOS Monterey 12.6.1
 - Device: Macbook Pro (13-inch, M1, 2020)
 - CPU: Apple M1
 - Dedicated GPU (if any): n/a, integrated M1 graphics
 - RAM: 8Gb

**Comment by Flynn-Hill** [comment]
A crash log wasn't created when it crashed, is there any other way to get a program log? sorry for the late reply

**Comment by DontyXD** [comment]
I have the same problem. However, I installed the game on external SSD, which format is APFS.
MacBook Air M2 8/256GB
SSD: Lexar

**Comment by Menelkir** [comment]
Is this happens again in the future, feel free to reopen.
