### ISSUE TITLE
Some bugs about Verify or Browser

### ISSUE THREAD

**Issue by Ricardo-F-X** [yaagl/yet-another-anime-game-launcher#62]
When i logged in, game requests my verify code from email. And the verify stage "slide to correct position" is a blank window.
and if i try to log in with twitter, the 3party verify windows is blank still.
I think maybe i need to install some wine support for website?
and i cannot close any blank verify windows.
 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/20970356/230377897-c7a57a05-ded3-48b3-ad4d-9003b0bb8766.png">
<img width="1728" alt="截屏2023-04-06 20 34 57" src="https://user-images.githubusercontent.com/20970356/230380130-ac9f452d-9a8e-4b8d-9510-22d8363867b3.png">
<img width="1372" alt="截屏2023-04-06 20 35 28" src="https://user-images.githubusercontent.com/20970356/230380251-79f91569-6f66-4bbb-81bb-ac016f069889.png">

**System Information (please complete the following information):**
 - macOS: 13.4 Ventura
 - Device: MacbookPro 16inch 2021
 - CPU: APPLE silicon
 - RAM: 16G

[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11170613/neutralinojs.log)

**Comment by Ricardo-F-X** [comment]
this bug also recur in playcover log in process, so i nailed it with twitter-side log in.
BTW, i cannot shutdown the genshin impact game, i must close it with activity moniter. but it works on the launcher.

**Comment by jjarlego** [comment]
> this bug also recur in playcover log in process, so i nailed it with twitter-side log in. BTW, i cannot shutdown the genshin impact game, i must close it with activity moniter. but it works on the launcher.

Same problem with mine. I wanted to try that twitter-side login. How do you do that?

**Comment by Abderrahmantbs** [comment]
same problem. please is there any update who to deal with it?

**Comment by Abderrahmantbs** [comment]
**It is solved For me, I found that you need to Disable SIP (System Integrity Protection):**
-First, shut down your Mac entirely so the screen is black and all other lights are off
-Press down and hold the power/Touch ID button until Loading startup options appear
-Select Options and continue
-If prompted, select the correct storage disk
-Log in with your administrator account
-When Utilities appears in the menu bar, click on it and choose Terminal
-In the terminal window type csrutil disable and type your password when prompted
-Wait for Successfully disabled System Integrity Protection to appear, then restart your Mac
**After logging to genshin impact account you enable it again**

**Comment by filvas** [comment]
I've found a workaround for the "slide to correct position" issue that worked (at least for me): try guesstimating the position of the draggable handle; once you start dragging, the UI appears.
