### ISSUE TITLE
switching audio output device doesn't work

### ISSUE THREAD

**Issue by jNaimXIII** [yaagl/yet-another-anime-game-launcher#75]
As the title says, I launched the game and the default sound output was the speakers. After I connected my headphones and switched the audio output from the menu bar, the game still was playing the sound through the speakers.

It only used the default player from when you start the launcher and doesn't switch mid way according to system settings.

**Comment by 3Shain** [comment]
Probably should be reported to upstream i.e. crossover/wine. I can't fix it.

**Comment by Menelkir** [comment]
This is a known issue that still exists to this day, you have to change the audio output before open the game.
