### ISSUE TITLE
the screen resolution does not change and the rendering quality does not change either. I can choose any of the proposed screen resolutions, but nothing changes

### ISSUE THREAD

**Issue by kissxsis22** [yaagl/yet-another-anime-game-launcher#77]
**Describe the bug**
the screen resolution does not change and the rendering quality does not change either. I can choose any of the proposed screen resolutions, but nothing changes

**Screenshots**

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 monterey]
 - Device: [e.g. MacbookPro 14 2021 ]
 - CPU: [e.g. Apple M1 pro]
 - Dedicated GPU (if any): [e.g.  m1 pro]
 - RAM: [e.g. 16G ]

**Additional context**

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by Menelkir** [comment]
Do you still have this issue?
