### ISSUE TITLE
8BitDo Pro 2 not being recognized

### ISSUE THREAD

**Issue by bmikaili** [yaagl/yet-another-anime-game-launcher#80]
**Describe the bug**
8bitdo pro 2 controller not recognized by game. It's definitely connected to the computer but the game doesn't pick it up.

**System Information (please complete the following information):**
 - macOS: [e.g. 13.1 Ventura]
 - Device: Macbook pro 16 inch 
 - CPU: m1 pro
 - RAM: 32gb

**Comment by 3Shain** [comment]
probably a upstream (wine) issue. I can't solve it.
