### ISSUE TITLE
screen resolution gets reset every time you open the game

### ISSUE THREAD

**Issue by PTH2023** [yaagl/yet-another-anime-game-launcher#81]
**Describe the bug**
every time you close and re open the game with retina mode enabled the screen resolution gets reset

**System Information (please complete the following information):**
 - macOS: [e.g. 13.3.1 Ventura]
 - Device: [e.g. MacbookPro 14inch 2021]
 - CPU: [Apple M1 Pro]
 - RAM: [e.g. 16G ]

**Comment by PTH2023** [comment]
the in game settings about the screen resolution are not saved
when changed in game:
<img width="1512" alt="Screenshot 2023-04-22 at 7 59 59 PM" src="https://user-images.githubusercontent.com/131446954/233796117-1fb05179-2fd5-4fa6-a922-a5caae94dc70.png">
when both the game and the launcher are completely closed and opened again:
<img width="1512" alt="Screenshot 2023-04-22 at 8 03 16 PM" src="https://user-images.githubusercontent.com/131446954/233796190-99f46bb2-7ddc-4e62-adac-7750df6103d9.png">

**Comment by Anfid** [comment]
This issue affects me too. It may be important to mention that other graphics settings are preserved across restarts, only screen resolution is reset.

**Comment by Menelkir** [comment]
Do you still have this issue?
