### ISSUE TITLE
Freeze when enter city

### ISSUE THREAD

**Issue by deefdon** [yaagl/yet-another-anime-game-launcher#86]
**Describe the bug**
I play about 30 hour Everything run well until I go to this city ,It starting freeze evertime without  Do anythings just run

**Screenshots**

**System Information (please complete the following information):**
 - macOS: 13.3.1
 - Device: MacbookPro 16inch 2022]
 - CPU: [e.g. Apple M2 max
 - Dedicated GPU (if any):38 core gpu
 - RAM: 32

**Additional context**
I run with wine 1.2 ,I try to change version 1.0 but it can't start
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11332492/neutralinojs.log)

I try to reinstall but still [happen]([url](url))
<img width="1728" alt="Screenshot 2566-04-26 at 18 55 40" src="https://user-images.githubusercontent.com/131873167/234568503-4189d052-c048-4066-9703-7e6ecbdcb42b.png">

**Logs (if any)**

> If it's related to the launcher, upload `neutralinojs.log` in Yaagl Data Directory 

> If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory

**Comment by deefdon** [comment]
I try to changed 1.0.2 it show blue screen so I change to 1.0.3 It's crash when cutscene
[neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11339814/neutralinojs.log)

**Comment by 3Shain** [comment]
> I try to changed 1.0.2 it show blue screen so I change to 1.0.3 It's crash when cutscene [neutralinojs.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11339814/neutralinojs.log)

Wrong log. Can read this line: If it's related to the game, upload `logs/game_{timestamp}.log in Yaagl Data Directory?

**Comment by deefdon** [comment]
[game_1682510035501.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11359484/game_1682510035501.log)
[game_1682508226522.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11359485/game_1682508226522.log)

[game_1682508110600.log](https://github.com/3Shain/yet-another-anime-game-launcher/files/11359486/game_1682508110600.log)

Oh I am sorry  here I upload log file

**Comment by 3Shain** [comment]
Found nothing suspicious. I can't solve it for now.
